;;;; Independent S-LAZY acceptance: Chapter 4, sections 4.1.3-4.1.4.
;;;; No traversal methods or slot mutation; the reference-host test reads the thunk accessor.
(in-package #:sophie-lisp.tests)

(parachute:define-test core.sealed-types-and-reference-host-instantiation
  (unwind-protect
       (parachute:fail
         (eval '(defclass core-001-lazy-seq-subclass (sl:lazy-seq) ()))
         error)
    (ignore-errors
      (setf (find-class 'core-001-lazy-seq-subclass nil) nil)))
  (unwind-protect
       (parachute:fail
         (eval '(defclass core-001-map-entry-subclass (sl:map-entry) ()))
         error)
    (ignore-errors
      (setf (find-class 'core-001-map-entry-subclass nil) nil)))
  ;; Reference-host characterization (SBCL): MAKE-INSTANCE succeeds with empty slots.
  ;; This may be revisited if explicit enforcement is ever added; do not force NODE.
  (let ((node (make-instance 'sl:lazy-seq))
        (entry (make-instance 'sl:map-entry)))
    (parachute:true (typep node 'sl:lazy-seq))
    (parachute:is eq nil (sophie-lisp.internal::lazy-node-thunk node))
    (parachute:true (typep entry 'sl:map-entry))
    (parachute:is eq nil (sl:entry-key entry))
    (parachute:is eq nil (sl:entry-value entry))))

(defun lazy-check-step (node empty-p &optional element rest)
  ;; Force outside Parachute's condition handlers so SIGNAL and CERROR reach
  ;; the test's resumable-condition handler before an assertion observes them.
  (let ((actual-empty-p (not (null (sl:seq-emptyp node)))))
    (parachute:is eq empty-p actual-empty-p))
  (unless empty-p
    (parachute:is eq element (sl:seq-first node))
    (parachute:is eq rest (sl:seq-rest node))))

(parachute:define-test lazy-seq.macro-laziness-and-arity
  (let ((calls 0) (element (list :before)) (node nil))
    (flet ((lexical-result () (sl:lazy-cons element nil)))
      (macrolet ((lexical-form () '(progn (incf calls) (lexical-result))))
        (setf node (sl:lazy-seq (lexical-form)))))
    (parachute:true (typep node 'sl:lazy-seq))
    (parachute:is = 0 calls)
    (setf element (list :after))
    (lazy-check-step node nil element nil)
    (lazy-check-step node nil element nil)
    (parachute:is = 1 calls))
  (parachute:fail (macroexpand-1 '(sl:lazy-seq)) program-error)
  (parachute:fail (macroexpand-1 '(sl:lazy-seq nil nil)) program-error)
  (parachute:fail (macroexpand-1 '(sl:lazy-seq nil nil nil)) program-error))

(parachute:define-test make-lazy-seq.input-validation-and-empty-memoization
  (dolist (bad (list 'identity 'list nil t 17 "thunk" '(lambda () nil)
                    (gensym "NOT-A-FUNCTION-")))
    (parachute:fail (sl:make-lazy-seq bad) type-error))
  (let* ((calls 0)
         (thunk (lambda () (incf calls) nil))
         (node (sl:make-lazy-seq thunk)))
    (parachute:true (typep node 'sl:lazy-seq))
    (parachute:is = 0 calls)
    (lazy-check-step node t)
    (lazy-check-step node t)
    (parachute:is = 1 calls)))

(parachute:define-test lazy-cons.eager-arguments-and-tail-validation
  (let* ((events nil) (tail-calls 0) (element (list :element))
         (tail (sl:lazy-seq (progn (incf tail-calls) (error "Tail forced"))))
         (node (sl:lazy-cons (progn (push :element events) element)
                             (progn (push :rest events) tail))))
    (parachute:is equal '(:rest :element) events)
    (parachute:true (typep node 'sl:lazy-seq))
    (lazy-check-step node nil element tail)
    (lazy-check-step node nil element tail)
    (parachute:is = 0 tail-calls))
  (let ((node (sl:lazy-cons nil nil)))
    (parachute:true (typep node 'sl:lazy-seq))
    (lazy-check-step node nil nil nil))
  (dolist (bad (list t 0 '(1) #(1) #'identity))
    (parachute:fail (sl:lazy-cons :element bad) type-error)))

(parachute:define-test lazy-seq.wrapper-flattening-and-independent-memoization
  (let* ((events nil) (tail-calls 0) (element (list :original))
         (saved-element element)
         (tail (sl:lazy-seq (progn (incf tail-calls) (error "Tail forced"))))
         (fixed (sl:lazy-cons element tail))
         (inner (sl:lazy-seq (progn (push :inner events) fixed)))
         (middle (sl:lazy-seq (progn (push :middle events) inner)))
         (outer (sl:lazy-seq (progn (push :outer events) middle))))
    (parachute:false events)
    (lazy-check-step outer nil saved-element tail)
    (parachute:is equal '(:inner :middle :outer) events)
    ;; Changing the captured binding cannot change ANY successfully resolved node.
    (setf element (list :replacement)
          fixed (sl:lazy-cons element nil))
    (dolist (node (list inner middle outer outer))
      (lazy-check-step node nil saved-element tail))
    (parachute:is equal '(:inner :middle :outer) events)
    (parachute:is = 0 tail-calls))
  (let* ((inner-calls 0) (outer-calls 0)
         (inner (sl:lazy-seq (progn (incf inner-calls) nil)))
         (outer (sl:lazy-seq (progn (incf outer-calls) inner))))
    (lazy-check-step outer t)
    (lazy-check-step inner t)
    (lazy-check-step outer t)
    ;; A newly constructed wrapper around an already empty node is also empty.
    (lazy-check-step (sl:lazy-seq inner) t)
    (parachute:is = 1 inner-calls)
    (parachute:is = 1 outer-calls))
  ;; Independent nodes using the identical thunk must not share memoization.
  (let* ((calls 0) (thunk (lambda () (incf calls) nil))
         (a (sl:make-lazy-seq thunk)) (b (sl:make-lazy-seq thunk)))
    (lazy-check-step a t)
    (lazy-check-step b t)
    (lazy-check-step a t)
    (parachute:is = 2 calls)))

(parachute:define-test lazy-seq.invalid-results-retry
  ;; Include multiple values whose PRIMARY value alone would be valid.
  (dolist (bad-values (list nil (list nil nil)
                          (list (sl:lazy-cons :ignored nil) :extra)
                          (list 42) (list '(1)) (list #(1))
                          (list #'identity)))
    (let* ((calls 0) (valid-p nil) (element (list :recovered))
           (fixed (sl:lazy-cons element nil))
           (node (sl:make-lazy-seq
                  (lambda ()
                    (incf calls)
                    (if valid-p fixed (values-list bad-values))))))
      (parachute:is = 0 calls)
      (parachute:fail (sl:seq-emptyp node) type-error)
      (parachute:is = 1 calls)
      (parachute:fail (sl:seq-emptyp node) type-error)
      (parachute:is = 2 calls)
      (setf valid-p t)
      (lazy-check-step node nil element nil)
      (lazy-check-step node nil element nil)
      (parachute:is = 3 calls))))

(parachute:define-test lazy-seq.failure-retry-and-resumable-conditions
  ;; Every failed wrapper must rerun, not merely retain a failed inner node.
  (dolist (failure '(:error :throw :invalid))
    (let* ((events nil) (fail-p t) (tag (gensym "ESCAPE-"))
           (condition (make-condition 'simple-error :format-control "Expected"))
           (element (list :success))
           (inner (sl:lazy-seq
                   (progn
                     (push :inner events)
                     (if fail-p
                         (ecase failure
                           (:error (error condition))
                           (:throw (throw tag condition))
                           (:invalid :not-a-node))
                         (sl:lazy-cons element nil)))))
           (middle (sl:lazy-seq (progn (push :middle events) inner)))
           (outer (sl:lazy-seq (progn (push :outer events) middle))))
      (parachute:false events)
      (ecase failure
        (:error
         (parachute:is eq condition
                       (handler-case (sl:seq-emptyp outer)
                         (simple-error (caught) caught))))
        (:throw
         (parachute:is eq condition
                       (catch tag
                         (sl:seq-emptyp outer)
                         :did-not-throw)))
        (:invalid
         (parachute:fail (sl:seq-emptyp outer) type-error)))
      (parachute:is equal '(:inner :middle :outer) events)
      (setf fail-p nil)
      (lazy-check-step outer nil element nil)
      (parachute:is equal '(:inner :middle :outer :inner :middle :outer) events)
      (dolist (node (list inner middle outer))
        (lazy-check-step node nil element nil))
      (parachute:is = 6 (length events))))
  ;; SIGNAL may return normally; CERROR may resume through CONTINUE.
  (dolist (resumable-error-p '(nil t))
    (let* ((calls 0) (handled 0)
           (condition (make-condition
                       (if resumable-error-p 'simple-error 'simple-condition)
                       :format-control "Resume"))
           (node (sl:lazy-seq
                  (progn (incf calls)
                         (if resumable-error-p
                             (cerror "Continue forcing" condition)
                             (signal condition))
                         nil))))
      (handler-bind ((simple-condition
                      (lambda (caught)
                        (when (eq caught condition)
                          (incf handled)
                          (when resumable-error-p (continue caught))))))
        (lazy-check-step node t)
        (lazy-check-step node t))
      (parachute:is = 1 calls)
      (parachute:is = 1 handled))))

(parachute:define-test lazy-seq.recursive-forcing-retry-and-self-tail
  (let ((node nil) (calls 0) (recurse-p t))
    (setf node (sl:lazy-seq
                (progn (incf calls)
                       (when recurse-p (sl:seq-emptyp node))
                       nil)))
    (parachute:fail (sl:seq-emptyp node) program-error)
    (parachute:fail (sl:seq-emptyp node) program-error)
    (parachute:is = 2 calls)
    (setf recurse-p nil)
    (lazy-check-step node t)
    (lazy-check-step node t)
    (parachute:is = 3 calls))
  ;; A handler INSIDE the thunk can unwind the recursive attempt and succeed.
  (let ((node nil) (calls 0) (handled 0) (element (list :handled)))
    (setf node (sl:lazy-seq
                (progn
                  (incf calls)
                  (handler-case (sl:seq-emptyp node)
                    (program-error () (incf handled)))
                  (sl:lazy-cons element nil))))
    (lazy-check-step node nil element nil)
    (lazy-check-step node nil element nil)
    (parachute:is = 1 calls)
    (parachute:is = 1 handled))
  ;; Returning oneself is also transitive recursive forcing, not emptiness.
  (let ((node nil) (cycle-p t) (calls 0))
    (setf node (sl:lazy-seq (progn (incf calls) (if cycle-p node nil))))
    (parachute:fail (sl:seq-emptyp node) program-error)
    (setf cycle-p nil)
    (lazy-check-step node t)
    (parachute:is = 2 calls))
  ;; Public construction suffices: resolving NODE gives it a fixed self-rest.
  (let ((node nil) (calls 0) (element (list :forever)))
    (setf node (sl:lazy-seq (progn (incf calls) (sl:lazy-cons element node))))
    (dotimes (index 4)
      (declare (ignorable index))
      (lazy-check-step node nil element node))
    (parachute:is = 1 calls)))

(parachute:define-test lazy-seq.predicate-and-representation
  (let* ((calls 0)
         (node (sl:lazy-seq (progn (incf calls) nil)))
         (fixed (sl:lazy-cons nil nil)))
    (parachute:true (sl:lazy-seq-p nil))
    (parachute:false (typep nil 'sl:lazy-seq))
    (dolist (object (list node fixed))
      (parachute:true (sl:lazy-seq-p object))
      (parachute:true (typep object 'sl:lazy-seq)))
    (dolist (object (list t 0 '(nil) #() "" #'identity))
      (parachute:false (sl:lazy-seq-p object)))
    (parachute:is = 0 calls)
    (lazy-check-step node t)
    (parachute:true (sl:lazy-seq-p node))
    (parachute:true (typep node 'sl:lazy-seq))
    (parachute:is = 1 calls)))

(parachute:define-test lazy-seq.single-value-contracts
  ;; This identical case is selected in fresh source and compiled runner modes.
  ;; Record exact public value counts, including predicate generalized truth.
  (let ((calls 0) (fail-p t) (element (list :value)))
    (let* ((constructed
             (multiple-value-list
              (sl:lazy-seq
               (progn (incf calls)
                      (if fail-p (values nil :extra)
                          (sl:lazy-cons element nil))))))
           (node (first constructed)))
      (parachute:is = 1 (length constructed))
      (parachute:true (typep node 'sl:lazy-seq))
      (parachute:is = 0 calls)
      (parachute:fail (sl:seq-emptyp node) type-error)
      (parachute:is = 1 calls)
      (setf fail-p nil)
      (lazy-check-step node nil element nil)
      (lazy-check-step node nil element nil)
      (parachute:is = 2 calls)
      (parachute:is = 1 (length (multiple-value-list (sl:lazy-seq-p node))))
      (parachute:true (sl:lazy-seq-p node))))
  (parachute:is = 1 (length (multiple-value-list (sl:make-lazy-seq (lambda () nil)))))
  (parachute:is = 1 (length (multiple-value-list (sl:lazy-cons nil nil))))
  (lazy-check-step nil t))

(defun lazy-wrapper-chain (terminal count)
  "Return a chain of COUNT unresolved wrappers and all wrappers outermost first."
  (let ((current terminal)
        (nodes nil))
    (dotimes (index count)
      (declare (ignore index))
      (let ((result current))
        (setf current (sl:make-lazy-seq (lambda () result))))
      (push current nodes))
    (values current nodes)))

(parachute:define-test lazy-seq.deep-wrapper-stack-safety-and-retry
  ;; A deep failure leaves every unfinished wrapper retryable.
  (let ((fail-p t)
        (calls 0)
        (element (list :retry)))
    (let ((terminal (sl:lazy-seq
                     (progn
                       (incf calls)
                       (if fail-p
                           (error "Deep failure")
                           (sl:lazy-cons element nil))))))
      (multiple-value-bind (outer nodes) (lazy-wrapper-chain terminal 1000)
        (declare (ignore nodes))
        (parachute:fail (sl:seq-emptyp outer) simple-error)
        (parachute:is = 1 calls)
        (setf fail-p nil)
        (lazy-check-step outer nil element nil)
        (parachute:is = 2 calls))))
  ;; Exact value-count and result-type checks apply at any wrapper depth.
  (dolist (producer (list (lambda () (values))
                          (lambda () (values nil :extra))
                          (lambda () :invalid)))
    (let ((valid-p nil)
          (element (list :valid)))
      (let ((terminal (sl:make-lazy-seq
                       (lambda ()
                         (if valid-p
                             (sl:lazy-cons element nil)
                             (funcall producer))))))
        (multiple-value-bind (outer nodes) (lazy-wrapper-chain terminal 100)
          (declare (ignore nodes))
          (parachute:fail (sl:seq-emptyp outer) type-error)
          (setf valid-p t)
          (lazy-check-step outer nil element nil)))))
  ;; A resumed condition in a deep thunk completes and memoizes normally.
  (let ((calls 0)
        (handled 0)
        (condition (make-condition 'simple-condition
                                   :format-control "Resume deep chain")))
    (let ((terminal (sl:lazy-seq
                     (progn
                       (incf calls)
                       (signal condition)
                       nil))))
      (multiple-value-bind (outer nodes) (lazy-wrapper-chain terminal 100)
        (declare (ignore nodes))
        (handler-bind ((simple-condition
                        (lambda (caught)
                          (when (eq caught condition)
                            (incf handled)))))
          (lazy-check-step outer t)
          (lazy-check-step outer t))
        (parachute:is = 1 calls)
        (parachute:is = 1 handled))))
  ;; Direct and indirect wrapper cycles are recursive forcing.
  (let ((node nil))
    (setf node (sl:lazy-seq node))
    (parachute:fail (sl:seq-emptyp node) program-error))
  (let ((a nil)
        (b nil))
    (setf a (sl:lazy-seq b)
          b (sl:lazy-seq a))
    (parachute:fail (sl:seq-emptyp a) program-error)
    (parachute:fail (sl:seq-emptyp b) program-error))
  ;; A thunk may catch recursive forcing and still return a valid node.
  (let ((node nil)
        (handled 0)
        (element (list :recovered)))
    (setf node
          (sl:lazy-seq
           (progn
             (handler-case (sl:seq-emptyp node)
               (program-error () (incf handled)))
             (sl:lazy-cons element nil))))
    (lazy-check-step node nil element nil)
    (lazy-check-step node nil element nil)
    (parachute:is = 1 handled))
  ;; A fixed result whose unforced rest is the resolving node is valid.
  (let ((node nil)
        (element (list :self-tail)))
    (setf node (sl:lazy-seq (sl:lazy-cons element node)))
    (lazy-check-step node nil element node)
    (lazy-check-step node nil element node))
  ;; A nested successful force remains cached if its caller later fails.
  (let ((inner-calls 0)
        (outer-calls 0)
        (fail-p t)
        (element (list :nested)))
    (let* ((inner (sl:lazy-seq
                   (progn
                     (incf inner-calls)
                     (sl:lazy-cons element nil))))
           (outer (sl:lazy-seq
                   (progn
                     (incf outer-calls)
                     (sl:seq-emptyp inner)
                     (if fail-p
                         (error "Outer failure")
                         inner)))))
      (parachute:fail (sl:seq-emptyp outer) simple-error)
      (parachute:is = 1 inner-calls)
      (parachute:is = 1 outer-calls)
      (lazy-check-step inner nil element nil)
      (parachute:is = 1 inner-calls)
      (setf fail-p nil)
      (lazy-check-step outer nil element nil)
      (parachute:is = 1 inner-calls)
      (parachute:is = 2 outer-calls))))

;; Deliberately independent extension: no Sophie traversal helper implements
;; these methods, and no REF or LENGTH method is installed on the base class.
(defclass trav-source ()
  ((items :initarg :items :reader trav-items)))
(defclass trav-child (trav-source) ())
(defclass trav-indexed (trav-source) ())
(defclass trav-unknown-length (trav-source) ())
(defclass trav-length-trap (trav-source) ())
(defvar *trav-observations* nil)
(defvar *trav-condition* nil)

(defmethod sl:seqablep ((source trav-source)) t)
(defmethod sl:seq-emptyp ((source trav-source))
  (push :empty *trav-observations*)
  (null (trav-items source)))
(defmethod sl:seq-first ((source trav-source))
  (push :first *trav-observations*)
  (when *trav-condition* (error *trav-condition*))
  (car (trav-items source)))
(defmethod sl:seq-rest ((source trav-source))
  (push :rest *trav-observations*)
  (when (trav-items source)
    (make-instance 'trav-source :items (cdr (trav-items source)))))
(defmethod sl:seq-ref ((source trav-indexed) index
                       &optional (default nil supplied-p))
  (push (list :ref supplied-p) *trav-observations*)
  (unless (integerp index)
    (error 'type-error :datum index :expected-type 'integer))
  (let* ((items (trav-items source))
         (length (length items))
         (position (if (minusp index) (+ length index) index))
         (tail (and (<= 0 position) (nthcdr position items))))
    (cond (tail (values (car tail) t))
          (supplied-p (values default nil))
          (t (error 'type-error :datum index
                               :expected-type `(integer ,(- length) ,(1- length)))))))

(defmethod sl:seq-length ((source trav-unknown-length))
  (declare (ignore source))
  nil)

(defmethod sl:seq-length ((source trav-length-trap))
  (declare (ignore source))
  (error "SEQ-LENGTH must not be called for a nonnegative SEQ-REF."))

(defun trav-lazy (items)
  (if items (sl:lazy-cons (car items) (trav-lazy (cdr items))) nil))

(defun trav-values (expected present-p thunk)
  (let ((result (multiple-value-list (funcall thunk))))
    (parachute:is = 2 (length result))
    (parachute:is eq expected (first result))
    (parachute:is eq present-p (not (null (second result))))))


(parachute:define-test seqablep.supported-and-rejected-sources
  (let* ((calls 0) (node (sl:lazy-seq (progn (incf calls) nil))))
    (dolist (source (list nil '(nil) #(1) "abc" (make-hash-table) node
                          (make-instance 'trav-child :items '(a))))
      (parachute:true (sl:seqablep source)))
    (dolist (source (list 42 #\a t #'identity (sl:map-entry :key :value)
                          (make-instance 'standard-object)))
      (parachute:false (sl:seqablep source)))
    (parachute:is = 0 calls)))

(parachute:define-test seq-emptyp.empty-and-nil-element-sources
  (let ((calls 0))
    (dolist (source (list nil #() "" (make-hash-table)
                          (make-array 3 :fill-pointer 0 :initial-element :inactive)
                          (sl:lazy-seq (progn (incf calls) nil))))
      (parachute:true (sl:seq-emptyp source))
      (parachute:is eq nil (sl:seq-first source))
      (parachute:is eq nil (sl:seq-rest source)))
    (parachute:is = 1 calls))
  (dolist (source (list '(nil) #(nil) (sl:lazy-cons nil nil)
                        (make-instance 'trav-source :items '(nil))))
    (parachute:false (sl:seq-emptyp source))
    (parachute:is eq nil (sl:seq-first source))))

(parachute:define-test seq-first-and-seq-rest.builtin-and-edge-sources
  (let* ((items (list :a :b :c)) (tail (cdr items)))
    (parachute:is eq :a (sl:seq-first items))
    (parachute:is eq tail (sl:seq-rest items)))
  (dolist (source (list (make-array 4 :initial-contents '(a b c ignored) :fill-pointer 3)
                        (make-array 4 :element-type 'character
                                      :initial-contents "abcx" :fill-pointer 3)))
    (let ((rest (sl:seq-rest source)))
      (parachute:true (sl:lazy-seq-p rest))
      (parachute:is eql (aref source 1) (sl:seq-first rest))
      (parachute:is eql (aref source 2) (sl:seq-ref rest 1))
      (parachute:is eql (aref source 0) (sl:seq-first source))))
  (let* ((tail (sl:lazy-seq (error "Unrequested tail")))
         (node (sl:lazy-cons :head tail)))
    (parachute:is eq :head (sl:seq-first node))
    (parachute:is eq tail (sl:seq-rest node)))
  (let ((dotted (list* :a :b :dot)))
    (parachute:true (sl:seqablep dotted))
    (parachute:is eq :a (sl:seq-first dotted))
    (parachute:is eq (cdr dotted) (sl:seq-rest dotted))
    (parachute:is eq :b (sl:seq-first (cdr dotted)))
    (parachute:fail (sl:seq-rest (cdr dotted)) type-error))
  (let ((cycle (list :a :b)))
    (setf (cddr cycle) cycle)
    (parachute:is eq cycle (sl:seq-rest (sl:seq-rest cycle)))
    (parachute:is eq :b (sl:seq-ref cycle 7)))
  (let ((table (make-hash-table)))
    (setf (gethash :key table) :value)
    (let ((entry (sl:seq-first table)))
      (parachute:true (typep entry 'sl:map-entry))
      (parachute:is eq :key (sl:entry-key entry))
      (parachute:is eq :value (sl:entry-value entry)))
    (parachute:true (sl:lazy-seq-p (sl:seq-rest table)))))


(parachute:define-test seq-ref.read-default-negative-and-errors
  (let ((default (list :default)))
    (dolist (source (list '(nil :b) #(nil :b) (trav-lazy '(nil :b))
                          (make-instance 'trav-source :items '(nil :b))))
      (trav-values nil t (lambda () (sl:seq-ref source 0)))
      (trav-values :b t (lambda () (sl:seq-ref source 1 default)))
      (trav-values :b t (lambda () (sl:seq-ref source -1)))
      (trav-values nil t (lambda () (sl:seq-ref source -2)))
      (trav-values nil nil (lambda () (sl:seq-ref source 2 nil)))
      (trav-values default nil (lambda () (sl:seq-ref source 9 default)))
      (trav-values default nil (lambda () (sl:seq-ref source -10 default)))
      (trav-values nil nil (lambda () (sl:seq-ref source -10 nil)))
      (parachute:fail (sl:seq-ref source 2) type-error)
      (parachute:fail (sl:seq-ref source -10) type-error)
      (dolist (index '(1/2 1.0 nil :index))
        (parachute:fail (sl:seq-ref source index default) type-error)))
    (dolist (source (list '(a b c) #(a b c) "abc"))
      (let ((expected (coerce source 'list)))
        (trav-values (third expected) t (lambda () (sl:seq-ref source -1)))
        (trav-values (second expected) t (lambda () (sl:seq-ref source -2)))
        (trav-values (first expected) t (lambda () (sl:seq-ref source -3)))
        (trav-values default nil (lambda () (sl:seq-ref source -4 default)))
        (parachute:fail (sl:seq-ref source -4) type-error)
        (trav-values default nil (lambda () (sl:seq-ref source -1000000000000 default)))
        (parachute:fail (sl:seq-ref source -1000000000000) type-error)))
    (let ((vector (make-array 3 :initial-contents '(:a :b :c) :fill-pointer 1)))
      (trav-values :a t (lambda () (sl:seq-ref vector -1)))
      (trav-values default nil (lambda () (sl:seq-ref vector -2 default))))
    (let ((string (make-array 3 :element-type 'character
                               :initial-contents "abc" :fill-pointer 1)))
      (parachute:is eql #\a (sl:seq-ref string 0))
      (parachute:is eql #\a (sl:seq-ref string -1))
      (trav-values nil nil (lambda () (sl:seq-ref string 1 nil)))
      (parachute:fail (sl:seq-ref string 1) type-error))
    (trav-values default nil (lambda () (sl:seq-ref nil 0 default)))
    (let ((condition (handler-case (progn (sl:seq-ref nil 0) nil)
                       (type-error (caught) caught))))
      (parachute:is equal '(integer 1 0)
                    (type-error-expected-type condition)))
    (let ((table (make-hash-table)))
      (setf (gethash :key table) nil)
      (let ((result (multiple-value-list (sl:seq-ref table 0))))
        (parachute:is = 2 (length result))
        (parachute:true (second result))
        (parachute:true (typep (first result) 'sl:map-entry))
        (parachute:is eq :key (sl:entry-key (first result)))
        (parachute:is eq nil (sl:entry-value (first result))))
      (trav-values nil nil (lambda () (sl:seq-ref table 1 nil)))
      (trav-values default nil (lambda () (sl:seq-ref table 1 default)))
      (parachute:fail (sl:seq-ref table 1) type-error)
      (multiple-value-bind (entry present-p) (sl:seq-ref table -1 default)
        (parachute:true present-p)
        (parachute:true (typep entry 'sl:map-entry))))
    (let ((cycle (list :a :b :c)))
      (setf (cdddr cycle) cycle)
      (parachute:fail (sl:seq-ref cycle -1 default) simple-error))
    (let ((source (make-instance 'trav-unknown-length :items '(a b))))
      (parachute:fail (sl:seq-ref source -1 default) simple-error))
    (let ((source (make-instance 'trav-length-trap :items '(:a :b))))
      (trav-values :a t (lambda () (sl:seq-ref source 0))))
    (parachute:fail (sl:seq-ref '(a . :dot) 1 default) type-error)
    (parachute:is eq 'a (sl:seq-ref '(a . :dot) 0))
    (let ((dotted (list* :a :b :c :dot)))
      (parachute:fail (sl:seq-ref dotted -1) type-error)))
  (let* ((calls 0)
         (tail (sl:lazy-seq (error "REF over-forced")))
         (node (sl:lazy-seq (progn (incf calls) (sl:lazy-cons :head tail)))))
    (trav-values :head t (lambda () (sl:seq-ref node 0)))
    (trav-values :head t (lambda () (sl:seq-ref node 0 nil)))
    (parachute:is = 1 calls))
  (let* ((calls 0)
         (source (sl:make-lazy-seq
                   (lambda ()
                     (incf calls)
                     (if (< calls 3)
                         (values calls (sl:make-lazy-seq
                                         (lambda ()
                                           (incf calls)
                                           (if (< calls 5)
                                               (values calls nil)
                                               (error "force failure")))))
                         (error "force failure"))))))
    (parachute:fail (sl:seq-ref source -1) error))
  (let* ((calls 0) (node (sl:lazy-seq (progn (incf calls) nil))))
    (trav-values :default nil (lambda () (sl:seq-ref node -1 :default)))
    (parachute:is = 1 calls))
  (let* ((calls 0) (node (sl:lazy-seq (progn (incf calls) nil))))
    (parachute:fail (sl:seq-ref node -1) type-error)
    (parachute:is = 1 calls)))

(parachute:define-test seq-ref.setf-evaluation-and-mutation
  (let ((value (list :new)))
    (dolist (source (list (list :a :b :c)
                          (make-array 4 :initial-contents '(:a :b :c :hidden)
                                        :fill-pointer 3)))
      (let ((events nil))
        (parachute:is equal (list value)
                      (multiple-value-list
                       (setf (sl:seq-ref (progn (push :source events) source)
                                         (progn (push :index events) 1)
                                         (progn (push :default events) :ignored))
                             (progn (push :value events) value))))
        (parachute:is equal '(:value :default :index :source) events)
        (parachute:is eq value (elt source 1))
        (parachute:is eq :a (elt source 0))
        (parachute:is eq :c (elt source 2)))
      (parachute:is equal (list value)
                    (multiple-value-list (setf (sl:seq-ref source -1) value)))
      (parachute:is eq value (elt source 2))
      (dolist (index '(3 -4 1/2 nil))
        (parachute:fail (setf (sl:seq-ref source index :ignored) value) type-error))))
  (let ((string (make-array 4 :element-type 'character
                             :initial-contents "abcx" :fill-pointer 3)))
    (parachute:is equal '(#\z) (multiple-value-list (setf (sl:seq-ref string 1 nil) #\z)))
    (parachute:is equal '(#\y) (multiple-value-list (setf (sl:seq-ref string -1) #\y)))
    (parachute:is string= "azy" string)
    (parachute:is eql #\x (aref string 3))
    (parachute:fail (setf (sl:seq-ref string 3) #\z) type-error)
    (parachute:fail (setf (sl:seq-ref string -1) 42) type-error)
    (parachute:is string= "azy" string))
  (let ((bits (make-array 2 :element-type 'bit :initial-element 0)))
    (parachute:fail (setf (sl:seq-ref bits -1) 2) type-error)
    (parachute:is = 0 (aref bits 1)))
  (dolist (source (list nil #() ""))
    (parachute:fail (setf (sl:seq-ref source -1 :ignored) :new) type-error))
  (let ((cycle (list :a :b :c)))
    (setf (cdddr cycle) cycle)
    (parachute:fail (setf (sl:seq-ref cycle -1 :ignored) :new) simple-error))
  (let ((dotted (list* :a :b :c :dot)))
    (parachute:fail (setf (sl:seq-ref dotted -1) :new) type-error))
  (let ((calls 0))
    (dolist (source (list (sl:lazy-seq (progn (incf calls) nil))
                          (make-hash-table) (make-instance 'trav-source :items '(a))
                          (sl:map-entry :a :b) 42))
      (dolist (index '(0 -1 :invalid))
        (parachute:fail (setf (sl:seq-ref source index nil) :new) simple-error)))
    (parachute:is = 0 calls)))

(parachute:define-test seq-length.finite-unbounded-and-lazy-sources
  (dolist (source (list nil #() "" (sl:lazy-seq nil)))
    (parachute:is = 0 (sl:seq-length source)))
  (dolist (source (list '(a b) #(a b) "ab"
                        (make-array 4 :fill-pointer 2 :initial-element :x)
                        (make-array 4 :element-type 'character :fill-pointer 2
                                      :initial-element #\x)
                        (make-instance 'trav-child :items '(a b))))
    (parachute:is = 2 (sl:seq-length source)))
  (let ((table (make-hash-table)))
    (setf (gethash :a table) nil (gethash :b table) :b)
    (parachute:is = 2 (sl:seq-length table)))
  (let ((cycle (list :prefix :a :b)))
    (setf (cdddr cycle) (cdr cycle))
    (parachute:is eq nil (sl:seq-length cycle)))
  (parachute:fail (sl:seq-length '(a b . :dot)) type-error)
  (let ((calls 0))
    (labels ((unknown (items)
               (sl:lazy-seq (progn (incf calls)
                                   (when items (sl:lazy-cons (car items)
                                                             (unknown (cdr items))))))))
      (let ((node (unknown '(a b c))))
        (parachute:is = 0 calls)
        (parachute:is = 3 (sl:seq-length node))
        (parachute:is = 4 calls)
        (parachute:is = 3 (sl:seq-length node))
        (parachute:is = 4 calls))))
  ;; Public construction, not private slot mutation: first resolve the cycle,
  ;; then ask for its known-unbounded length. Unknown divergent thunks are not
  ;; subjected to LENGTH: the specification permits nontermination there.
  (let ((node nil) (calls 0))
    (setf node (sl:lazy-seq (progn (incf calls) (sl:lazy-cons :forever node))))
    (parachute:is eq :forever (sl:seq-first node))
    (parachute:is eq node (sl:seq-rest node))
    (parachute:is eq nil (sl:seq-length node))
    (parachute:is = 1 calls)))

(parachute:define-test traversal.extension-methods-and-condition-propagation
  (let* ((*trav-observations* nil) (element (list :identity))
         (default (list :absent))
         (source (make-instance 'trav-child :items (list nil element))))
    (parachute:true (sl:seqablep source))
    (trav-values element t (lambda () (sl:seq-ref source 1)))
    (trav-values default nil (lambda () (sl:seq-ref source 2 default)))
    (parachute:fail (sl:seq-ref source 2) type-error)
    (parachute:is = 2 (sl:seq-length source))
    (parachute:true (member :first *trav-observations*)))
  (let* ((*trav-observations* nil)
         (source (make-instance 'trav-indexed :items '(nil :b))))
    (trav-values nil t (lambda () (sl:seq-ref source 0)))
    (trav-values :b t (lambda () (sl:seq-ref source -1)))
    (trav-values nil t (lambda () (sl:seq-ref source -2)))
    (trav-values nil nil (lambda () (sl:seq-ref source 2 nil)))
    (trav-values nil nil (lambda () (sl:seq-ref source -3 nil)))
    (parachute:fail (sl:seq-ref source 2) type-error)
    (parachute:fail (sl:seq-ref source -3) type-error))
  (let* ((*trav-condition* (make-condition 'simple-error :format-control "Extension condition"))
         (source (make-instance 'trav-source :items '(a))))
    (parachute:is eq *trav-condition*
                  (handler-case (sl:seq-ref source 0)
                    (error (caught) caught)))))

(parachute:define-test traversal.non-seqable-rejection-and-single-values
  ;; Non-seqable inputs consistently reject every traversal entry point.
  (dolist (source (list 42 :not-seqable #\a #'identity (sl:map-entry nil nil)))
    (parachute:fail (sl:seq-emptyp source) type-error)
    (parachute:fail (sl:seq-first source) type-error)
    (parachute:fail (sl:seq-rest source) type-error)
    (parachute:fail (sl:seq-ref source 0 nil) type-error)
    (parachute:fail (sl:seq-length source) type-error))
  (let ((source (list :a :b)))
    (dolist (function (list #'sl:seqablep #'sl:seq-emptyp #'sl:seq-first
                            #'sl:seq-rest #'sl:seq-length))
      (parachute:is = 1 (length (multiple-value-list (funcall function source)))))
    (trav-values :b t (lambda () (sl:seq-ref source 1)))))

(parachute:define-test seq-rest.forced-node-stability-after-source-mutation
  (labels ((drain (view)
             (loop with elements = nil
                   until (sl:seq-emptyp view)
                   do (push (sl:seq-first view) elements)
                      (setf view (sl:seq-rest view))
                   finally (return (nreverse elements))))
           (check-eq-elements (expected actual)
             (parachute:is = (length expected) (length actual))
             (loop for before in expected for after in actual
                   do (parachute:is eq before after))))
    ;; Every retained node is forced before changing the object it came from.
    (let* ((first (list :first))
           (second (list :second))
           (third (list :third))
           (source (vector first second third))
           (view (sl:seq-rest source))
           (expected (list second third)))
      (check-eq-elements expected (drain view))
      (setf (aref source 1) :changed
            (aref source 2) :changed)
      (check-eq-elements expected (drain view)))
    (let* ((source (copy-seq "abc"))
           (view (sl:seq-rest source))
           (expected (drain view)))
      (parachute:is equal '(#\b #\c) expected)
      (setf (char source 1) #\x
            (char source 2) #\y)
      (parachute:is equal '(#\b #\c) (drain view)))
    (let* ((key-one (list :key-one))
           (key-two (list :key-two))
           (key-three (list :key-three))
           (value-one (list :value-one))
           (value-two (list :value-two))
           (value-three (list :value-three))
           (table (make-hash-table :test #'eq)))
      (setf (gethash key-one table) value-one
            (gethash key-two table) value-two
            (gethash key-three table) value-three)
      (let* ((view (sl:seq-rest table))
             (entries (drain view))
             (repeated (drain view)))
        (parachute:is = 2 (length entries))
        (check-eq-elements entries repeated)
        (dolist (entry entries)
          (let ((pair (assoc (sl:entry-key entry)
                             (list (cons key-one value-one)
                                   (cons key-two value-two)
                                   (cons key-three value-three))
                             :test #'eq)))
            (parachute:true pair)
            (parachute:is eq (cdr pair) (sl:entry-value entry))))
        (remhash key-one table)
        (remhash key-two table)
        (remhash key-three table)
        (setf (gethash :new-key table) :new-value)
        (check-eq-elements entries (drain view))))))
