(in-package #:sophie-lisp.tests)

(defclass complexity-work-key ()
  ((id :initarg :id :reader complexity-work-id)
   (hash :initarg :hash :reader complexity-work-hash)))
(defvar *complexity-hash-work* 0)
(defvar *complexity-equal-work* 0)
(defmethod sl:hash-code ((key complexity-work-key))
  (incf *complexity-hash-work*) (complexity-work-hash key))
(defmethod sl:equals ((a complexity-work-key) (b complexity-work-key))
  (incf *complexity-equal-work*) (= (complexity-work-id a) (complexity-work-id b)))
(defmethod sl:compare ((a complexity-work-key) (b complexity-work-key))
  (cond ((= (complexity-work-id a) (complexity-work-id b)) :equal)
        ((< (complexity-work-id a) (complexity-work-id b)) :less) (t :greater)))
(defun complexity-work-key (id &optional (hash id))
  (make-instance 'complexity-work-key :id id :hash hash))

(parachute:define-test dict.persistent-updates-have-bounded-work
  (dolist (n '(100 1000 10000))
    (let ((dict (sl:dict)) (versions (make-array (1+ n)))
          (*complexity-hash-work* 0) (*complexity-equal-work* 0))
      (setf (aref versions 0) dict)
      (dotimes (i n)
        (setf dict (sl:dict-set dict (complexity-work-key i) i)
              (aref versions (1+ i)) dict))
      ;; Explicit callback counters catch whole-map rehashing independently of
      ;; timing or allocation-area/GC noise. Old versions stay live throughout.
      (parachute:true (<= n *complexity-hash-work* (* 4 n)))
      (parachute:true (<= *complexity-equal-work* (* 4 n)))
      (parachute:is = n (sl:dict-size dict))
      (let* ((*complexity-hash-work* 0) (*complexity-equal-work* 0)
             (updated (sl:dict-set dict (complexity-work-key (floor n 2)) :changed))
             (removed (sl:dict-without updated (complexity-work-key 0))))
        (parachute:true (<= *complexity-hash-work* 8))
        (parachute:true (<= *complexity-equal-work* 8))
        (parachute:is = (floor n 2) (sl:dict-ref dict (complexity-work-key (floor n 2))))
        (parachute:is eq :changed (sl:dict-ref updated (complexity-work-key (floor n 2))))
        (parachute:false (nth-value 1 (sl:dict-ref removed (complexity-work-key 0))))
        (parachute:is = 0 (sl:dict-ref dict (complexity-work-key 0))))
      (loop for size from 0 to n by (max 1 (floor n 100)) do
        (let ((old (aref versions size)))
          (parachute:is = size (sl:dict-size old))
          (parachute:false (nth-value 1 (sl:dict-ref old (complexity-work-key size))))
          (when (plusp size)
            (parachute:is = (1- size) (sl:dict-ref old (complexity-work-key (1- size)))))))))
  (let ((dict (sl:dict)) (set (sl:hash-set)) (old nil))
    (dotimes (i 64)
      (let ((key (complexity-work-key i 7)))
        (setf dict (sl:dict-set dict key i) set (sl:set-add key set))
        (push dict old)))
    (parachute:is = 64 (sl:dict-size dict))
    (parachute:is = 64 (sl:set-size set))
    (dotimes (i 64)
      (parachute:is = i (sl:dict-ref dict (complexity-work-key i 7)))
      (parachute:true (sl:set-member (complexity-work-key i 7) set)))
    (loop for version in (reverse old) for size from 1 do
      (parachute:is = size (sl:dict-size version))
      (parachute:is = (1- size) (sl:dict-ref version (complexity-work-key (1- size) 7))))))
