;;;; Fresh domain fixtures: no historical adapters and no Chapter 6 methods.
(in-package #:sophie-lisp.tests)

(defclass extension-cache ()
  ((values :initarg :values :reader extension-values)
   (cached :initform (make-array 0 :adjustable t :fill-pointer 0) :reader extension-cached)
   (realized :initform 0 :accessor extension-realized)
   (exhausted :initform nil :accessor extension-exhausted)))
(defclass extension-record ()
  ((cache :initarg :cache :reader extension-cache)
   (position :initarg :position :initform 0 :reader extension-position)
   (configuration :initarg :configuration :reader extension-configuration)))
(defclass extension-configured-record (extension-record) ())
(defclass extension-collectable (extension-configured-record) ())
(defclass extension-child (extension-collectable) ())
(defvar *extension-events* nil)

(defun extension-record (values &optional (class 'extension-child) (configuration :configured))
  (make-instance class :cache (make-instance 'extension-cache :values (coerce values 'vector))
                       :configuration configuration))
(defun extension-fetch (record index)
  ;; The backing data is fixed. Only missing cache positions are realized;
  ;; external fetches extend the same cache without advancing any cursor.
  (let* ((cache (extension-cache record)) (backing (extension-values cache))
         (cached (extension-cached cache)))
    (loop while (and (<= (length cached) index) (< (length cached) (length backing))) do
      (vector-push-extend (aref backing (length cached)) cached)
      (incf (extension-realized cache)))
    (if (< index (length cached)) (values (aref cached index) t)
        (progn (setf (extension-exhausted cache) t) (values nil nil)))))
(defmethod sl:seqablep ((source extension-record)) t)
(defmethod sl:seq-emptyp ((source extension-record))
  (not (nth-value 1 (extension-fetch source (extension-position source)))))
(defmethod sl:seq-first ((source extension-record)) (extension-fetch source (extension-position source)))
(defmethod sl:seq-rest ((source extension-record))
  (unless (sl:seq-emptyp source)
    (make-instance (class-of source) :cache (extension-cache source)
                   :position (1+ (extension-position source))
                   :configuration (extension-configuration source))))
(defmethod sl:seq-length ((source extension-record))
  (- (length (extension-values (extension-cache source))) (extension-position source)))

(defclass extension-builder ()
  ((finish :initarg :finish :reader extension-finish)
   (items :initform nil :accessor extension-items)
   (done :initform nil :accessor extension-done)
   (result :accessor extension-result)))
(defmethod sl:collector-accumulate ((builder extension-builder) element)
  (push element (extension-items builder)) builder)
(defmethod sl:collector-result ((builder extension-builder))
  (unless (extension-done builder)
    (setf (extension-result builder) (funcall (extension-finish builder) (reverse (extension-items builder)))
          (extension-done builder) t))
  (extension-result builder))
(defmethod sl:make-collector-for ((source extension-collectable) &key)
  (push :primary *extension-events*)
  (make-instance 'extension-builder :finish
                 (lambda (items) (extension-record items (class-of source) (extension-configuration source)))))
(defmethod sl:make-collector-for :around ((source extension-collectable) &key)
  (push :around-enter *extension-events*)
  (prog1 (call-next-method) (push :around-exit *extension-events*)))
(defmethod sl:make-collector-for :before ((source extension-collectable) &key)
  (push :before *extension-events*))
(defmethod sl:make-collector-for :after ((source extension-collectable) &key)
  (push :after *extension-events*))
(defmethod sl:make-collector-for ((target (eql (find-class 'extension-child))) &key (configuration :target))
  (make-instance 'extension-builder :finish (lambda (items) (extension-record items 'extension-child configuration))))
(defmethod sl:ref ((source extension-record) key &optional (default nil supplied))
  (if supplied (sl:seq-ref source key default) (sl:seq-ref source key)))

(defun extension-empty-user-split ()
  (let* ((*extension-events* nil) (calls 0) (configuration (list :schema))
         (source (extension-record '(1 2) 'extension-child configuration))
         (pair (sl:seq-split-with (lambda (x) (declare (ignore x)) (incf calls) nil) source)))
    (parachute:is = 0 calls)
    (parachute:is eq nil *extension-events*)
    (let ((prefix (sl:seq-first pair)))
      (parachute:is eq (class-of source) (class-of prefix))
      (parachute:is eq configuration (extension-configuration prefix))
      (parachute:is = 0 (sl:seq-length prefix))
      (parachute:is = 1 calls)
      (parachute:is = 1 (count :primary *extension-events*))
      (parachute:is eq prefix (sl:seq-first pair))
      (let ((suffix (sl:seq-first (sl:seq-rest pair))))
        (parachute:is equal '(1 2) (integration-list suffix))
        (parachute:is eq configuration (extension-configuration suffix))
        (parachute:is = 1 calls)
        (parachute:is = 2 (count :primary *extension-events*))))))

(parachute:define-test sequence.extend-custom-types-with-caching-and-collectors
 (let* ((source (extension-record '(10 20 30)))
        (a
         (sophie-lisp-extensions:seq-into 'sophie-lisp-extensions:lazy-seq
          source))
        (b
         (sophie-lisp-extensions:seq-into 'sophie-lisp-extensions:lazy-seq
          source)))
   (parachute:is = 0 (extension-realized (extension-cache source)))
   (parachute:is = 3 (sophie-lisp-extensions:seq-length source))
   (parachute:is = 0 (extension-realized (extension-cache source)))
   (parachute:is = 10 (sophie-lisp-extensions:seq-first a))
   (parachute:is = 10 (sophie-lisp-extensions:seq-first b))
   (parachute:is = 1 (extension-realized (extension-cache source)))
   (parachute:is = 20
                 (sophie-lisp-extensions:seq-first
                  (sophie-lisp-extensions:seq-rest a)))
   (parachute:is = 20
                 (sophie-lisp-extensions:seq-first
                  (sophie-lisp-extensions:seq-rest b)))
   (parachute:is = 2 (extension-realized (extension-cache source)))
   (parachute:is = 0 (extension-position source))
   (parachute:is = 3 (sophie-lisp-extensions:seq-length source))
   (parachute:is equal '(10 20 30) (integration-list a))
   (parachute:is equal '(10 20 30) (integration-list b))
   (parachute:true (extension-exhausted (extension-cache source))))
 (let* ((source (extension-record '(10 20 30)))
        (view
         (sophie-lisp-extensions:seq-into 'sophie-lisp-extensions:lazy-seq
          source)))
   (parachute:is = 10 (sophie-lisp-extensions:seq-first view))
   (parachute:is = 20 (extension-fetch source 1))
   (parachute:is = 2 (extension-realized (extension-cache source)))
   (parachute:is = 20
                 (sophie-lisp-extensions:seq-first
                  (sophie-lisp-extensions:seq-rest view)))
   (parachute:is = 3 (sophie-lisp-extensions:seq-length source))
   (parachute:is = 10 (sophie-lisp-extensions:seq-first view)))
 (let* ((*extension-events* nil)
        (configuration (list :codec :utf8))
        (source (extension-record '(1 2 3) 'extension-child configuration))
        (result (sophie-lisp-extensions:seq-map #'1+ source)))
   (parachute:is eq (class-of source) (class-of result))
   (parachute:is eq configuration (extension-configuration result))
   (parachute:false (eq source result))
   (parachute:false (eq (extension-cache source) (extension-cache result)))
   (parachute:is equal '(:around-enter :before :primary :after :around-exit)
                 (reverse *extension-events*))
   (parachute:is equal '(2 3 4) (integration-list result))
   (parachute:is equal '(1 2 3) (integration-list source))
   (parachute:is = 0 (extension-position result))
   (let ((builder (sophie-lisp-extensions:make-collector-for source)))
     (parachute:is eq builder
                   (sophie-lisp-extensions:collector-accumulate builder 99))
     (let ((first (sophie-lisp-extensions:collector-result builder)))
       (parachute:is eq first
                     (sophie-lisp-extensions:collector-result builder))
       (parachute:is equal '(99) (integration-list first)))))
 (let* ((*extension-events* nil)
        (source (extension-record '(1 2 3)))
        (pair (sophie-lisp-extensions:seq-split-at 1 source)))
   (parachute:true (sophie-lisp-extensions:lazy-seq-p pair))
   (parachute:is = 0 (extension-realized (extension-cache source)))
   (parachute:is eq nil *extension-events*)
   (let ((prefix (sophie-lisp-extensions:seq-first pair)))
     (parachute:is equal '(1) (integration-list prefix))
     (parachute:is eq (class-of source) (class-of prefix))
     (parachute:is = 1 (count :primary *extension-events*))
     (parachute:is eq prefix (sophie-lisp-extensions:seq-first pair))
     (let ((rest (sophie-lisp-extensions:seq-rest pair)))
       (parachute:is = 1 (count :primary *extension-events*))
       (let ((suffix (sophie-lisp-extensions:seq-first rest)))
         (parachute:is equal '(2 3) (integration-list suffix))
         (parachute:is eq (class-of source) (class-of suffix))
         (parachute:is = 2 (count :primary *extension-events*))
         (parachute:is eq suffix (sophie-lisp-extensions:seq-first rest))
         (parachute:true
          (sophie-lisp-extensions:seq-emptyp
           (sophie-lisp-extensions:seq-rest rest)))))))
 (extension-empty-user-split))

(defclass extension-dictionary (extension-record) ())
(defclass extension-dictionary-child (extension-dictionary) ())
(defmethod sl:dictp ((source extension-dictionary)) t)
(defmethod sl:dict-test ((source extension-dictionary)) 'eql)
(defmethod sl:dict-size ((source extension-dictionary)) (sl:seq-length source))
(defmethod sl:dict-ref ((source extension-dictionary) key &optional default)
  (let ((entry (find key (extension-values (extension-cache source)) :key #'sl:entry-key :test #'eql)))
    (if entry (values (sl:entry-value entry) t) (values default nil))))
(defmethod sl:ref ((source extension-dictionary) key &optional default)
  (sl:dict-ref source key default))
(defmethod sl:dict-collect ((source extension-dictionary) entries &key (test 'eql))
  (unless (eq test 'eql) (error 'program-error))
  (let ((alist nil))
    (dolist (entry (integration-list entries))
      (unless (typep entry 'sl:map-entry) (error 'type-error :datum entry :expected-type 'sl:map-entry))
      (setf alist (acons (sl:entry-key entry) (sl:entry-value entry)
                         (remove (sl:entry-key entry) alist :key #'car :test #'eql))))
    (extension-record (mapcar (lambda (pair) (sl:map-entry (car pair) (cdr pair))) (reverse alist))
               (class-of source) (extension-configuration source))))

(defun extension-dual-role-check ()
  ;; STANDARD-CLASS is self-instantiating and not an enumerated Sophie target.
  ;; Scoped ordinary class methods also make each returned class object seqable.
  (let* ((target (find-class 'standard-class)) (contents (make-hash-table :test #'eq))
         (methods nil) (*extension-events* nil))
    (setf (gethash target contents) '(4 5))
    (flet ((install (form) (push (eval form) methods)))
      (unwind-protect
           (progn
             (install `(defmethod sl:seqablep ((x standard-class))
                         (nth-value 1 (gethash x ',contents))))
             (install `(defmethod sl:seq-emptyp ((x standard-class))
                         (null (gethash x ',contents))))
             (install `(defmethod sl:seq-first ((x standard-class))
                         (first (gethash x ',contents))))
             (install `(defmethod sl:seq-rest ((x standard-class))
                         (rest (gethash x ',contents))))
             (let ((method
                     (make-instance (closer-mop:generic-function-method-class #'sl:make-collector-for)
                       :qualifiers nil :lambda-list '(x &key configuration)
                       :specializers (list (find-class 'standard-class))
                       :function
                       (lambda (arguments next-methods)
                         (declare (ignore next-methods))
                         (push (list :class (first arguments)) *extension-events*)
                         (make-instance 'extension-builder :finish
                           (lambda (items)
                             (let ((result (make-instance 'standard-class :name (gensym "ZI-CLASS-"))))
                               (setf (gethash result contents) items) result)))))))
               (add-method #'sl:make-collector-for method)
               (push method methods))
             (install `(defmethod sl:make-collector-for ((x (eql ,target)) &key configuration)
                         (push (list :eql x configuration) *extension-events*)
                         (call-next-method)))
             (install `(defmethod sl:make-collector-for :before ((x (eql ,target)) &key configuration)
                         (declare (ignore configuration)) (push (list :before x) *extension-events*)))
             (install `(defmethod sl:make-collector-for :after ((x (eql ,target)) &key configuration)
                         (declare (ignore configuration)) (push (list :after x) *extension-events*)))
             (let ((a (sl:seq-into '(standard-class :configuration :option) '(4 5)))
                   (b (sl:seq-map #'1+ target)))
               (parachute:is eq (class-of target) (class-of a))
               (parachute:is eq (class-of target) (class-of b))
               (parachute:is equal '(4 5) (integration-list a))
               (parachute:is equal '(5 6) (integration-list b))
               (parachute:is equal '(:before :eql :class :after :before :eql :class :after)
                             (mapcar #'first (reverse *extension-events*)))
               (parachute:true (every (lambda (event) (eq target (second event))) *extension-events*))
               (parachute:is eq :option (third (second (reverse *extension-events*))))))
        (dolist (method methods)
          (remove-method (closer-mop:method-generic-function method) method))))))

(parachute:define-test extensions.dispatch-custom-methods-and-preserve-semantics
  (let* ((source (extension-record '(2 3) 'extension-configured-record)) (calls 0) (method nil))
    (unwind-protect
         (progn
           (setf method (eval '(defmethod sl:make-collector-for :around ((x extension-configured-record) &key)
                                (push :aux-only *extension-events*) (call-next-method))))
           (let* ((*extension-events* nil)
                  (result (sl:seq-map (lambda (x) (incf calls) (1+ x)) source)))
             (parachute:true (sl:lazy-seq-p result))
             (parachute:is = 0 calls)
             (parachute:is eq nil *extension-events*)
             (parachute:is equal '(3 4) (integration-list result))
             (parachute:is = 2 calls)))
      (when method (remove-method #'sl:make-collector-for method))))
  (let* ((source (extension-record '(7 8) 'extension-configured-record)) (method nil))
    (unwind-protect
         (progn
           (setf method
                 (eval `(defmethod sl:make-collector-for ((x (eql ,source)) &key)
                          (make-instance 'extension-builder :finish
                            (lambda (items) (extension-record items (class-of x) (extension-configuration x)))))))
           (let ((result (sl:seq-map #'1+ source)))
             (parachute:true (typep result 'extension-configured-record))
             (parachute:is equal '(8 9) (integration-list result))
             (parachute:false (eq result source)))
           (remove-method #'sl:make-collector-for method)
           (setf method nil)
           (parachute:true (sl:lazy-seq-p (sl:seq-map #'1+ source))))
      (when method (remove-method #'sl:make-collector-for method))))
  (let* ((source (extension-record (list (sl:map-entry 0 10) (sl:map-entry 1 20))
                           'extension-dictionary-child :schema))
         (result (sl:dict-transform (lambda (k v) (values k (1+ v))) source)))
    (parachute:is eq (class-of source) (class-of result))
    (parachute:is eq :schema (extension-configuration result))
    (parachute:is eq 'eql (sl:dict-test result))
    (parachute:is equal '(11 t) (multiple-value-list (sl:ref result 0)))
    (parachute:is equal '(nil nil) (multiple-value-list (sl:ref result 9)))
    (parachute:is = 2 (sl:dict-size result))
    (parachute:is = 10 (sl:dict-ref source 0))
    (parachute:is equal '(10 20) (sl:bind ((#(a b) source)) (list a b)))
    (parachute:is = 30 (funcall (sl:fn (#(a b) &optional (sum (+ a b))) sum) source))
    (let* ((table (make-hash-table :test 'eq)) (outer (sl:dict :table table)))
      (setf (gethash :user table) source)
      (parachute:is = 20 (sl:dict-ref-in outer '(:table :user 1)))
      (parachute:is = 3 (sl:dict-ref-in (sl:dict-set-in outer '(:table :other) 3) '(:table :other)))
      (parachute:false (nth-value 1 (gethash :other table)))))
  (let* ((source (extension-record '(2 3))) (*package* (find-package :sophie-lisp.tests))
         (*readtable* (named-readtables:find-readtable :sl-core-syntax))
         (form (read-from-string "(sl:fn (#(a b) &optional (c (+ a b))) (declare (type integer a b c)) #v(a b c))")))
    (parachute:is equalp #(2 3 5) (funcall (eval form) source)))
  (let ((callback (gensym "ZI-CALLBACK-")))
    (unwind-protect
         (progn
           (setf (symbol-function callback) #'1+)
           (let ((result (sl:seq-map callback (sl:lazy-cons 2 nil))))
             (setf (symbol-function callback) (lambda (x) (+ x 10)))
             (parachute:is = 12 (sl:seq-first result))
             (fmakunbound callback)
             (parachute:is = 12 (sl:seq-first result)))
           (setf (symbol-function callback) #'identity)
           (let ((result (sl:seq-map callback (sl:lazy-cons 2 nil))))
             (fmakunbound callback)
             (parachute:fail (sl:seq-first result) undefined-function)))
      (when (fboundp callback) (fmakunbound callback))))
  (let ((result (sl:seq-into '(extension-child :configuration :custom) '(1 2))))
    (parachute:true (typep result 'extension-child))
    (parachute:is eq :custom (extension-configuration result))
    (parachute:is equal '(1 2) (integration-list result))
    (parachute:is = 0 (extension-position result))
    (parachute:is = 2 (sl:seq-length result)))
  ;; Manually constructed methods rely on the host's method-function calling
  ;; convention, which AMOP leaves implementation-defined: SBCL passes
  ;; (ARGUMENTS NEXT-METHODS), CCL passes an extra argument, and ECL's
  ;; machinery signals, so this characterization is SBCL-only.
  #+sbcl (extension-dual-role-check))

(defmethod sl:seq-rest ((source extension-dictionary))
  (sl:seq-into (quote sl:lazy-seq) (subseq (extension-values (extension-cache source)) (min 1 (sl:dict-size source)))))
