;;;; Independent D-CONVERSIONS acceptance tests.
;;;;
;;;; These tests cover only the explicit alist/plist conversions and the
;;;; conversion boundaries assigned to D-CONVERSIONS.  Dict-derived order is
;;;; never treated as specified; resident keys and values are checked by EQ.
(in-package #:sophie-lisp.tests)

(defun conversion-alist-entry (alist key)
  (find key alist :key #'car :test #'eq))

(defun conversion-plist-value (plist key)
  (loop for tail on plist by #'cddr
        for candidate = (car tail)
        for value = (cadr tail)
        when (eq candidate key) do (return (values value t))
        finally (return (values nil nil))))

(defun conversion-circular-list (first second)
  (let ((list (list first second)))
    (setf (cdr (cdr list)) list)
    list))

(parachute:define-test alist-dict.malformed-input
  ;; PLIST-001 retains all malformed-plist assertions. This stable case ID
  ;; tests the distinct ALIST requirement; backing plist mutation is undefined.
  (dolist (bad (list 42 (cons (cons :key :value) :tail)
                    (list :not-a-cons)
                    (conversion-circular-list (cons :a 1) (cons :b 2))))
    (let ((condition (handler-case (progn (sophie-lisp:alist-dict bad) nil)
                       (condition (caught) caught))))
      (parachute:true (typep condition 'type-error))
      (parachute:false (typep condition 'program-error)))))

(parachute:define-test alist-dict.last-wins
  (let* ((first-key (copy-seq "alist-key"))
         (last-key (copy-seq "alist-key"))
         (whole-value (list :whole :tail))
         (first-value (list :first))
         (last-value (list :last))
         (alist (list (cons first-key first-value)
                      (cons :whole whole-value)
                      (cons last-key last-value)))
         (dict (sophie-lisp:alist-dict alist)))
    (parachute:false (eq first-key last-key))
    (parachute:true (sophie-lisp:dictp dict))
    (parachute:is = 2 (sophie-lisp:dict-size dict))
    (let ((values (multiple-value-list
                   (sophie-lisp:dict-ref dict (copy-seq "alist-key")))))
      (parachute:is = 2 (length values))
      (parachute:is eq last-value (first values))
      (parachute:true (second values)))
    ;; ALIST-DICT uses the complete cdr of an association as its value.
    (let ((values (multiple-value-list
                   (sophie-lisp:dict-ref dict :whole))))
      (parachute:is eq whole-value (first values))
      (parachute:true (second values)))
    (let ((entry (conversion-alist-entry
                  (sophie-lisp:dict-alist dict) last-key)))
      (parachute:true entry)
      (parachute:is eq last-key (car entry))
      (parachute:is eq last-value (cdr entry))))
  (dolist (bad (list 42
                     (cons (cons :key :value) :tail)
                     (list :not-a-cons)))
    (parachute:fail (sophie-lisp:alist-dict bad) type-error))
  (let* ((key (gensym "ALIST-CYCLE-"))
         (value (list :value))
         (circular (conversion-circular-list (cons key value)
                                              (cons key value))))
    (parachute:fail (sophie-lisp:alist-dict circular) type-error)))

(parachute:define-test plist-dict.last-wins
  (let* ((first-key (copy-seq "plist-key"))
         (last-key (copy-seq "plist-key"))
         (first-value (list :first))
         (last-value (list :last))
         (plist (list first-key first-value last-key last-value))
         (dict (sophie-lisp:plist-dict plist)))
    (parachute:false (eq first-key last-key))
    (parachute:true (sophie-lisp:dictp dict))
    (parachute:is = 1 (sophie-lisp:dict-size dict))
    (let ((entry (sl:seq-first dict)))
      (parachute:is eq last-key (sl:entry-key entry))
      (parachute:false (eq first-key (sl:entry-key entry))))
    (let ((values (multiple-value-list
                   (sophie-lisp:dict-ref dict (copy-seq "plist-key")))))
      (parachute:is = 2 (length values))
      (parachute:is eq last-value (first values))
      (parachute:true (second values)))
    ;; The explicit conversion is last-wins, unlike the EQ first-match view.
    (let* ((key (gensym "SHARED-INDICATOR-"))
           (first (list :view-first))
           (last (list :view-last))
           (raw (list key first key last))
           (converted (sophie-lisp:plist-dict raw))
           (view (sophie-lisp:plist-dict-view raw)))
      (parachute:is = 1 (sophie-lisp:dict-size converted))
      (parachute:is = 1 (sophie-lisp:dict-size view))
      (parachute:is eq last (sophie-lisp:dict-ref converted key))
      (parachute:is eq first (sophie-lisp:dict-ref view key))))
  (parachute:fail (sophie-lisp:plist-dict (list :odd)) program-error)
  (dolist (bad (list 42
                     (cons :key (cons :value :tail))))
    (parachute:fail (sophie-lisp:plist-dict bad) type-error))
  (parachute:fail (sophie-lisp:plist-dict (cons :key (cons :value :tail)))
                  program-error)
  (let* ((key (gensym "PLIST-CYCLE-"))
         (value (list :value))
         (circular (conversion-circular-list key value)))
    (parachute:fail (sophie-lisp:plist-dict circular) type-error)
    (parachute:fail (sophie-lisp:plist-dict circular) program-error)))

(parachute:define-test dict-convert.fresh-exports
  (let* ((key-a (gensym "DICT-ALIST-A-"))
         (key-b (gensym "DICT-ALIST-B-"))
         (value-a (list :value-a))
         (value-b (list :value-b))
         (dict (sophie-lisp:dict key-a value-a key-b value-b))
         (alist-one (sophie-lisp:dict-alist dict))
         (alist-two (sophie-lisp:dict-alist dict)))
    (parachute:true (listp alist-one))
    (parachute:false (eq alist-one alist-two))
    (let ((entry-one (conversion-alist-entry alist-one key-a))
          (entry-two (conversion-alist-entry alist-two key-a)))
      (parachute:true entry-one)
      (parachute:true entry-two)
      (parachute:false (eq entry-one entry-two))
      (parachute:is eq key-a (car entry-one))
      (parachute:is eq value-a (cdr entry-one)))
    (let ((entry (conversion-alist-entry alist-one key-b)))
      (parachute:true entry)
      (parachute:is eq key-b (car entry))
      (parachute:is eq value-b (cdr entry))))
  (let* ((key-a (gensym "DICT-PLIST-A-"))
         (key-b (gensym "DICT-PLIST-B-"))
         (value-a (list :value-a))
         (value-b (list :value-b))
         (dict (sophie-lisp:dict key-a value-a key-b value-b))
         (plist-one (sophie-lisp:dict-plist dict))
         (plist-two (sophie-lisp:dict-plist dict)))
    (parachute:true (listp plist-one))
    (parachute:false (eq plist-one plist-two))
    (parachute:false (eq (cdr plist-one) (cdr plist-two)))
    (multiple-value-bind (found-a present-a)
        (conversion-plist-value plist-one key-a)
      (parachute:true present-a)
      (parachute:is eq value-a found-a))
    (multiple-value-bind (found-b present-b)
        (conversion-plist-value plist-one key-b)
      (parachute:true present-b)
      (parachute:is eq value-b found-b))
    ;; A second call is an independently materialized proper plist.
    (parachute:true (null (cddr (last plist-one))))))

(defun d-group-ref-values (dict key &optional (default nil default-supplied-p))
  (if default-supplied-p
      (multiple-value-list (sl:dict-ref dict key default))
      (multiple-value-list (sl:dict-ref dict key))))

(parachute:define-test dict-frequencies.counts-equal-values
  (let* ((first (copy-seq "same"))
         (alias (copy-seq "same"))
         (source (vector 1 1.0 first alias nil nil :other))
         (result (sl:dict-frequencies source)))
    (parachute:true (typep result 'sl:dict))
    (parachute:true (sl:dictp result))
    ;; DICT-FREQUENCIES uses EQUALS, so mathematical and string aliases coalesce.
    (parachute:is = 4 (sl:dict-size result))
    (let ((values (d-group-ref-values result 1)))
      (parachute:is = 2 (length values))
      (parachute:is = 2 (first values))
      (parachute:true (second values)))
    (let ((values (d-group-ref-values result first)))
      (parachute:is = 2 (first values))
      (parachute:true (second values)))
    (let ((values (d-group-ref-values result nil)))
      (parachute:is = 2 (first values))
      (parachute:true (second values)))
    (let ((values (d-group-ref-values result :other)))
      (parachute:is = 1 (first values))
      (parachute:true (second values)))
    (parachute:fail (sl:dict-frequencies 42) type-error)))

(parachute:define-test dict-group-by.groups-and-callback
  (let* ((a1 (copy-seq "a-one"))
         (b1 (copy-seq "b-one"))
         (a2 (copy-seq "a-two"))
         (b2 (copy-seq "b-two"))
         (source (list a1 b1 a2 b2))
         (calls nil)
         (result
           (sl:dict-group-by
            (lambda (item)
              (push item calls)
              (values (if (char= (char item 0) #\a) :a :b)
                      :ignored-secondary-value))
            source)))
    (parachute:true (typep result 'sl:dict))
    (parachute:is = 2 (sl:dict-size result))
    ;; The callback is called once per element, in retained traversal order.
    (parachute:is = (length source) (length calls))
    (parachute:true (every #'eq source (reverse calls)))
    (let ((values (d-group-ref-values result :a)))
      (parachute:is = 2 (length values))
      (parachute:true (second values))
      (let ((group (first values)))
        (parachute:false (eq source group))
        (parachute:is = 2 (length group))
        (parachute:is eq a1 (first group))
        (parachute:is eq a2 (second group))))
    (let ((values (d-group-ref-values result :b)))
      (parachute:is = 2 (length values))
      (parachute:true (second values))
      (let ((group (first values)))
        (parachute:false (eq source group))
        (parachute:is = 2 (length group))
        (parachute:is eq b1 (first group))
        (parachute:is eq b2 (second group))))
    ;; A detectable callback error is reported before any callback invocation.
    (parachute:fail (sl:dict-group-by 42 source) type-error)
    (parachute:fail (sl:dict-group-by #'identity 42) type-error)
    ;; Symbol designators must be functions, not macros or unbound symbols.
    (parachute:fail (sl:dict-group-by 'when source) type-error)
    (parachute:fail (sl:dict-count-by 'when source) type-error)
    (let ((unbound (gensym "UNDEFINED-")))
      (parachute:fail (sl:dict-group-by unbound source) type-error)
      (parachute:fail (sl:dict-count-by unbound source) type-error))))

(parachute:define-test dict-zipmap.lockstep-laziness
  ;; Keys are forced before values at each lockstep position, and an observed
  ;; key end prevents a later value tail from being forced.
  (let* ((events nil)
         (key-tail-forces 0)
         (value-tail-forces 0)
         (keys (sl:lazy-seq
                 (progn
                   (push :key-head events)
                   (sl:lazy-cons
                    :key
                    (sl:lazy-seq
                      (progn
                        (incf key-tail-forces)
                        (push :key-end events)
                        nil))))))
         (vals (sl:lazy-seq
                 (progn
                   (push :value-head events)
                   (sl:lazy-cons
                    :value
                    (sl:lazy-seq
                      (progn
                        (incf value-tail-forces)
                        (push :value-tail events)
                        nil))))))
         (result (sl:dict-zipmap keys vals)))
    (parachute:true (typep result 'sl:dict))
    (parachute:is = 1 (sl:dict-size result))
    (let ((values (d-group-ref-values result :key)))
      (parachute:is eq :value (first values))
      (parachute:true (second values)))
    (parachute:is equal '(:key-head :value-head :key-end) (reverse events))
    (parachute:is = 1 key-tail-forces)
    (parachute:is = 0 value-tail-forces))
  ;; When values end after the first pair, the extra key is observed to decide
  ;; which input is shorter, but its own tail is not forced.
  (let* ((events nil)
         (key-tail-forces 0)
         (value-tail-forces 0)
         (keys (sl:lazy-seq
                 (progn
                   (push :key-head events)
                   (sl:lazy-cons
                    :key
                    (sl:lazy-seq
                      (progn
                        (push :key-extra events)
                        (sl:lazy-cons
                         :extra-key
                         (sl:lazy-seq
                           (progn
                             (incf key-tail-forces)
                             (push :key-tail events)
                             nil)))))))))
         (vals (sl:lazy-seq
                 (progn
                   (push :value-head events)
                   (sl:lazy-cons
                    :value
                    (sl:lazy-seq
                      (progn
                        (incf value-tail-forces)
                        (push :value-tail events)
                        nil))))))
         (result (sl:dict-zipmap keys vals)))
    (parachute:true (typep result 'sl:dict))
    (parachute:is = 1 (sl:dict-size result))
    (let ((values (d-group-ref-values result :key)))
      (parachute:is eq :value (first values))
      (parachute:true (second values)))
    (parachute:is equal '(:key-head :value-head :key-extra :value-tail)
                  (reverse events))
    (parachute:is = 0 key-tail-forces)
    (parachute:is = 1 value-tail-forces))
  ;; Both operands are validated as seqables, and a pair is never installed
  ;; when one of the sources is invalid.
  (parachute:fail (sl:dict-zipmap 42 nil) type-error)
  (parachute:fail (sl:dict-zipmap nil 42) type-error)
  (let* ((first-key (copy-seq "same"))
         (last-key (copy-seq "same"))
         (result (sl:dict-zipmap (list first-key last-key) '(1 2))))
    (parachute:false (eq first-key last-key))
    (parachute:true (sl:equals first-key last-key))
    (parachute:is = 1 (sl:dict-size result))
    (parachute:is = 2 (sl:dict-ref result last-key))
    (let ((resident-key (sl:entry-key (sl:seq-first result))))
      (parachute:is eq last-key resident-key)
      (parachute:false (eq first-key resident-key))
      (parachute:is = 2 (sl:dict-ref result resident-key)))))

(parachute:define-test dict-count-by.counts-classifications
  (let ((result (sl:dict-count-by #'evenp '(1 2 3 4 5 6))))
    (parachute:true (typep result 'sl:dict))
    (parachute:is = 2 (sl:dict-size result))
    (parachute:is = 3 (sl:dict-ref result t))
    (parachute:is = 3 (sl:dict-ref result nil)))
  (let ((result (sl:dict-count-by #'identity '(nil nil t))))
    (parachute:is = 2 (sl:dict-ref result nil))
    (parachute:is = 1 (sl:dict-ref result t)))
  (let ((result (sl:dict-count-by #'identity #(:a :b :a))))
    (parachute:is = 2 (sl:dict-size result))
    (parachute:is = 2 (sl:dict-ref result :a)))
  (let ((result (sl:dict-count-by (lambda (x) (mod x 2)) '(1 3 2 4))))
    (parachute:is = 2 (sl:dict-ref result 1))
    (parachute:is = 2 (sl:dict-ref result 0)))
  (let* ((first-key (copy-seq "k"))
         (last-key (copy-seq "k"))
         (result (sl:dict-count-by #'identity (list first-key last-key))))
    (parachute:false (eq first-key last-key))
    (parachute:is eq last-key (sl:entry-key (sl:seq-first result)))
    (parachute:is = 2 (sl:dict-ref result first-key))
    (parachute:is = 2 (sl:dict-ref result last-key)))
  (let ((result (sl:dict-count-by #'identity nil)))
    (parachute:true (sl:dictp result))
    (parachute:is = 0 (sl:dict-size result))))

(parachute:define-test dict-reduce-kv.accumulates-entries
  (parachute:is = 6
    (sl:dict-reduce-kv (lambda (acc k v) (declare (ignore k)) (+ acc v))
                       0 (sl:dict :a 1 :b 2 :c 3)))
  (parachute:is = 0 (sl:dict-reduce-kv #'+ 0 (sl:dict)))
  (parachute:is = 2
    (sl:dict-reduce-kv (lambda (acc k v) (declare (ignore k)) (and acc v))
                       t (sl:ordered-dict :a 1 :b 2)))
  (let ((table (make-hash-table)))
    (setf (gethash :a table) 4
          (gethash :b table) 5)
    (parachute:is = 9
      (sl:dict-reduce-kv (lambda (acc k v) (declare (ignore k)) (+ acc v))
                         0 table)))
  (parachute:is = 10
    (sl:dict-reduce-kv (lambda (acc k v) (declare (ignore k)) (+ acc v))
                       0 (sl:ordered-dict :a 4 :b 6))))

(parachute:define-test dict-projections.lazy-projection
  ;; Projection results preserve lazy forcing and validate map entries.
  (dolist (projection (list #'sl:dict-keys #'sl:dict-vals))
    (let* ((calls 0) (tail-calls 0)
           (entry (sl:map-entry (list :key) (list :value)))
           (tail (sl:lazy-seq (progn (incf tail-calls) (error "Unrequested tail"))))
           (source (sl:lazy-seq
                     (progn (incf calls) (sl:lazy-cons entry tail))))
           (result (funcall projection source))
           (expected (if (eq projection #'sl:dict-keys)
                         (sl:entry-key entry) (sl:entry-value entry))))
      (parachute:true (sl:lazy-seq-p result))
      (parachute:is = 0 calls)
      (parachute:is = 0 tail-calls)
      (parachute:is eq expected (sl:seq-first result))
      (cseq-ref-values result 0 :unused expected t)
      (parachute:is = 1 calls)
      (parachute:is = 0 tail-calls))
    (let* ((calls 0)
           (bad (sl:lazy-seq (progn (incf calls) (sl:lazy-cons '(:a . :b) nil))))
           (result (funcall projection bad)))
      (parachute:is = 0 calls)
      (parachute:fail (sl:seq-first result) type-error)
      (parachute:is = 1 calls))
    (parachute:fail (funcall projection 42) type-error)
    (let* ((source (sl:dict :a nil :b :value))
           (result (funcall projection source))
           (items (cseq-drain result 2)))
      (parachute:is = 2 (length items))
      (parachute:true (every #'eq items (cseq-drain result 2)))
      (parachute:true (null (set-exclusive-or
                            items (if (eq projection #'sl:dict-keys)
                                      '(:a :b) '(nil :value)) :test #'eq))))))

(defclass projection-source ()
  ((items :initarg :items :reader projection-items)
   (observations :initarg :observations :reader projection-observations)))

(defmethod sl:seqablep ((source projection-source)) t)
(defmethod sl:seq-emptyp ((source projection-source))
  (incf (car (projection-observations source)))
  (null (projection-items source)))
(defmethod sl:seq-first ((source projection-source))
  (incf (car (projection-observations source)))
  (car (projection-items source)))
(defmethod sl:seq-rest ((source projection-source))
  (incf (car (projection-observations source)))
  (cdr (projection-items source)))
(defmethod sl:seq-length ((source projection-source))
  (length (projection-items source)))

(defun projection-drain (view bound)
  (let ((items nil))
    (dotimes (i (1+ bound))
      (declare (ignorable i))
      (when (sl:seq-emptyp view)
        (return-from projection-drain (nreverse items)))
      (push (sl:seq-first view) items)
      (setf view (sl:seq-rest view)))
    (parachute:true nil "PROJECTION-DRAIN exceeded its independent finite bound of ~D" bound)
    (nreverse items)))

(parachute:define-test dict-projections.lazy-validation
  (dolist (project (list #'sl:dict-keys #'sl:dict-vals))
    (dolist (bad (list 42 #'identity (sl:map-entry :k :v)))
      (parachute:fail (funcall project bad) type-error))
    (let* ((key (list :key)) (value (list :value))
           (entry (sl:map-entry key value))
           (expected (if (eq project #'sl:dict-keys) key value))
           (observations (list 0))
           (source (make-instance 'projection-source :items (list entry)
                                  :observations observations))
           (view (funcall project source)))
      (parachute:false (sl:dictp source))
      (parachute:true (sl:lazy-seq-p view))
      (parachute:is = 0 (car observations))
      (parachute:is eq expected (sl:seq-first view))
      (let ((count (car observations)))
        (parachute:is eq expected (sl:seq-first view))
        (parachute:is = count (car observations)))
      (parachute:is equal (list expected) (projection-drain view 1)))
    (let* ((head-calls 0) (bad-calls 0) (tail-calls 0)
           (entry (sl:map-entry nil nil))
           (tail (sl:lazy-seq (progn (incf tail-calls)
                                           (error "Past malformed entry"))))
           (bad (sl:lazy-seq (progn (incf bad-calls)
                                          (sl:lazy-cons :not-an-entry tail))))
           (source (sl:lazy-seq (progn (incf head-calls)
                                             (sl:lazy-cons entry bad))))
           (view (funcall project source)))
      (parachute:true (sl:lazy-seq-p view))
      (parachute:is = 0 head-calls)
      (parachute:is = 0 bad-calls)
      (parachute:false (sl:seq-emptyp view))
      (parachute:is eq nil (sl:seq-first view))
      (parachute:is = 1 head-calls)
      (parachute:is = 0 bad-calls)
      (let ((rest (sl:seq-rest view)))
        (parachute:is = 0 bad-calls)
        (parachute:fail (sl:seq-first rest) type-error))
      (parachute:is = 1 bad-calls)
      (parachute:is = 0 tail-calls))
    ;; Ordinary lists/vectors are accepted, not shape-sniffed into dicts.
    (dolist (source (list nil #() (list (sl:map-entry :a :b))
                         (vector (sl:map-entry :a :b))))
      (let ((view (funcall project source)))
        (parachute:true (sl:lazy-seq-p view))
        (parachute:is = (length source) (length (projection-drain view 1)))))
    (let ((view (funcall project (list (cons :key :value)))))
      (parachute:true (sl:lazy-seq-p view))
      (parachute:fail (sl:seq-first view) type-error))
    (let* ((tag (gensym "PROJECTION-ESCAPE-"))
           (view (funcall project (sl:lazy-seq (throw tag :escaped)))))
      (parachute:is eq :escaped (catch tag (sl:seq-first view) :returned)))))

(parachute:define-test dict-projections.canonical-membership
  ;; PLIST-003 projection clause: EQ-distinct EQUAL keys retain multiplicity,
  ;; but later raw occurrences are hidden in both projections.
  (let* ((a (copy-seq "same")) (b (copy-seq "same"))
         (source (sl:plist-dict-view (list a :first b :second a :hidden)))
         (keys (projection-drain (sl:dict-keys source) 2))
         (vals (projection-drain (sl:dict-vals source) 2)))
    (parachute:is = 2 (length keys))
    (parachute:is = 2 (length vals))
    (parachute:is = 1 (count a keys :test #'eq))
    (parachute:is = 1 (count b keys :test #'eq))
    (parachute:is = 1 (count :first vals :test #'eq))
    (parachute:is = 1 (count :second vals :test #'eq)))
  (let* ((key (copy-seq "resident")) (value (list :resident))
         (pairs (list (cons key value) (cons :nil nil)))
         (table (make-hash-table :test 'eq)))
    (setf (gethash key table) value (gethash :nil table) nil)
    (dolist (source (list (sl:dict key value :nil nil) table
                         (sl:plist-dict-view (list key value :nil nil key :hidden))))
      ;; Open a fresh public lazy view without relying on internal traversal.
      (let* ((entries (sl:seq-into 'sl:lazy-seq source))
             (keys (sl:dict-keys entries))
             (vals (sl:dict-vals entries))
             (observed (projection-drain entries 2))
             (observed-keys (projection-drain keys 2))
             (observed-vals (projection-drain vals 2)))
        (parachute:true (sl:lazy-seq-p entries))
        (parachute:true (sl:lazy-seq-p keys))
        (parachute:true (sl:lazy-seq-p vals))
        (parachute:is = (sl:dict-size source) (length observed))
        (parachute:is = 2 (length observed-keys))
        (parachute:is = 2 (length observed-vals))
        (loop for entry in observed for k in observed-keys for v in observed-vals do
          (parachute:is eq (sl:entry-key entry) k)
          (parachute:is eq (sl:entry-value entry) v)
          (let ((pair (assoc k pairs :test #'eq)))
            (parachute:true pair)
            (parachute:is eq (cdr pair) v)))
        (parachute:true (every #'eq observed (projection-drain entries 2)))
        (parachute:true (every #'eq observed-keys (projection-drain keys 2)))
        (parachute:true (every #'eq observed-vals (projection-drain vals 2))))
      ;; Independent direct projections promise membership, not shared order.
      (let ((keys (projection-drain (sl:dict-keys source) 2))
            (vals (projection-drain (sl:dict-vals source) 2)))
        (parachute:is = 2 (length keys))
        (parachute:is = 2 (length vals))
        (dolist (pair pairs)
          (parachute:is = 1 (count (car pair) keys :test #'eq))
          (parachute:is = 1 (count (cdr pair) vals :test #'eq)))))
    (dolist (source (list (sl:dict) (make-hash-table)
                         (sl:plist-dict-view nil)))
      (dolist (project (list #'sl:dict-keys #'sl:dict-vals))
        (let ((view (funcall project source)))
          (parachute:true (sl:lazy-seq-p view))
          (parachute:is = 0 (sl:dict-size source))
          (parachute:true (sl:seq-emptyp view)))))))
