;;;; Public-contract acceptance; no private pattern compiler is an oracle.
(in-package #:sophie-lisp.tests)

(defun xbind-check (expected form)
  ;; On SBCL, explicitly exercise its interpreter and compiler.
  (dolist (mode '(:interpret :compile))
    (let ((function
            (if (eq mode :interpret)
                (let* (#+sbcl (sb-ext:*evaluator-mode* :interpret))
                  (eval `(lambda () ,form)))
                (multiple-value-bind (function warnings failure)
                    (compile nil `(lambda () ,form))
                  (declare (ignore warnings))
                  (when failure (error "X-BIND fixture failed compilation: ~S" form))
                  function))))
      (parachute:is equalp expected (multiple-value-list (funcall function))))))

(defun xbind-syntax-error (form)
  (parachute:fail (macroexpand-1 form) program-error))

(defvar *xbind-global* :outer)
(defvar *xbind-events* nil)
(defconstant +xbind-constant+ 19)
(define-condition xbind-sentinel (error) ())
(defclass xbind-object ()
  ((xbind-slot :initform 17) (xbind-unbound)))
(defclass xbind-access () ())
(defmethod sl:ref ((object xbind-access) key &optional (default nil supplied))
  (declare (ignore object))
  (push (list key supplied) *xbind-events*)
  (cond ((eq key :stop) (error 'xbind-sentinel))
        ((eq key :missing) (values default nil))
        ((eq key :nil) (values nil t))
        (t (values key t))))

(parachute:define-test bind.evaluation-order-and-empty-clauses
  (xbind-check '((2 5 7 (:a :b :c)))
    '(let ((events nil))
       (sl:bind ((a (progn (push :a events) 2))
                 (b (progn (push :b events) (+ a 3)))
                 (a (progn (push :c events) (+ a b))))
         (list 2 b a (reverse events)))))
  (xbind-check '(nil) '(sl:bind ()))
  (xbind-check '(:last :extra)
    '(sl:bind () :discarded (values :last :extra))))

(parachute:define-test bind.ignore-patterns
  (xbind-check '((3 :outer))
    '(let ((n 0) (_ :outer))
       (sl:bind ((_ (incf n)) (_ (incf n)) (#(_) (vector (incf n))))
         (list n _))))
  (xbind-check '(((:key nil)))
    '(let ((*xbind-events* nil))
       (sl:bind (((_ (_ :key)) sl:? (make-instance 'xbind-access)))
         (reverse *xbind-events*))))
  (xbind-check '(t)
    '(handler-case
         (sl:bind ((((_ :stop)) sl:? (make-instance 'xbind-access))) nil)
       (xbind-sentinel () t)))
  (xbind-check '(1)
    '(let ((n 0)) (sl:bind ((() sl:? (incf n)))) n)))

(parachute:define-test bind.multiple-values
  (xbind-check '(1 nil nil :extra)
    '(sl:bind ((a b c (values 1))) (values a b c :extra)))
  (xbind-check '(nil nil)
    '(sl:bind ((a b (values))) (values a b)))
  (xbind-check '(1 3 4)
    '(sl:bind ((a _ b (values 1 2 3 99)) (c (+ a b))) (values a b c)))
  (xbind-check '() '(sl:bind ((x 1)) (declare (ignore x)) (values))))

(parachute:define-test bind.keyed-patterns
  (xbind-check '((xbind-key (:literal key) nil nil 1
                  ((xbind-key nil) ((:literal key) nil) (:nil nil) (:missing nil))))
    '(let ((*xbind-events* nil) (n 0) (key :must-not-evaluate))
       (declare (ignorable key))
       (sl:bind (((xbind-key (a (:literal key)) (b :nil) (c :missing)) sl:?
                  (progn (incf n) (make-instance 'xbind-access))))
         (list xbind-key a b c n (reverse *xbind-events*)))))
  ;; A keyed NIL is not mistaken for a missing primary-value binding.
  (xbind-check '(nil 2)
    '(let ((table (make-hash-table)))
       (setf (gethash :a table) nil (gethash :b table) 2)
       (sl:bind ((((a :a) (b :b)) sl:? table)) (values a b)))))

(parachute:define-test bind.slot-patterns
  (xbind-check '((17 17 1))
    '(let ((n 0) (xbind-slot :not-a-slot))
       (declare (ignorable xbind-slot))
       (sl:bind (((xbind-slot (alias xbind-slot)) sl:@
                  (progn (incf n) (make-instance 'xbind-object))))
         (list xbind-slot alias n))))
  (xbind-check '(t)
    '(handler-case
         (sl:bind ((((x xbind-unbound)) sl:@ (make-instance 'xbind-object))) x)
       (unbound-slot () t)))
  (xbind-check '(t)
    '(handler-case
         (sl:bind ((((_ xbind-unbound)) sl:@ (make-instance 'xbind-object))) nil)
       (unbound-slot () t)))
  (xbind-check '(1)
    '(let ((n 0)) (sl:bind ((() sl:@ (incf n)))) n)))

(parachute:define-test bind.syntax-validation
  (dolist (operator '(sl:bind sl:if-bind sl:when-bind))
    (dolist (clauses '(((x)) ((x 1 2 . 3)) ((42 x 1)) ((:bad 1))
                      ((t 1)) ((+xbind-constant+ 1)) ((sl:? 1))
                      (((x) sl:?)) (((x) sl:? 1 2))
                      (((x . y) sl:? 1)) ((((x a b)) sl:@ 1))
                      (((nil) sl:? 1)) ((((:bad :key)) sl:? 1))
                      ((#(42) 1)) (((:entry x) 1))))
      (xbind-syntax-error `(,operator ,clauses nil)))
    (dolist (name '("?" "@"))
      ;; Fresh NON-keyword impostor: marker recognition is by name, then identity.
      (xbind-syntax-error
       `(,operator (((x) ,(make-symbol name) 1)) nil))))
  (xbind-check '(:ordinary :nested)
    '(let ((sl:? :ordinary) (sl:@ :nested))
       (sl:bind ((x (identity sl:?)) (y (identity sl:@))) (values x y)))))

(parachute:define-test bind.declarations-and-special-bindings
  (xbind-check '((10 20 20))
    '(flet ((xbind-read () (declare (special xbind-local)) xbind-local))
       (sl:bind ((xbind-local 10) (first (xbind-read))
                 (#(xbind-local) #(20)) (second (xbind-read)))
         (declare (special xbind-local) (type integer xbind-local)
                  (ignorable first second) (optimize (safety 3)))
         (list first second (xbind-read)))))
  (xbind-check '((7 7 7))
    '(flet ((xbind-read () (declare (special xbind-local)) xbind-local))
       (sl:bind (((#(xbind-local) &optional (later (xbind-read))
                   &aux (last (xbind-read))) '(#(7))))
         (declare (special xbind-local))
         (list xbind-local later last))))
  (xbind-check '((:lexical :lexical :dynamic))
    '(progv '(xbind-free) '(:dynamic)
       (let ((xbind-free :lexical))
         (sl:bind ((a xbind-free) ((&optional (b xbind-free)) nil))
           (declare (special xbind-free) (optimize (safety 3)))
           (list a b xbind-free)))))
  (xbind-check '((11 11))
    '(flet ((xbind-read () (declare (special xbind-local)) xbind-local))
       (sl:when-bind ((xbind-local 11) (a (xbind-read)))
         (declare (special xbind-local)) (list a (xbind-read)))))
  (xbind-check '((:lexical :dynamic))
    '(progv '(xbind-free) '(:dynamic)
       (let ((xbind-free :lexical))
         (sl:when-bind (a xbind-free)
           (declare (special xbind-free)) (list a xbind-free)))))
  (xbind-check '((:inner :outer))
    '(let ((*xbind-global* :outer))
       (list (sl:bind ((*xbind-global* :inner))
               (symbol-value '*xbind-global*)) *xbind-global*))))

(parachute:define-test if-bind-and-when-bind.patterns
  (xbind-check '(1 2 nil)
    '(sl:if-bind ((a b c (values 1 2))) (values a b c) :bad))
  (xbind-check '(1 2 nil)
    '(sl:when-bind ((a b c (values 1 2))) (values a b c)))
  (xbind-check '((:else 1))
    '(let ((n 0))
       (list (sl:if-bind ((#(a) (progn (incf n) nil))
                          (b (error "late expression")))
               (list a b) :else) n)))
  (xbind-check '(nil)
    '(sl:when-bind (((:entry a b) nil)) (list a b)))
  (xbind-check '(:yes :extra) '(sl:if-bind () (values :yes :extra) :bad))
  (xbind-check '(:yes :extra) '(sl:when-bind () (values :yes :extra)))
  (xbind-check '(nil) '(sl:when-bind ()))
  (xbind-check '((nil nil ((:nil nil) (:missing nil))))
    '(let ((*xbind-events* nil))
       (sl:if-bind ((((a :nil) (b :missing)) sl:? (make-instance 'xbind-access)))
           (list a b (reverse *xbind-events*)) :bad)))
  (xbind-check '(5)
    '(sl:when-bind ((a 2) (b (+ a 3))) b))
  (xbind-check '(17)
    '(sl:when-bind ((((a xbind-slot)) sl:@ (make-instance 'xbind-object))) a))
  (xbind-check '(:no-access)
    '(sl:if-bind ((((a xbind-unbound)) sl:@ nil)) a :no-access))
  (xbind-check '(:false)
    '(sl:if-bind ((a b (values nil :true-secondary))) (list a b) :false)))

(parachute:define-test if-bind-and-when-bind.failure
  (xbind-check '(:lexical :dynamic :extra)
    '(let ((a :lexical) (*xbind-global* :dynamic))
       (sl:if-bind ((a :new) (*xbind-global* :inner) (bad nil))
           (list a bad) (values a *xbind-global* :extra))))
  (xbind-check '(nil :outer)
    '(let ((*xbind-global* :outer))
       (values (sl:when-bind ((*xbind-global* :inner) (bad nil)) bad)
               *xbind-global*)))
  (xbind-check '(nil) '(sl:if-bind (a nil) a))
  (xbind-check '(nil) '(sl:when-bind (a 1) (declare (ignore a)))))

(parachute:define-test if-bind-and-when-bind.simple-clauses
  (xbind-check '(7) '(sl:if-bind (a 7) a :bad))
  (xbind-check '(7) '(sl:when-bind (a 7) a))
  (xbind-check '(3) '(sl:if-bind ((a 1) (b 2)) (+ a b) :bad))
  (xbind-check '(3) '(sl:if-bind (((a b) '(1 2))) (+ a b) :bad))
  (xbind-check '(:false) '(sl:if-bind (nil nil) :true :false))
  (xbind-syntax-error '(sl:if-bind () :then :else :extra))
  (xbind-syntax-error '(sl:if-bind ()))
  (xbind-syntax-error '(sl:when-bind (a 1 2) a)))

(define-condition xdoseq-sentinel (error) ())
(defvar *xdoseq-events* nil)
(defclass xdoseq-source ()
  ((items :initarg :items :reader xdoseq-items)))
(defmethod sl:seqablep ((source xdoseq-source)) t)
(defmethod sl:seq-emptyp ((source xdoseq-source)) (null (xdoseq-items source)))
(defmethod sl:seq-first ((source xdoseq-source)) (first (xdoseq-items source)))
(defmethod sl:seq-rest ((source xdoseq-source)) (rest (xdoseq-items source)))
(defclass xdoseq-access ()
  ((name :initarg :name :reader xdoseq-name)))
(defmethod sl:ref ((object xdoseq-access) key &optional (default nil supplied))
  (push (list (xdoseq-name object) key supplied) *xdoseq-events*)
  (if (eql key 0) (values (xdoseq-name object) t) (values default nil)))

(parachute:define-test doseq.basic-iteration
  (xbind-check '(nil 1 (1 nil 3))
    '(let ((n 0) (seen nil))
       (values (sl:doseq (x (progn (incf n) '(1 nil 3))) (push x seen))
               n (reverse seen))))
  (xbind-check '(nil 1)
    '(let ((n 0))
       (values (sl:doseq (x (progn (incf n) nil)) (error "empty body ran")) n)))
  (xbind-check '(nil) '(sl:doseq (_ '(1 2 3)))))

(parachute:define-test doseq.sequence-types
  (dolist (source '((quote (1 nil 3)) #(1 nil 3)
                    (make-array 5 :initial-contents '(1 nil 3 9 9) :fill-pointer 3)
                    (sl:lazy-cons 1 (sl:lazy-cons nil (sl:lazy-cons 3 nil)))
                    (make-instance 'xdoseq-source :items '(1 nil 3))))
    (xbind-check '((1 nil 3))
      `(let ((seen nil)) (sl:doseq (x ,source) (push x seen)) (reverse seen))))
  (xbind-check '((#\a #\b))
    '(let ((seen nil))
       (sl:doseq (x (make-array 4 :element-type 'character
                                :initial-contents "abcd" :fill-pointer 2))
         (push x seen)) (reverse seen))))

(parachute:define-test doseq.unordered-collections
  ;; Compare membership and multiplicity, never the order of independent views.
  (dolist (source '((let ((table (make-hash-table)))
                     (dotimes (i 64) (setf (gethash i table) (* i i))) table)
                    (let ((dict (sl:dict)))
                      (dotimes (i 64 dict) (setf dict (sl:dict-set dict i (* i i)))))))
    (xbind-check '(t)
      `(let ((seen nil))
         (sl:doseq ((:entry key value) ,source) (push (cons key value) seen))
         (equal (sort seen #'< :key #'car)
                (loop for i below 64 collect (cons i (* i i)))))))
  (xbind-check '(t)
    '(let ((source (apply #'sl:hash-set (loop for i below 64 collect i)))
           (seen nil))
       (sl:doseq (x source) (push x seen))
       (equal (sort seen #'<) (loop for i below 64 collect i)))))

(parachute:define-test doseq.patterns-and-index
  (xbind-check '(((a 0) (b 1) (c 2)))
    '(let ((seen nil))
       (sl:doseq ((x index) '(a b c)) (push (list x index) seen)) (reverse seen)))
  (xbind-check '(((1 2) (3 4)))
    '(let ((seen nil))
       (sl:doseq ((a . tail) '((1 2) (3 4))) (push (cons a tail) seen))
       (reverse seen)))
  (xbind-check '(((1 2 3)))
    '(let ((seen nil))
       (sl:doseq ((a b c) '((1 2 3))) (push (list a b c) seen)) seen))
  (xbind-check '(((1 2)))
    '(let ((seen nil))
       (sl:doseq ((a (b)) '((1 (2)))) (push (list a b) seen)) seen))
  (xbind-check '(((1 2 0) (3 4 1)))
    '(let ((seen nil))
       (sl:doseq (((a b) index) '((1 2) (3 4))) (push (list a b index) seen))
       (reverse seen))))

(parachute:define-test doseq.entry-patterns
  (xbind-check '((:key nil))
    '(let ((seen nil))
       (sl:doseq (entry (list (sl:map-entry :key nil)))
         (push (sl:entry-value entry) seen) (push (sl:entry-key entry) seen)) seen))
  (xbind-check '((:key :value ((:key 0 nil) (:value 0 nil))))
    '(let ((*xdoseq-events* nil))
       (sl:doseq ((:entry #(key) #(value))
                   (list (sl:map-entry
                           (make-instance 'xdoseq-access :name :key)
                           (make-instance 'xdoseq-access :name :value))))
         (return (list key value (reverse *xdoseq-events*))))))
  (xbind-check '(((:a . 1) (:b . 2)))
    '(let ((seen nil))
       (sl:doseq ((key . value) '((:a . 1) (:b . 2))) (push (cons key value) seen))
       (reverse seen)))
  (xbind-check '(t)
    '(handler-case
         (sl:doseq ((key . value) (list (sl:map-entry :a 1))) (list key value))
       (error () t))))

(parachute:define-test doseq.declarations-and-special-bindings
  (xbind-check '(((7 7 0) (8 8 1)))
    '(flet ((xdoseq-read () (declare (special xdoseq-local xdoseq-index))
               (list xdoseq-local xdoseq-index)))
       (let ((seen nil))
         (sl:doseq (((#(xdoseq-local) &optional (later (symbol-value 'xdoseq-local)))
                      xdoseq-index) '( (#(7)) (#(8))))
           (declare (special xdoseq-local xdoseq-index)
                    (type integer xdoseq-local xdoseq-index) (ignorable later))
           (push (list later (first (xdoseq-read)) (second (xdoseq-read))) seen))
         (reverse seen))))
  (xbind-check '((:lexical ((:lexical :dynamic))))
    '(progv '(xdoseq-free) '(:dynamic)
       (let ((xdoseq-free :lexical) (source-value nil) (seen nil))
         (sl:doseq ((&optional (a xdoseq-free))
                     (progn (setf source-value xdoseq-free) '(nil)))
           (declare (special xdoseq-free) (optimize (safety 3)))
           (push (list a xdoseq-free) seen))
         (list source-value seen))))
  (xbind-check '((1 3))
    '(let ((seen nil))
       (sl:doseq (x '(1 2 3))
         (declare (type integer x))
         (when (evenp x) (go xdoseq-skip))
         (push x seen)
         xdoseq-skip)
       (reverse seen)))
  (xbind-check '(nil)
    '(sl:doseq ((x index) '(1 2)) (declare (ignore x index)))))

(parachute:define-test doseq.control-flow
  (xbind-check '(2 :extra)
    '(sl:doseq (x '(1 2 3)) (when (= x 2) (return (values x :extra)))))
  (xbind-check '() '(sl:doseq (x '(1)) (declare (ignore x)) (return (values))))
  (xbind-check '(nil) '(sl:doseq (x '(1)) (declare (ignore x)) (return)))
  (xbind-check '(:outer)
    '(block nil (sl:doseq (x '(1)) (return x)) :outer))
  (xbind-check '((:again :done :again :done))
    '(let ((seen nil))
       (sl:doseq (x '(1 2))
         (go 10)
         xdoseq-again
         (push :again seen)
         (go xdoseq-done)
         10
         (go xdoseq-again)
         xdoseq-done
         (push :done seen))
       (reverse seen))))

(parachute:define-test doseq.error-handling
  (dolist (source '(42 (sl:map-entry :a 1)))
    (xbind-check '(t)
      `(handler-case (sl:doseq (x ,source) (declare (ignore x)))
         (type-error () t))))
  (dolist (form '((sl:doseq ()) (sl:doseq (x)) (sl:doseq (x nil extra))
                  (sl:doseq (x nil . extra)) (sl:doseq (#(42) nil))
                  (sl:doseq ((:entry a) nil)) (sl:doseq ((x :bad) nil))
                  (sl:doseq ((a &environment env) nil))))
    (parachute:fail (macroexpand-1 form) program-error))
  (dolist (marker (list 'sl:? 'sl:@ (make-symbol "?") (make-symbol "@")))
    (parachute:fail
      (macroexpand-1 `(sl:doseq ((x ,marker) nil) nil))
      program-error))
  (xbind-check '(:propagated)
    '(handler-case
         (sl:doseq (x (sl:lazy-seq (error 'xdoseq-sentinel))) (declare (ignore x)))
       (xdoseq-sentinel () :propagated)))
  (xbind-check '(t)
    '(handler-case (sl:doseq (x '(1 . 2)) (declare (ignore x)))
       (type-error () t))))

(parachute:define-test doseq.laziness-and-nonlocal-exits
  (xbind-check '(:first 1)
    '(let ((forces 0))
       (values
         (sl:doseq (x (sl:lazy-seq
                        (progn
                          (incf forces)
                          (sl:lazy-cons :first (sl:lazy-seq (error "forced tail"))))))
           (return x))
         forces)))
  (xbind-check '(:escaped)
    '(catch 'xdoseq-exit
       (sl:doseq (x '(1 2)) (declare (ignore x)) (throw 'xdoseq-exit :escaped))))
  (xbind-check '(((0 :a) (1 :a)) ((:a 0 nil) (:a 1 nil) (:a 0 nil) (:a 1 nil)))
    '(let ((seen nil) (*xdoseq-events* nil))
       (sl:doseq ((#(value _) index)
                   (list (make-instance 'xdoseq-access :name :a)
                         (make-instance 'xdoseq-access :name :a)))
         (push (list index value) seen))
       (values (reverse seen) (reverse *xdoseq-events*)))))

(parachute:define-test doseq.value-bindings
  ;; This is a positive value-binding check, NOT an undefined source mutation.
  (xbind-check '((1 2 3) ((99 77) (99 77) (99 77)))
    '(let ((source (list 1 2 3)) (seen nil))
       (sl:doseq ((element index) source)
         (setf element 99 index 77)
         (push (list element index) seen))
       (values source seen)))
  (xbind-check '(:outer-element :outer-index)
    '(let ((element :outer-element) (index :outer-index))
       (sl:doseq ((element index) '(1)) (declare (ignore element index)))
       (values element index))))

(parachute:define-test doseq.cursor-equivalence-and-no-prefetch
  (eager-traversal-check-corpus
   (lambda (source)
     (let ((seen nil))
       (sl:doseq ((element index) source)
         (eager-traversal-record index)
         (push (cons index element) seen))
       (nreverse seen))))
  (eager-traversal-check-corpus
   (lambda (source)
     (let ((seen nil))
       (sl:doseq ((element index) source)
         (eager-traversal-record index)
         (push (cons index element) seen)
         (when (= index 1) (return (nreverse seen))))
       (nreverse seen)))
   :expected-dotted-callbacks nil)
  ;; The body fails at index one, before a dotted tail or a lazy continuation
  ;; may be demanded. The observed body count must be exactly two on each path.
  (dolist (source (list (list* :a :b :bad)
                        (sl:lazy-cons :a
                                      (sl:lazy-cons :b
                                                    (sl:lazy-seq (error 'xdoseq-sentinel))))))
    (let ((fast (eager-traversal-observe
                 (lambda (items)
                   (sl:doseq ((element index) items)
                     (declare (ignore element))
                     (eager-traversal-record index)
                     (when (= index 1) (error 'xdoseq-sentinel))))
                 source nil))
          (generic (eager-traversal-observe
                    (lambda (items)
                      (sl:doseq ((element index) items)
                        (declare (ignore element))
                        (eager-traversal-record index)
                        (when (= index 1) (error 'xdoseq-sentinel))))
                    source t)))
      (parachute:is equal generic fast)
      (parachute:is equal '(:error xdoseq-sentinel) (first fast))
      (parachute:is = 2 (second fast))
      (parachute:is equal '(0 1) (third fast)))))
