;;;; Independent Chapter 6 forcing oracles; no production helper dependencies.
(in-package #:sophie-lisp.tests)

(defun f1-uncached-keys (function)
  ;; Arithmetic oracle, independent of the chosen comparison algorithm.
  (let* ((input (loop for n downfrom 257 above 0 collect n))
         (keys 0) (comparisons 0) (pending nil) (paired t)
         (result
           (funcall function input
             :key (lambda (x) (incf keys) (push x pending) x)
             :test (lambda (a b)
                     (incf comparisons)
                     (unless (and (= 2 (length pending))
                                  (equal (sort (copy-list pending) #'<)
                                         (sort (list a b) #'<)))
                       (setf paired nil))
                     (setf pending nil)
                     (< a b)))))
    (parachute:is equal (loop for n from 1 to 257 collect n) result)
    (parachute:true (plusp comparisons))
    (parachute:is = (* 2 comparisons) keys)
    (parachute:true paired)
    (parachute:is equal nil pending)
    (parachute:is equal (loop for n downfrom 257 above 0 collect n) input)))


(defun f1-list (source)
  (let ((view source) (out nil))
    (loop for step below 10000
          until (sophie-lisp:seq-emptyp view)
          do (push (sophie-lisp:seq-first view) out)
             (setf view (sophie-lisp:seq-rest view))
          finally (unless (sophie-lisp:seq-emptyp view)
                    (parachute:true nil "F1-LIST exceeded its finite fixture bound")))
    (nreverse out)))

(defun f1-lazy (items visit)
  (sophie-lisp:make-lazy-seq
   (lambda ()
     (funcall visit items)
     (if items (sophie-lisp:lazy-cons (car items) (f1-lazy (cdr items) visit)) nil))))

(defclass f1-source () ((items :initarg :items :reader f1-items)))
(defclass f1-collected (f1-source) ())
(defclass f1-collector ()
  ((items :initform nil :accessor f1-buffer)
   (result :initform nil :accessor f1-result)))
(defvar *f1-refuse* nil)
(defmethod sophie-lisp:seqablep ((x f1-source)) t)
(defmethod sophie-lisp:seq-emptyp ((x f1-source)) (null (f1-items x)))
(defmethod sophie-lisp:seq-first ((x f1-source)) (car (f1-items x)))
(defmethod sophie-lisp:seq-rest ((x f1-source)) (cdr (f1-items x)))
(defmethod sophie-lisp:make-collector-for ((x f1-collected) &key)
  (make-instance 'f1-collector))
(defmethod sophie-lisp:collector-accumulate ((c f1-collector) item)
  (when *f1-refuse* (error *f1-refuse*))
  (push item (f1-buffer c)) c)
(defmethod sophie-lisp:collector-result ((c f1-collector))
  (or (f1-result c)
      (setf (f1-result c) (make-instance 'f1-collected :items (reverse (f1-buffer c))))))

(defun f1-vector-check (function items expected)
  (let* ((source (make-array 6 :element-type '(unsigned-byte 8)
                             :initial-contents (append items '(99 98 97)) :fill-pointer 3))
         (result (funcall function source)))
    (parachute:is equalp (coerce expected 'vector) result)
    (parachute:is equal (array-element-type source) (array-element-type result))
    (parachute:false (eq source result))
    (parachute:is equal items (coerce source 'list))
    (parachute:is = 99 (aref source 3)))
  (let* ((source (make-array 0 :element-type 'bit)) (result (funcall function source)))
    (parachute:is = 0 (length result))
    (parachute:is equal (array-element-type source) (array-element-type result))
    (parachute:false (eq source result))))

(defun f1-timing (function expected)
  (let ((visits 0))
    (let ((result (funcall function (f1-lazy '(3 1 2) (lambda (x) (declare (ignore x)) (incf visits))))))
      ;; Return representation does not imply deferred input traversal.
      (parachute:is = 4 visits)
      (parachute:true (sophie-lisp:lazy-seq-p result))
      (parachute:is equal expected (f1-list result))
      (parachute:is = 4 visits)))
  (let* ((sentinel (make-condition 'simple-error :format-control "finite end sentinel"))
         (calls 0)
         (source (f1-lazy '(3 1 2) (lambda (tail) (incf calls) (unless tail (error sentinel))))))
    (parachute:is eq sentinel (handler-case (progn (funcall function source) nil) (error (c) c)))
    (parachute:is = 4 calls)))

(defun f1-extension (function expected)
  (let ((result (funcall function (make-instance 'f1-collected :items '(3 1 2)))))
    (parachute:true (typep result 'f1-collected))
    (parachute:is equal expected (f1-items result)))
  (let ((result (funcall function (make-instance 'f1-source :items '(3 1 2)))))
    (parachute:true (sophie-lisp:lazy-seq-p result))
    (parachute:is equal expected (f1-list result)))
  (let ((*f1-refuse* (make-condition 'simple-error :format-control "collector refusal")))
    (parachute:is eq *f1-refuse*
                  (handler-case (progn (funcall function (make-instance 'f1-collected :items '(3 1 2))) nil)
                    (error (c) c)))))

(parachute:define-test seq-reverse.representations-and-validation
  (f1-vector-check #'sophie-lisp:seq-reverse '(1 2 3) '(3 2 1))
  (parachute:is equal '(3 2 1) (sophie-lisp:seq-reverse '(1 2 3)))
  (parachute:is string= "cba" (sophie-lisp:seq-reverse "abc"))
  (let* ((source (sophie-lisp:ordered-dict :a 7 :b 8))
         (normalized (f1-list source))
         (result (sophie-lisp:seq-reverse source)))
    (parachute:true (sophie-lisp:ordered-dict-p result))
    (parachute:true (every (lambda (entry) (typep entry 'sophie-lisp:map-entry))
                           (f1-list result)))
    (parachute:is equal
                  (mapcar (lambda (entry) (list (sophie-lisp:entry-key entry)
                                                 (sophie-lisp:entry-value entry)))
                          (reverse normalized))
                  (mapcar (lambda (entry) (list (sophie-lisp:entry-key entry)
                                                 (sophie-lisp:entry-value entry)))
                          (f1-list result))))
  (dolist (key '(:test :test-not :key :start))
    (parachute:fail (funcall #'sophie-lisp:seq-reverse '(1) key nil) program-error)))

(parachute:define-test seq-reverse.forcing
  (f1-timing #'sophie-lisp:seq-reverse '(2 1 3)))

(parachute:define-test seq-reverse.extensions
  (f1-extension #'sophie-lisp:seq-reverse '(2 1 3))
  (let ((table (make-hash-table)))
    (setf (gethash :a table) 7 (gethash :b table) 8)
    (dolist (source (list table (sophie-lisp:dict :a 7 :b 8)))
      (let ((result (sophie-lisp:seq-reverse source)))
        (parachute:true (sophie-lisp:ordered-dict-p result))
        (parachute:is = 2 (sophie-lisp:dict-size result))
        (parachute:is = 7 (sophie-lisp:dict-ref result :a))
        (parachute:is = 8 (sophie-lisp:dict-ref result :b)))))
  (let ((result (sophie-lisp:seq-reverse (sophie-lisp:hash-set 1 2 3))))
    (parachute:true (sophie-lisp:lazy-seq-p result))
    (parachute:is equal '(1 2 3) (sort (f1-list result) #'<))))

(parachute:define-test seq-sort.ordering-and-validation
  (f1-vector-check #'sophie-lisp:seq-sort '(3 1 2) '(1 2 3))
  (parachute:is equal '(1 2 3) (sophie-lisp:seq-sort '(3 1 2) :key nil))
  (parachute:is equal '(3 2 1) (sophie-lisp:seq-sort '(3 1 2) :test #'> :key #'identity))
  (dolist (key '(:test-not :start :end :from-end :count :unknown))
    (parachute:fail (sophie-lisp:seq-sort '(1) key nil) program-error)))

(parachute:define-test seq-sort.forcing-and-callbacks
  (f1-timing #'sophie-lisp:seq-sort '(1 2 3))
  (let ((keys nil) (comparisons 0))
    (parachute:is equal '(1 2 3)
      (sophie-lisp:seq-sort '(3 1 2) :key (lambda (x) (push x keys) x)
                               :test (lambda (a b) (incf comparisons) (< a b))))
    (parachute:true (plusp comparisons))
    ;; No prescribed sorting algorithm or exact number of repeated key calls.
    (parachute:is equal '(1 2 3) (sort (remove-duplicates keys) #'<)))
  (dolist (option '(:key :test))
    (let* ((calls 0)
           (source (f1-lazy '(3 1 2) (lambda (x) (declare (ignore x)) (incf calls)))))
      (parachute:fail (sophie-lisp:seq-sort source option 42) type-error)
      (parachute:is = 0 calls)))
  (dolist (option '(:key :test))
    (let ((sentinel (make-condition 'simple-error :format-control "sort callback")))
      (parachute:is eq sentinel
        (handler-case
            (sophie-lisp:seq-sort '(3 1 2) option
              (lambda (&rest values) (declare (ignore values)) (error sentinel)))
          (error (c) c)))))
  (f1-uncached-keys #'sophie-lisp:seq-sort))

(defun f1-coalescing-sort-check (operation)
  (let* ((first (copy-seq "a")) (second (copy-seq "a"))
         (table (make-hash-table :test 'eql)) (compared nil))
    (setf (gethash first table) 2 (gethash second table) 1 (gethash "b" table) 3)
    (let ((result (funcall operation table :key #'sophie-lisp:entry-value
                           :test (lambda (left right)
                                   (push (list left right) compared) (< left right)))))
      (parachute:true (sophie-lisp:ordered-dict-p result))
      (parachute:is = 2 (sophie-lisp:dict-size result))
      (parachute:is = 1 (count-if (lambda (entry)
                                    (string= "a" (sophie-lisp:entry-key entry)))
                                  (f1-list result)))
      (parachute:true (apply #'<= (mapcar #'sophie-lisp:entry-value (f1-list result))))
      (parachute:true (plusp (length compared)))
      (parachute:is = 1
                    (length (remove-duplicates
                             (remove-if-not (lambda (value) (member value '(1 2)))
                                            (apply #'append compared))))))))

(parachute:define-test seq-sort.extensions-and-coalescing
  (f1-extension #'sophie-lisp:seq-sort '(1 2 3))
  (dolist (pair (list (list 1 :a) (list #c(1 2) 2) (list nil :a)))
    (parachute:fail (sophie-lisp:seq-sort pair) simple-error))
  (parachute:is equal '((1 b) (2 a)) (sophie-lisp:seq-sort '((2 a) (1 b)) :key #'car))
  (let ((result (sophie-lisp:seq-sort (sophie-lisp:hash-set 3 1 2))))
    (parachute:true (sophie-lisp:lazy-seq-p result))
    (parachute:is equal '(1 2 3) (f1-list result)))
  (let ((table (make-hash-table)))
    (setf (gethash :b table) 2 (gethash :a table) 1)
    (dolist (source (list table (sophie-lisp:dict :b 2 :a 1)))
      (let ((result (sophie-lisp:seq-sort source :key #'sophie-lisp:entry-value)))
        (parachute:true (sophie-lisp:ordered-dict-p result))
        (parachute:is equal '(1 2)
                      (mapcar #'sophie-lisp:entry-value (f1-list result))))))
  (f1-coalescing-sort-check #'sophie-lisp:seq-sort))

(parachute:define-test seq-stable-sort.ordering-and-validation
  (f1-vector-check #'sophie-lisp:seq-stable-sort '(3 1 2) '(1 2 3))
  (parachute:is equalp #((0 c) (1 a) (1 b))
    (sophie-lisp:seq-stable-sort #((1 a) (1 b) (0 c)) :key #'car))
  (dolist (key '(:test-not :start :end :from-end :count))
    (parachute:fail (sophie-lisp:seq-stable-sort '(1) key nil) program-error)))

(parachute:define-test seq-stable-sort.forcing-and-callbacks
  (f1-timing #'sophie-lisp:seq-stable-sort '(1 2 3))
  (let ((keys nil) (comparisons 0))
    (parachute:is equal '(1 2 3)
      (sophie-lisp:seq-stable-sort '(3 1 2) :key (lambda (x) (push x keys) x)
                               :test (lambda (a b) (incf comparisons) (< a b))))
    (parachute:true (plusp comparisons))
    ;; No prescribed sorting algorithm or exact number of repeated key calls.
    (parachute:is equal '(1 2 3) (sort (remove-duplicates keys) #'<)))
  (dolist (option '(:key :test))
    (let* ((calls 0)
           (source (f1-lazy '(3 1 2) (lambda (x) (declare (ignore x)) (incf calls)))))
      (parachute:fail (sophie-lisp:seq-stable-sort source option 42) type-error)
      (parachute:is = 0 calls)))
  (dolist (option '(:key :test))
    (let ((sentinel (make-condition 'simple-error :format-control "sort callback")))
      (parachute:is eq sentinel
        (handler-case
            (sophie-lisp:seq-stable-sort '(3 1 2) option
              (lambda (&rest values) (declare (ignore values)) (error sentinel)))
          (error (c) c)))))
  (f1-uncached-keys #'sophie-lisp:seq-stable-sort))

(parachute:define-test seq-stable-sort.extensions-and-stability
  (f1-extension #'sophie-lisp:seq-stable-sort '(1 2 3))
  (let* ((a (list 1 :a)) (b (list 1.0 :b)) (c (list 0 :c))
         (source (vector a b c))
         (result (sophie-lisp:seq-stable-sort source :key #'car)))
    (parachute:is eq c (aref result 0))
    (parachute:is eq a (aref result 1))
    (parachute:is eq b (aref result 2))
    (parachute:is eq t (array-element-type result)))
  (f1-coalescing-sort-check #'sophie-lisp:seq-stable-sort))

;;; Frozen pre-optimization merge schedule: a test oracle, not a production helper.
(defun f1-sort-schedule-oracle (elements test key)
  (let* ((input (coerce elements 'vector))
         (size (length input))
         (output (make-array size)))
    (loop for width = 1 then (* 2 width)
          while (< width size)
          do (loop for start from 0 below size by (* 2 width)
                   for middle = (min size (+ start width))
                   for end = (min size (+ middle width))
                   do (let ((left start) (right middle))
                        (loop for destination from start below end
                              do (setf (aref output destination)
                                       (cond
                                         ((= left middle)
                                          (prog1 (aref input right) (incf right)))
                                         ((= right end)
                                          (prog1 (aref input left) (incf left)))
                                         ((funcall test (funcall key (aref input right))
                                                   (funcall key (aref input left)))
                                          (prog1 (aref input right) (incf right)))
                                         (t
                                          (prog1 (aref input left) (incf left))))))))
          (rotatef input output))
    (coerce input 'list)))

(parachute:define-test seq-sort.pre-optimization-callback-traces
  (dolist (operation '(sophie-lisp:seq-sort sophie-lisp:seq-stable-sort))
    (dolist (items '(() ((2 a)) ((3 a) (1 b) (3 c) (2 d) (1 e))
                     ((0 a) (0 b) (0 c) (0 d))
                     ((7 a) (1 b) (5 c) (4 d) (0 e) (7 f) (1 g) (4 h) (3 i))))
      (let ((expected-events nil) (actual-events nil)
            (source (coerce items 'vector)))
        (flet ((expected-key (item)
                 (push (list :key (second item)) expected-events)
                 (first item))
               (expected-test (right left)
                 (push (list :test right left) expected-events)
                 (< right left))
               (actual-key (item)
                 (push (list :key (second item)) actual-events)
                 (first item))
               (actual-test (right left)
                 (push (list :test right left) actual-events)
                 (< right left)))
          (let ((expected (f1-sort-schedule-oracle items #'expected-test #'expected-key))
                (actual (funcall operation source :key #'actual-key :test #'actual-test)))
            (parachute:is equal expected (coerce actual 'list))
            (parachute:is equal (nreverse expected-events) (nreverse actual-events))
            (parachute:is equal items (coerce source 'list))))))))

(defun f2-predicate-events (function expected)
  (let ((events nil))
    (let ((result (funcall function '(0 0 1 0 2 0 0)
                   :predicate (lambda (x) (push x events) (zerop x)))))
      (parachute:is equal expected result)
      (parachute:is equal '(0 0 1 0 2 0 0) (reverse events))))
  (let ((events nil)
        (sentinel (make-condition 'simple-error :format-control "trim predicate escape")))
    (parachute:is eq sentinel
      (handler-case
          (funcall function '(0 0 1 0 2 0 0)
            :predicate (lambda (x)
                         (push x events)
                         (when (= x 2) (error sentinel))
                         (zerop x)))
        (error (c) c)))
    ;; No trailing predicate calls after the escaped invocation.
    (parachute:is equal '(0 0 1 0 2) (reverse events))))



(defun f2-list (source)
  (let ((view source) (out nil))
    (loop for step below 10000
          until (sophie-lisp:seq-emptyp view)
          do (push (sophie-lisp:seq-first view) out)
             (setf view (sophie-lisp:seq-rest view))
          finally (unless (sophie-lisp:seq-emptyp view)
                    (parachute:true nil "F2-LIST exceeded its finite fixture bound")))
    (nreverse out)))
(defun f2-lazy (items visit)
  (sophie-lisp:make-lazy-seq
   (lambda () (funcall visit items)
     (if items (sophie-lisp:lazy-cons (car items) (f2-lazy (cdr items) visit)) nil))))
(defclass f2-source () ((items :initarg :items :reader f2-items)))
(defclass f2-collector ()
  ((items :initform nil :accessor f2-buffer)
   (result :initform nil :accessor f2-result)))
(defvar *f2-refuse* nil)
(defmethod sophie-lisp:seqablep ((x f2-source)) t)
(defmethod sophie-lisp:seq-emptyp ((x f2-source)) (null (f2-items x)))
(defmethod sophie-lisp:seq-first ((x f2-source)) (car (f2-items x)))
(defmethod sophie-lisp:seq-rest ((x f2-source)) (cdr (f2-items x)))
(defmethod sophie-lisp:make-collector-for ((x f2-source) &key)
  (make-instance 'f2-collector))
(defmethod sophie-lisp:collector-accumulate ((c f2-collector) x)
  (when *f2-refuse* (error *f2-refuse*)) (push x (f2-buffer c)) c)
(defmethod sophie-lisp:collector-result ((c f2-collector))
  (or (f2-result c)
      (setf (f2-result c) (make-instance 'f2-source :items (reverse (f2-buffer c))))))

(defun f2-timing (function expected)
  (let ((visits 0))
    (let ((result (funcall function
                   (f2-lazy '(0 1 0 2 0) (lambda (x) (declare (ignore x)) (incf visits))))))
      (parachute:is = 6 visits)
      (parachute:true (sophie-lisp:lazy-seq-p result))
      (parachute:is equal expected (f2-list result))
      (parachute:is = 6 visits)))
  (let* ((sentinel (make-condition 'simple-error :format-control "finite trailing sentinel"))
         (source (f2-lazy '(0 1 0 2 0) (lambda (tail) (unless tail (error sentinel))))))
    (parachute:is eq sentinel
      (handler-case (progn (funcall function source) nil) (error (c) c)))))

(defun f2-vector (function expected)
  (let* ((source (make-array 7 :element-type '(unsigned-byte 8) :fill-pointer 5
                             :initial-contents '(0 1 0 2 0 99 98)))
         (result (funcall function source)))
    (parachute:is equal expected (coerce result 'list))
    (parachute:is equal (array-element-type source) (array-element-type result))
    (parachute:false (eq source result))
    (parachute:is equal '(0 1 0 2 0) (coerce source 'list)))
  (let* ((source (make-array 0 :element-type 'bit)) (result (funcall function source)))
    (parachute:is = 0 (length result))
    (parachute:is equal (array-element-type source) (array-element-type result))
    (parachute:false (eq source result))))

(defun f2-roster (function)
  ;; Retain all entries: independent traversals need not choose the same order.
  (let ((table (make-hash-table :test 'eq)) (value (list :value)))
    (setf (gethash :a table) value)
    (dolist (source (list table (sophie-lisp:dict :a value)))
      (let ((result (funcall function source)))
        (parachute:true (typep result (class-of source)))
        (parachute:is eq (sophie-lisp:dict-test source) (sophie-lisp:dict-test result))
        (parachute:is = 1 (sophie-lisp:seq-length result))
        (parachute:is eq value (sophie-lisp:entry-value (sophie-lisp:seq-first result)))))
    (parachute:false (eq table (funcall function table)))))

(parachute:define-test seq-take-last.representations-and-validation
  (f2-vector (lambda (s) (sophie-lisp:seq-take-last 2 s)) '(2 0))
  (parachute:is equal '(3 4) (sophie-lisp:seq-take-last 2 '(1 2 3 4)))
  (parachute:is equal '(1 2) (sophie-lisp:seq-take-last 10 '(1 2)))
  (dolist (n '(-1 1/2 nil))
    (parachute:fail (sophie-lisp:seq-take-last n '(1)) type-error))
  (dolist (key '(:test :key))
    (parachute:fail (funcall #'sophie-lisp:seq-take-last 1 '(1) key nil) program-error)))

(parachute:define-test seq-take-last.forcing-and-empty-results
  (f2-timing (lambda (s) (sophie-lisp:seq-take-last 2 s)) '(2 0))
  (let ((visits 0))
    (let ((result
            (sophie-lisp:seq-take-last 0
              (f2-lazy '(1) (lambda (tail) (declare (ignore tail)) (incf visits))))))
      (parachute:is = 0 visits)
      (parachute:true (sophie-lisp:seq-emptyp result))
      (parachute:is = 0 visits)))
  (let* ((source (vector 1 2)) (result (sophie-lisp:seq-take-last 0 source)))
    (parachute:is = 0 (length result))
    (parachute:false (eq source result)))
  (let* ((source (copy-seq "abc")) (result (sophie-lisp:seq-take-last 0 source)))
    (parachute:is string= "" result)
    (parachute:false (eq source result)))
  (parachute:true (sophie-lisp:seq-emptyp (sophie-lisp:seq-take-last 0 nil))))

(parachute:define-test seq-take-last.extensions
  (f2-roster (lambda (s) (sophie-lisp:seq-take-last 10 s)))
  (let* ((source (sophie-lisp:dict :a 1 :b 2 :c 3))
         (result (sophie-lisp:seq-take-last 1 source)))
    (parachute:true (typep result 'sophie-lisp:dict))
    (parachute:is = 1 (sophie-lisp:seq-length result)))
  (let ((result (sophie-lisp:seq-take-last 10 (sophie-lisp:hash-set 1 2 3))))
    (parachute:true (sophie-lisp:lazy-seq-p result))
    (parachute:is equal '(1 2 3) (sort (f2-list result) #'<))))

(parachute:define-test seq-trim-right.representations-and-validation
  (parachute:is string= "x" (sl:seq-trim-right "x "))
  (f2-vector (lambda (s) (sophie-lisp:seq-trim-right s :predicate #'zerop)) '(0 1 0 2))
  (let* ((source (copy-seq "x  "))
         (result (sophie-lisp:seq-trim-right source :predicate (lambda (c) (char= c #\Space)))))
    (parachute:is string= "x" result)
    (parachute:false (eq source result))
    (parachute:is string= "x  " source))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (sophie-lisp:seq-trim-right "x" key nil) program-error))
  (parachute:fail (sophie-lisp:seq-trim-right "x" :predicate nil) program-error))
(parachute:define-test seq-trim-right.forcing-and-predicates
  (f2-timing (lambda (s) (sophie-lisp:seq-trim-right s :predicate #'zerop)) '(0 1 0 2))
  (let* ((visits 0) (source (f2-lazy '(1) (lambda (x) (declare (ignore x)) (incf visits)))))
    (parachute:fail (sophie-lisp:seq-trim-right source) program-error)
    (parachute:is = 0 visits))
  (parachute:is equal '(0 1 0 2)
    (sophie-lisp:seq-trim-right '(0 1 0 2 0) :predicate #'zerop))
  (f2-predicate-events #'sophie-lisp:seq-trim-right '(0 0 1 0 2)))

(parachute:define-test seq-trim-right.extensions
  (f2-roster (lambda (s) (sophie-lisp:seq-trim-right s :predicate (constantly nil))))
  (let ((calls 0))
    (let ((result (sophie-lisp:seq-trim-right (sophie-lisp:dict :a 1)
                    :predicate (lambda (e) (incf calls) (typep e 'sophie-lisp:map-entry)))))
      (parachute:is = 1 calls)
      (parachute:is = 0 (sophie-lisp:seq-length result))))
  (let ((*f2-refuse* (make-condition 'simple-error :format-control "refuse reconstruction")))
    (parachute:is eq *f2-refuse*
      (handler-case (sophie-lisp:seq-trim-right (make-instance 'f2-source :items '(1))
                                              :predicate #'zerop)
        (error (c) c)))))

(parachute:define-test seq-trim.representations-and-validation
  (parachute:is string= "x" (sl:seq-trim " x "))
  (f2-vector (lambda (s) (sophie-lisp:seq-trim s :predicate #'zerop)) '(1 0 2))
  (let* ((source (copy-seq "  x  "))
         (result (sophie-lisp:seq-trim source :predicate (lambda (c) (char= c #\Space)))))
    (parachute:is string= "x" result)
    (parachute:false (eq source result))
    (parachute:is string= "  x  " source))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (sophie-lisp:seq-trim "x" key nil) program-error))
  (parachute:fail (sophie-lisp:seq-trim "x" :predicate nil) program-error))
(parachute:define-test seq-trim.forcing-and-predicates
  (f2-timing (lambda (s) (sophie-lisp:seq-trim s :predicate #'zerop)) '(1 0 2))
  (parachute:is equal '(1 0 2) (sophie-lisp:seq-trim '(0 1 0 2 0) :predicate #'zerop))
  (parachute:is equal nil (sophie-lisp:seq-trim '(0 0 0) :predicate #'zerop))
  (f2-predicate-events #'sophie-lisp:seq-trim '(1 0 2)))
(parachute:define-test seq-trim.extensions
  (f2-roster (lambda (s) (sophie-lisp:seq-trim s :predicate (constantly nil))))
  (let ((calls 0))
    (let ((result (sophie-lisp:seq-trim (sophie-lisp:hash-set 1 2 3)
                     :predicate (lambda (x) (declare (ignore x)) (incf calls) t))))
      (parachute:is = 3 calls)
      (parachute:true (sophie-lisp:lazy-seq-p result))
      (parachute:true (sophie-lisp:seq-emptyp result))
      (parachute:is = 3 calls)))
  (let* ((visits 0) (source (f2-lazy '(1) (lambda (x) (declare (ignore x)) (incf visits)))))
    (parachute:fail (sophie-lisp:seq-trim source) program-error)
    (parachute:is = 0 visits))
  (let ((*f2-refuse* (make-condition 'simple-error :format-control "refuse trim")))
    (parachute:is eq *f2-refuse*
      (handler-case (sophie-lisp:seq-trim (make-instance 'f2-source :items '(1)) :predicate #'zerop)
        (error (c) c)))))

;;;; Independent reduction oracle: construct association trees, not CL:REDUCE.
(defun l01-r-lazy (items observe)
  (sl:make-lazy-seq (lambda () (funcall observe (if items (car items) :end))
                     (if items (sl:lazy-cons (car items) (l01-r-lazy (cdr items) observe)) nil))))
(defun l01-r-error (thunk type)
  ;; ECL's TYPEP returns a truthy class-precedence list, not T, when the
  ;; signaled condition's class is a strict subclass of TYPE; normalize to a
  ;; strict boolean so the EQ-T assertions hold on every host.
  (handler-case (progn (funcall thunk) nil)
    (error (c) (if (typep c type) t nil))))
(defclass l01-r-source () ((items :initarg :items :reader l01-r-items)))
(defmethod sl:seqablep ((s l01-r-source)) t)
(defmethod sl:seq-emptyp ((s l01-r-source)) (null (l01-r-items s)))
(defmethod sl:seq-first ((s l01-r-source)) (car (l01-r-items s)))
(defmethod sl:seq-rest ((s l01-r-source)) (make-instance 'l01-r-source :items (cdr (l01-r-items s))))
(defmethod sl:make-collector-for ((s l01-r-source) &key) (error "Scalar reduction Collector"))
(defun l01-r-model (items backwards seeded seed)
  (let* ((xs (mapcar #'1+ (if backwards (reverse items) items)))
         (acc (if seeded seed (pop xs))))
    (dolist (x xs acc) (setf acc (if backwards (list x acc) (list acc x))))))

(parachute:define-test seq-reduce.finite-model-and-validation
  (parachute:is eq t (typep (fdefinition 'sl:seq-reduce) 'generic-function))
  (loop for seed from 1 to 20
        for items = (loop for i below (+ 1 (mod seed 7)) collect (mod (+ seed (* i 13)) 17))
        do (dolist (backwards '(nil t))
             (dolist (seeded '(nil t))
               (dolist (source (list items (coerce items 'vector)))
                 (parachute:is equal (l01-r-model items backwards seeded nil)
                   (apply #'sl:seq-reduce #'list source :key #'1+ :from-end backwards
                          (when seeded (list :initial-value nil))))))))
  (parachute:is = 9 (sl:seq-reduce #'+ #(1 2 3) :key #'1+ :initial-value 0))
  (parachute:is equal '(nil 3) (sl:seq-reduce #'list '(3) :initial-value nil))
  (parachute:is equal '(3 nil) (sl:seq-reduce #'list '(3) :initial-value nil :from-end t))
  (parachute:is = 5 (sl:seq-reduce #'+ #(9 2 3 8) :start 1 :end 3 :key nil))
  (parachute:is = 6 (sl:seq-reduce #'+ #(1 2 3) :end 99))
  (parachute:is = 3 (sl:seq-reduce #'+ (make-array 4 :initial-contents '(1 2 99 99) :fill-pointer 2)))
  (dolist (keyword '(:test :test-not))
    (parachute:is eq t (l01-r-error (lambda () (funcall 'sl:seq-reduce #'+ '(1) keyword nil)) 'program-error))))

(parachute:define-test seq-reduce.forcing-and-order
  (dolist (backwards '(nil t))
    (let ((forces nil) (keys nil) (calls nil))
      (parachute:is equal (if backwards '(2 (3 :seed)) '((:seed 2) 3))
        (sl:seq-reduce (lambda (a b) (push (list a b) calls) (values (list a b) :ignored))
                       (l01-r-lazy '(9 2 3 8) (lambda (x) (push x forces) (when (eql x 8) (error "past END"))))
                       :start 1 :end 3 :from-end backwards :initial-value :seed
                       :key (lambda (x) (push x keys) (values x :ignored))))
      (parachute:is equal '(9 2 3) (reverse forces))
      (parachute:is equal (if backwards '(3 2) '(2 3)) (reverse keys))
      (parachute:is equal (if backwards '((3 :seed) (2 (3 :seed))) '((:seed 2) ((:seed 2) 3)))
        (reverse calls))))
  (let ((sentinel (make-condition 'simple-error :format-control "zero-end sentinel")))
    (parachute:is eq :seed
      (sl:seq-reduce #'+
                     (l01-r-lazy '(1) (lambda (x) (declare (ignore x)) (error sentinel)))
                     :end 0 :initial-value :seed)))
  (let ((events nil))
    (parachute:is = 6 (sl:seq-reduce #'+ (l01-r-lazy '(1 2 3) (lambda (x) (push x events)))))
    (parachute:is equal '(1 2 3 :end) (reverse events)))
  (let ((marker (make-condition 'simple-error :format-control "end sentinel")))
    (parachute:is eq marker
      (handler-case (sl:seq-reduce #'+ (l01-r-lazy '(1 2) (lambda (x) (when (eq x :end) (error marker)))))
        (error (c) c))))
  (let ((calls 0) (keys 0))
    (parachute:is = 4 (sl:seq-reduce (lambda (&rest xs) (declare (ignore xs)) (incf calls)) '(3)
                                    :key (lambda (x) (incf keys) (1+ x))))
    (parachute:is equal '(0 1) (list calls keys))))

(parachute:define-test seq-reduce.empty-input-and-errors
  (let ((calls 0) (keys 0) (seed (list :seed)))
    (dolist (source (list nil #() (sl:make-lazy-seq (lambda () nil))))
      ;; Sophie does NOT invoke FUNCTION with zero arguments on empty input.
      (parachute:is eq t
        (l01-r-error (lambda () (sl:seq-reduce (lambda (&rest xs) (declare (ignore xs)) (incf calls)) source)) 'simple-error))
      (parachute:is eq seed
        (sl:seq-reduce (lambda (&rest xs) (declare (ignore xs)) (incf calls)) source
                       :initial-value seed :key (lambda (x) (incf keys) x))))
    (parachute:is = 0 calls)
    (parachute:is = 0 keys))
  (parachute:is eq nil (sl:seq-reduce #'+ '(1 2) :start 2 :initial-value nil))
  (parachute:is eq t (l01-r-error (lambda () (sl:seq-reduce #'+ '(1 2) :start 2)) 'simple-error))
  (parachute:is equal '(1 (2 3)) (sl:seq-reduce #'list '(1 2 3) :from-end t))
  (parachute:is = 6 (sl:seq-reduce '+ (make-instance 'l01-r-source :items '(1 2 3))))
  (dolist (options '((:start -1) (:start 1/2) (:end 1/2) (:start 2 :end 1) (:key 42)))
    (let ((forces 0))
      (parachute:is eq t
        (l01-r-error (lambda () (apply #'sl:seq-reduce #'+
                                  (l01-r-lazy '(1) (lambda (x) (declare (ignore x)) (incf forces))) options)) 'type-error))
      (parachute:is = 0 forces)))
  (dolist (function (list nil 42 'l01-r-unbound-function))
    (let ((forces 0))
      (parachute:is eq t
        (l01-r-error (lambda () (sl:seq-reduce function
                                (l01-r-lazy '(1) (lambda (x) (declare (ignore x)) (incf forces))))) 'type-error))
      (parachute:is = 0 forces)))
  (parachute:is eq t (l01-r-error (lambda () (sl:seq-reduce #'+ '(1) :start 2)) 'type-error))
  (parachute:is eq t (l01-r-error (lambda () (sl:seq-reduce #'+ 42)) 'type-error))
  (let ((marker (make-condition 'simple-error :format-control "callback sentinel")))
    (parachute:is eq marker
      (handler-case (sl:seq-reduce (lambda (a b) (declare (ignore a b)) (error marker)) '(1 2))
        (error (c) c)))
    (parachute:is eq marker
      (handler-case (sl:seq-reduce #'+ '(1) :key (lambda (x) (declare (ignore x)) (error marker)))
        (error (c) c)))))

(parachute:define-test eager-traversal.aggregation-equivalence
  (dolist (operation
           (list (lambda (source) (sl:seq-reverse source))
                 (lambda (source) (sl:seq-sort source :test (lambda (a b)
                                                            (declare (ignore a b)) nil)))
                 (lambda (source) (sl:seq-stable-sort source :test (lambda (a b)
                                                                   (declare (ignore a b)) nil)))
                 (lambda (source) (sl:seq-take-last 2 source))
                 (lambda (source)
                   (sl:seq-trim-right source :predicate
                                      (lambda (item)
                                        (eager-traversal-query-record :trim item)
                                        nil)))
                 (lambda (source)
                   (sl:seq-trim source :predicate
                                (lambda (item)
                                  (eager-traversal-query-record :trim item)
                                  nil)))))
    (eager-traversal-check-corpus operation :expected-dotted-callbacks nil))
  (dolist (bounds '((0 nil) (0 0) (0 2) (1 3) (2 2) (4 4) (5 nil)))
    (dolist (backwards '(nil t))
      (dolist (seeded '(nil t))
        (eager-traversal-check-corpus
         (lambda (source)
           (apply #'sl:seq-reduce
                  (lambda (left right)
                    (eager-traversal-query-record :combine left right)
                    (list left right))
                  source :start (first bounds) :end (second bounds)
                  :from-end backwards
                  :key (lambda (item)
                         (eager-traversal-query-record :key item)
                         1)
                  (when seeded (list :initial-value :seed))))
         :expected-dotted-callbacks nil)))
  (dolist (generic-p '(nil t))
    (let ((sophie-lisp.internal::*force-generic-traversal* generic-p)
          (source (list 3 1 2)))
      (let ((result (sl:seq-reverse source)))
        (parachute:is equal '(2 1 3) result)
        (parachute:is eq nil (eq source result)))
      (let ((result (sl:seq-sort source)))
        (parachute:is equal '(1 2 3) result)
        (parachute:is eq nil (eq source result)))))))
