(in-package #:sophie-lisp.tests)

;;;; Independent sliding-buffer and adjacent-run oracles; Chapter 6.2.4.
(defun part03-list (source)
  (loop with view = source for i below 100 until (sl:seq-emptyp view)
        collect (sl:seq-first view) do (setf view (sl:seq-rest view))
        finally (unless (sl:seq-emptyp view)
                  (parachute:true nil "PART03-LIST exceeded its finite fixture bound"))))
(defun part03-pieces (source) (mapcar #'part03-list (part03-list source)))
(defun part03-stream (items observer &optional (i 0))
  (sl:make-lazy-seq
   (lambda () (funcall observer i)
     (if items (sl:lazy-cons (car items) (part03-stream (cdr items) observer (1+ i))) nil))))
(defclass part03-source () ((items :initarg :items :reader part03-items)))
(defclass part03-collected (part03-source) ())
(defmethod sl:seqablep ((x part03-source)) t)
(defmethod sl:seq-emptyp ((x part03-source)) (null (part03-items x)))
(defmethod sl:seq-first ((x part03-source)) (car (part03-items x)))
(defmethod sl:seq-rest ((x part03-source)) (cdr (part03-items x)))
(defclass part03-collector ()
  ((items :initform nil :accessor part03-acc) (result :accessor part03-result)))
(defvar *part03-collects* 0)
(defvar *part03-refusal* nil)
(defmethod sl:make-collector-for ((x part03-collected) &key)
  (incf *part03-collects*) (make-instance 'part03-collector))
(defmethod sl:collector-accumulate ((c part03-collector) x)
  (when *part03-refusal* (error *part03-refusal*))
  (push x (part03-acc c)) c)
(defmethod sl:collector-result ((c part03-collector))
  (if (slot-boundp c 'result) (part03-result c)
      (setf (part03-result c)
            (make-instance 'part03-collected :items (reverse (part03-acc c))))))

(parachute:define-test seq-partition.representations-and-validation
  (let* ((s (vector 1 2 3 4 5)) (r (sl:seq-partition 2 s :step 2 :pad nil)))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is equalp '(#(1 2) #(3 4)) (part03-list r))
    (dolist (p (part03-list r))
      (parachute:false (eq p s)) (parachute:is eq t (array-element-type p)))
    (parachute:is equalp #(1 2 3 4 5) s))
  (parachute:is equal '((1 2) (3 4)) (part03-list (sl:seq-partition 2 '(1 2 3 4 5))))
  (parachute:is equal '("ab" "cd") (part03-list (sl:seq-partition 2 "abcde")))
  (parachute:is eq nil (part03-list (sl:seq-partition 2 nil :pad t)))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (funcall #'sl:seq-partition 2 '(1 2) key nil) program-error)))

(parachute:define-test seq-partition.padding-and-forcing
  (parachute:is equal '((1 2 3) (2 3 4) (3 4 5) (4 5))
                (part03-pieces (sl:seq-partition 3 '(1 2 3 4 5) :step 1 :pad t)))
  (parachute:is equal '((1 2) (4 5) (7))
                (part03-pieces (sl:seq-partition 2 '(1 2 3 4 5 6 7) :step 3 :pad t)))
  (parachute:is equal '((1 2 3) (4 9))
                (part03-pieces (sl:seq-partition 3 '(1 2 3 4) :pad '(9))))
  (parachute:is equal '((1 2) (3 9))
                (part03-pieces (sl:seq-partition 2 '(1 2 3) :pad '(9 8))))
  (parachute:is equal '((1)) (part03-pieces (sl:seq-partition 2 '(1) :pad #())))
  (let* ((reads nil) (pads nil)
         (r (sl:seq-partition 2 (part03-stream '(1 2 3) (lambda (i) (push i reads)))
                              :pad (part03-stream '(9 8) (lambda (i) (push i pads))))))
    (parachute:is eq nil reads) (parachute:is eq nil pads)
    (parachute:is equal '(1 2) (part03-list (sl:seq-first r)))
    (parachute:is equal '(1 0) reads) (parachute:is eq nil pads)
    (parachute:is equal '(3 9) (part03-list (sl:seq-first (sl:seq-rest r))))
    (parachute:is equal '(3 2 1 0) reads)
    (parachute:is equal '(0) pads)
    (parachute:is equal '((1 2) (3 9)) (part03-pieces r))
    (parachute:is equal '(0) pads))
  (let ((pads 0))
    (let ((pad (part03-stream '(99) (lambda (i) (declare (ignore i)) (incf pads) (error "unused pad")))))
      (parachute:is equal '((1 2)) (part03-pieces (sl:seq-partition 2 '(1 2) :pad pad)))
      (parachute:is = 0 pads)))
  ;; No length or positional access is supplied by this user seqable.
  (parachute:is equal '((1 2) (3 4))
                (part03-pieces (sl:seq-partition 2 (make-instance 'part03-source :items '(1 2 3 4)))))

  ;; Fail only after two padding elements have been accumulated.
  (let* ((attempts 0) (pads nil)
         (pad (part03-stream '(8 9 10 11)
                             (lambda (i)
                               (when (= i 2) (incf attempts)
                                 (when (= attempts 1) (error "retry partial pad")))
                               (push i pads))))
         (r (sl:seq-partition 4 '(1) :pad pad)))
    (parachute:fail (sl:seq-first r) simple-error)
    (parachute:is equal '(1 0) pads)
    (parachute:is equal '((1 8 9 10)) (part03-pieces r))
    (parachute:is equal '(2 1 0) pads)
    (parachute:is = 2 attempts)
    (parachute:is equal '((1 8 9 10)) (part03-pieces r))
    (parachute:is equal '(2 1 0) pads))
  (let* ((r (sl:seq-partition
             3 (part03-stream (loop for i below 20 collect i)
                              (lambda (i) (when (> i 3) (error "partition window sentinel"))))
             :step 1)))
    (parachute:is equal '(0 1 2) (part03-list (sl:seq-first r)))
    (parachute:is equal '(1 2 3) (part03-list (sl:seq-first (sl:seq-rest r))))))

(parachute:define-test seq-partition.extensions-and-validation
  (dolist (pad (list '(1) '(:incompatible) '(1 :unused)))
    (let* ((s (make-array 4 :element-type 'bit :initial-contents '(1 0 1 0) :fill-pointer 3))
           (pieces (part03-list (sl:seq-partition 2 s :pad pad))))
      (parachute:is = 2 (length pieces))
      (parachute:is equal (array-element-type s) (array-element-type (first pieces)))
      (parachute:is equal (if (eq (car pad) :incompatible) t (array-element-type s))
                    (array-element-type (second pieces)))
      (parachute:is equalp (vector 1 (car pad)) (second pieces))
      (parachute:false (eq (first pieces) s))))
  (let ((pieces (part03-list (sl:seq-partition 2 "abc" :pad '(7)))))
    (parachute:true (stringp (first pieces)))
    (parachute:is equal "ab" (first pieces))
    (parachute:is equalp #(#\c 7) (second pieces))
    (parachute:is eq t (array-element-type (second pieces))))
  (dolist (value '(-1 1/2 :bad))
    (parachute:fail (sl:seq-partition value '(1)) type-error)
    (parachute:fail (sl:seq-partition 1 '(1) :step value) type-error))
  (parachute:fail (sl:seq-partition 0 '(1)) program-error)
  (parachute:fail (sl:seq-partition 1 '(1) :step 0) program-error)
  (parachute:fail (sl:seq-partition 1 '(1) :pad 7) type-error)
  (parachute:fail (sl:seq-partition 1 '(1) :pad (sl:map-entry :k 1)) type-error)
  (let ((table (make-hash-table)))
    (setf (gethash :k table) 7)
    (dolist (source (list table (sl:dict :k 7) (sl:hash-set 7)))
      (let ((r (sl:seq-partition 1 source)))
        (parachute:true (sl:lazy-seq-p r))
        (parachute:true (if (or (hash-table-p source) (typep source 'sl:dict))
                            (sl:ordered-dict-p (sl:seq-first r))
                            (sl:lazy-seq-p (sl:seq-first r))))
        (parachute:is = 1 (length (part03-list (sl:seq-first r)))))))
  (let* ((*part03-collects* 0)
         (r (sl:seq-partition 2 (make-instance 'part03-collected :items '(1 2 3)) :pad t)))
    (parachute:is = 0 *part03-collects*)
    (parachute:true (typep (sl:seq-first r) 'part03-collected))
    (parachute:is equal '(1 2) (part03-items (sl:seq-first r))))
  (let* ((*part03-refusal* (make-condition 'simple-error))
         (r (sl:seq-partition 1 (make-instance 'part03-collected :items '(1)))))
    (parachute:fail (sl:seq-first r) simple-error))

  (let ((table (make-hash-table)))
    (setf (gethash 1 table) 10 (gethash 2 table) 20 (gethash 3 table) 30)
    (dolist (source (list table (sl:dict 1 10 2 20 3 30) (sl:hash-set 1 2 3)))
      (let* ((r (sl:seq-partition 2 source :pad t)) (pieces (part03-list r))
             (items (mapcan #'part03-list pieces)))
        (parachute:is equal '(2 1) (mapcar (lambda (p) (length (part03-list p))) pieces))
        (parachute:true
         (every (if (or (hash-table-p source) (typep source 'sl:dict))
                    #'sl:ordered-dict-p
                    #'sl:lazy-seq-p)
                pieces))
        (parachute:is = 3 (length items))
        (if (typep (first items) 'sl:map-entry)
            (parachute:is equal '((1 10) (2 20) (3 30))
                          (sort (mapcar (lambda (e) (list (sl:entry-key e) (sl:entry-value e))) items)
                                #'< :key #'first))
            (parachute:is equal '(1 2 3) (sort items #'<)))))))

(parachute:define-test seq-partition-by.representations-and-validation
  (dolist (type '(bit (unsigned-byte 8) t))
    (let* ((s (make-array 6 :element-type type :initial-contents '(1 1 0 0 1 0) :fill-pointer 5))
           (r (sl:seq-partition-by #'identity s :test #'eql))
           (pieces (part03-list r)))
      (parachute:true (sl:lazy-seq-p r))
      (parachute:is equalp '(#(1 1) #(0 0) #(1)) pieces)
      (dolist (p pieces)
        (parachute:is equal (array-element-type s) (array-element-type p))
        (parachute:false (eq s p)))))
  (parachute:is equal '((1 1.0) (2) (1))
                (part03-pieces (sl:seq-partition-by #'identity '(1 1.0 2 1))))
  (parachute:is equal '("aa" "bb" "a") (part03-list (sl:seq-partition-by #'identity "aabba")))
  (parachute:is eq nil (part03-list (sl:seq-partition-by #'identity nil)))
  (dolist (key '(:test-not :key :start))
    (parachute:fail (funcall #'sl:seq-partition-by #'identity '(1) key nil) program-error)))

(parachute:define-test seq-partition-by.forcing-and-key-caching
  (let* ((keys nil) (tests nil) (reads nil) (index -1)
         (r (sl:seq-partition-by
             (lambda (x) (push x keys) (cons x (incf index)))
             (part03-stream '(1 1 2 2 1) (lambda (i) (push i reads)))
             :test (lambda (a b)
                     (push (sort (list (cdr a) (cdr b)) #'<) tests)
                     (eql (car a) (car b))))))
    (parachute:is eq nil keys) (parachute:is eq nil tests) (parachute:is eq nil reads)
    (parachute:is equal '(1 1) (part03-list (sl:seq-first r)))
    (parachute:is equal '(2 1 1) keys)
    (parachute:is equal '(2 1 0) reads)
    (parachute:true (member '(0 1) tests :test #'equal))
    (parachute:true (member '(1 2) tests :test #'equal))
    (let ((saved (copy-list keys)))
      (parachute:is eq (sl:seq-first r) (sl:seq-first r))
      (parachute:is equal saved keys))
    (parachute:is equal '((1 1) (2 2) (1)) (part03-pieces r))
    (parachute:is equal '(1 2 2 1 1) keys)
    ;; TEST may repeat comparisons and its orientation is not prescribed.
    ;; Distinct key identities nevertheless require predecessor, not run-head.
    (parachute:true (every (lambda (edge) (= (second edge) (1+ (first edge)))) tests))
    (dolist (edge '((0 1) (1 2) (2 3) (3 4)))
      (parachute:true (member edge tests :test #'equal)))))

(parachute:define-test seq-partition-by.extensions-and-retry
  (let* ((*part03-collects* 0) (calls 0)
         (r (sl:seq-partition-by (lambda (x) (incf calls) x)
                                (make-instance 'part03-collected :items '(1 1 2)))))
    (parachute:is = 0 calls) (parachute:is = 0 *part03-collects*)
    (parachute:true (typep (sl:seq-first r) 'part03-collected))
    (parachute:is equal '(1 1) (part03-items (sl:seq-first r)))
    (parachute:is = 3 calls))
  (let ((attempts 0) (successful nil))
    (let ((r (sl:seq-partition-by
              (lambda (x)
                (when (= x 2) (incf attempts) (when (= attempts 1) (error "retry key")))
                (push x successful) x)
              (part03-stream '(1 2 3) (constantly nil)))))
      (parachute:fail (sl:seq-first r) simple-error)
      (parachute:is equal '((1) (2) (3)) (part03-pieces r))
      (parachute:is equal '(3 2 1) successful)
      (parachute:is = 2 attempts)))
  (dolist (source (list (sl:hash-set 7) (make-instance 'part03-source :items '(7))))
    (let ((r (sl:seq-partition-by #'identity source)))
      (parachute:true (sl:lazy-seq-p r))
      (parachute:true (sl:lazy-seq-p (sl:seq-first r)))
      (parachute:is equal '((7)) (part03-pieces r))))
  (parachute:fail (sl:seq-partition-by 7 '(1)) type-error)
  (parachute:fail (sl:seq-partition-by #'identity '(1) :test 7) type-error)

  ;; Pairwise comparison may repeat, but successful keys must not repeat.
  (let* ((keys nil) (fail-once t)
         (r (sl:seq-partition-by
             (lambda (x) (push x keys) x)
             (part03-stream '(1 1 2 2 3) (constantly nil))
             :test (lambda (a b)
                     (when (and fail-once (or (= a 2) (= b 2)))
                       (setf fail-once nil) (error "retry comparison"))
                     (= a b)))))
    (parachute:fail (sl:seq-first r) simple-error)
    (parachute:is equal '(2 1 1) keys)
    (parachute:is equal '((1 1) (2 2) (3)) (part03-pieces r))
    (parachute:is equal '(3 2 2 1 1) keys)
    (parachute:is equal '((1 1) (2 2) (3)) (part03-pieces r))
    (parachute:is = 5 (length keys)))
  (let ((table (make-hash-table)))
    (setf (gethash 1 table) 10 (gethash 2 table) 20 (gethash 3 table) 30)
    (dolist (source (list table (sl:dict 1 10 2 20 3 30) (sl:hash-set 1 2 3)))
      (let* ((seen nil)
             (r (sl:seq-partition-by (lambda (x) (push x seen) :one-run) source)))
        (parachute:is eq nil seen)
        (parachute:true (sl:lazy-seq-p r))
        (let* ((pieces (part03-list r)) (items (part03-list (first pieces))))
          (parachute:is = 1 (length pieces))
          (parachute:true
           (if (or (hash-table-p source) (typep source 'sl:dict))
               (sl:ordered-dict-p (first pieces))
               (sl:lazy-seq-p (first pieces))))
          (parachute:is equal (reverse seen) items)
          (if (typep (first items) 'sl:map-entry)
              (parachute:is equal '((1 10) (2 20) (3 30))
                            (sort (mapcar (lambda (e) (list (sl:entry-key e) (sl:entry-value e))) items)
                                  #'< :key #'first))
              (parachute:is equal '(1 2 3) (sort items #'<))))))))

(parachute:define-test seq-partition.keyword-validation
  (parachute:fail
   (sl:seq-partition 1 '(1) :allow-other-keys t :unsupported nil)
   program-error)
  (parachute:fail
   (sl:seq-partition-by #'identity '(1) :allow-other-keys t :unsupported nil)
   program-error))

;;;; Independent nested-result and delimiter oracles, Chapter 6.2.4.
(defun split03-list (source)
  (loop with view = source for i below 100 until (sl:seq-emptyp view)
        collect (sl:seq-first view) do (setf view (sl:seq-rest view))
        finally (unless (sl:seq-emptyp view)
                  (parachute:true nil "SPLIT03-LIST exceeded its finite fixture bound"))))
(defun split03-pieces (source) (mapcar #'split03-list (split03-list source)))
(defun split03-stream (items observer &optional (i 0))
  (sl:make-lazy-seq
   (lambda () (funcall observer i)
     (if items (sl:lazy-cons (car items) (split03-stream (cdr items) observer (1+ i))) nil))))
(defclass split03-source ()
  ((items :initarg :items :reader split03-items)
   (observations :initarg :observations :initform (list 0)
                 :accessor split03-observations)))
(defun split03-observation-count (source)
  (car (split03-observations source)))
(defclass split03-collected (split03-source) ())
(defmethod sl:seqablep ((x split03-source)) t)
(defmethod sl:seq-emptyp ((x split03-source)) (null (split03-items x)))
(defmethod sl:seq-first ((x split03-source))
  (incf (car (split03-observations x)))
  (car (split03-items x)))
(defmethod sl:seq-rest ((x split03-source))
  (incf (car (split03-observations x)))
  (make-instance 'split03-source
                 :items (cdr (split03-items x))
                 :observations (split03-observations x)))
(defclass split03-collector ()
  ((items :initform nil :accessor split03-acc) (result :accessor split03-result)))
(defvar *split03-collects* 0)
(defvar *split03-refusal* nil)
(defvar *split03-hook* nil)
(defun split03-event (phase)
  (when *split03-hook* (funcall *split03-hook* phase)))
(defmethod sl:make-collector-for ((x split03-collected) &key)
  (split03-event :create)
  (incf *split03-collects*) (make-instance 'split03-collector))
(defmethod sl:collector-accumulate ((c split03-collector) x)
  (split03-event :accumulate)
  (when *split03-refusal* (error *split03-refusal*))
  (push x (split03-acc c)) c)
(defmethod sl:collector-result ((c split03-collector))
  (if (slot-boundp c 'result) (split03-result c)
      (progn
        (split03-event :result)
        (setf (split03-result c)
              (make-instance 'split03-collected :items (reverse (split03-acc c)))))))

(parachute:define-test seq-split.representations-and-validation
  (let* ((s (copy-seq "a,,b,")) (r (sl:seq-split s :delimiter #\, :test #'char=)))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is equal '("a" "" "b" "") (split03-list r))
    (parachute:is equal "a,,b," s))
  (parachute:is equal '("" "ba") (split03-list (sl:seq-split "ababa" :delimiter "aba")))
  (parachute:is equal '("" "" "a") (split03-list (sl:seq-split "aaaaa" :delimiter "aa")))
  (parachute:is equal '("") (split03-list (sl:seq-split "" :delimiter ",")))
  (parachute:is equal '((a) nil (b) nil)
                (split03-list (sl:seq-split '(a :d :d b :d) :delimiter :d)))
  (parachute:is equal '(nil (2)) (split03-list (sl:seq-split '(1.0 2) :delimiter 1)))
  (parachute:fail (sl:seq-split '(1)) program-error)
  (parachute:fail (sl:seq-split '(1) :delimiter 1 :predicate #'oddp) program-error)
  (parachute:fail (sl:seq-split '(1) :predicate #'oddp :test #'eql) program-error)
  (dolist (key '(:test-not :key :start :end))
    (parachute:fail (apply #'sl:seq-split '(1) :delimiter 1 (list key nil)) program-error)))

(parachute:define-test seq-split.forcing-and-delimiter-errors
  (let* ((events nil)
         (delimiter (split03-stream '(:d) (lambda (i) (push (list :d i) events))))
         (source (split03-stream '(1 :d 2) (lambda (i) (push (list :s i) events))))
         (r (sl:seq-split source :delimiter delimiter
                         :test (lambda (a b) (push (list :test a b) events) (eql a b)))))
    (parachute:is eq nil events)
    (parachute:is equal '(1) (split03-list (sl:seq-first r)))
    (parachute:is equal '((:d 0) (:d 1)) (subseq (reverse events) 0 2))
    (parachute:false (member '(:s 2) events :test #'equal))
    (let ((snapshot (copy-list events)))
      (parachute:is eq (sl:seq-first r) (sl:seq-first r))
      (parachute:is equal snapshot events))
    (parachute:is equal '((1) (2)) (split03-pieces r)))
  (parachute:fail (sl:seq-split '(1) :delimiter nil) simple-error)
  (dolist (empty (list "" #() (split03-stream nil (constantly nil))))
    (let ((r (sl:seq-split '(1) :delimiter empty)))
      (parachute:true (sl:lazy-seq-p r))
      (parachute:fail (sl:seq-first r) simple-error)))
  ;; Bounded escape stands in for an unbounded delimiter, without a hang.
  (let ((reads 0)
        (delimiter (split03-stream '(1 2 3 4) (lambda (i) (when (= i 3) (error "delimiter sentinel"))))))
    (let ((r (sl:seq-split (split03-stream '(1) (lambda (i) (declare (ignore i)) (incf reads)))
                          :delimiter delimiter)))
      (parachute:fail (sl:seq-first r) simple-error)
      (parachute:is = 0 reads))))

(parachute:define-test seq-split.extensions-and-retry
  (dolist (type '(bit (unsigned-byte 8) t))
    (let* ((s (make-array 5 :element-type type :initial-contents '(1 0 0 1 0) :fill-pointer 4))
           (pieces (split03-list (sl:seq-split s :delimiter 0))))
      (parachute:is equalp '(#(1) #() #(1)) pieces)
      (dolist (p pieces)
        (parachute:is equal (array-element-type s) (array-element-type p))
        (parachute:false (eq s p)))))
  (let* ((source (copy-seq "abc")) (p (sl:seq-first (sl:seq-split source :delimiter ","))))
    (parachute:is equal source p) (parachute:false (eq source p)))
  (let ((calls nil) (attempts 0))
    (let ((r (sl:seq-split '(1 0 2) :predicate
                           (lambda (x) (incf attempts)
                             (when (= attempts 1) (error "retry boundary"))
                             (push x calls) (zerop x)))))
      (parachute:is eq nil calls)
      (parachute:fail (sl:seq-first r) simple-error)
      (parachute:is equal '(1) (sl:seq-first r))
      (parachute:is equal '(0 1) calls)
      (parachute:is equal '((1) (2)) (split03-pieces r))
      (parachute:is equal '(2 0 1) calls)))
  ;; A failed Collector reconstruction must leave the retained piece retryable.
  (dolist (phase '(:create :accumulate :result))
    (let* ((attempts 0) (condition (make-condition 'simple-error))
           (source (make-instance 'split03-collected :items '(1 0 2)))
           (*split03-hook* (lambda (event)
                              (when (eq event phase)
                                (incf attempts)
                                (when (= attempts 1) (error condition)))))
           (r (sl:seq-split source :delimiter 0)))
      (parachute:is eq condition
                    (handler-case (sl:seq-first r) (simple-error (c) c)))
      (parachute:is = 1 attempts)
      (let ((observations (split03-observation-count source)))
        (parachute:is equal '(1) (split03-items (sl:seq-first r)))
        ;; Retried reconstruction reads only the retained prefix, not SOURCE.
        (parachute:is = observations (split03-observation-count source)))
      (parachute:is equal '((1) (2)) (split03-pieces r))
      (parachute:is = 3 attempts)))
  (let ((r (sl:seq-split (sl:hash-set 1) :predicate (constantly nil))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:true (sl:lazy-seq-p (sl:seq-first r)))
    (parachute:is equal '((1)) (split03-pieces r)))
  (let* ((*split03-collects* 0)
         (r (sl:seq-split (make-instance 'split03-collected :items '(1 0 2)) :delimiter 0)))
    (parachute:is = 0 *split03-collects*)
    (parachute:true (typep (sl:seq-first r) 'split03-collected))
    (parachute:is equal '(1) (split03-items (sl:seq-first r))))

  (let ((r (sl:seq-split (make-instance 'split03-source :items '(1 0 2)) :delimiter 0)))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:true (sl:lazy-seq-p (sl:seq-first r)))
    (parachute:is equal '((1) (2)) (split03-pieces r))))

(parachute:define-test seq-split-at.representations-and-validation
  (dolist (n '(0 2 20))
    (let* ((s (make-array 4 :element-type '(unsigned-byte 8)
                           :initial-contents '(1 2 3 99) :fill-pointer 3))
           (pair (sl:seq-split-at n s))
           (pieces (coerce pair 'list)))
      (parachute:true (vectorp pair))
      (parachute:is eq t (array-element-type pair))
      (parachute:is equal (list (subseq '(1 2 3) 0 (min n 3))
                               (subseq '(1 2 3) (min n 3)))
                    (mapcar #'split03-list pieces))
      (dolist (p pieces)
        (parachute:is equal (array-element-type s) (array-element-type p))
        (parachute:false (eq s p)))
      (parachute:false (eq pair s))))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (funcall #'sl:seq-split-at 1 '(1) key nil) program-error))
  (split04-empty-checks :at))

(parachute:define-test seq-split-at.forcing-and-observation
  (let* ((forces nil)
         (r (sl:seq-split-at 2 (split03-stream '(1 2 3 4) (lambda (i) (push i forces))))))
    (parachute:is eq nil forces)
    (parachute:true (sl:lazy-seq-p r))
    (let* ((prefix (sl:seq-first r))
           (suffix (sl:seq-first (sl:seq-rest r))))
      ;; Consume suffix before prefix to detect separate traversals/lost buffer.
      (parachute:is equal '(3 4) (split03-list suffix))
      (parachute:is equal '(1 2) (split03-list prefix))
      (parachute:is equal '(4 3 2 1 0) forces)
      (parachute:is equal '(1 2) (split03-list prefix))
      (parachute:is = 5 (length forces))))
  (parachute:is equal '(nil (1 2)) (sl:seq-split-at 0 '(1 2)))
  (let* ((s (list 1 2)) (pair (sl:seq-split-at 0 s)))
    (parachute:false (eq s (second pair))))

  ;; Complete bounded prefix must not pre-scan the arbitrarily long suffix.
  (let ((r (sl:seq-split-at
            2 (split03-stream (loop for i below 20 collect i)
                              (lambda (i) (when (> i 1) (error "split prefix sentinel")))))))
    (parachute:is equal '(0 1) (split03-list (sl:seq-first r))))

  (split04-observation-checks :at))

(parachute:define-test seq-split-at.extensions-and-validation
  (parachute:is equal '((1) (2 3)) (sl:seq-split-at 1 '(1 2 3)))
  (let* ((s (copy-seq "abc")) (pair (sl:seq-split-at 0 s)))
    (parachute:true (vectorp pair)) (parachute:false (stringp pair))
    (parachute:is equalp #("" "abc") pair)
    (parachute:false (eq s (aref pair 1))))
  (dolist (n '(-1 1/2 :bad))
    (parachute:fail (sl:seq-split-at n '(1)) type-error))
  (let ((table (make-hash-table)))
    (setf (gethash :key table) 7)
    (dolist (source (list table (sl:dict :key 7) (sl:hash-set 7)))
      (let* ((r (sl:seq-split-at 0 source)) (pieces (split03-list r))
             (piece (second pieces)))
        (parachute:true (sl:lazy-seq-p r))
        (if (typep source 'sl:hash-set)
            (parachute:is eq nil (first pieces))
            (progn
              (parachute:true (sl:ordered-dict-p (first pieces)))
              (parachute:is = 0 (sl:dict-size (first pieces)))
              (parachute:true (every (lambda (entry) (typep entry 'sl:map-entry))
                                     (split03-list piece)))))
        (parachute:true (if (typep source 'sl:hash-set)
                            (sl:lazy-seq-p piece)
                            (sl:ordered-dict-p piece)))
        (parachute:is = 1 (length (split03-list piece))))))
  (parachute:fail (sl:seq-split-at 1 (sl:map-entry :k 7)) type-error)
  (split04-refusal-checks :at)
  (split04-count-validation-checks))

(parachute:define-test seq-split-with.representations-and-validation
  (let* ((s (make-array 5 :element-type '(unsigned-byte 8)
                         :initial-contents '(1 3 4 5 99) :fill-pointer 4))
         (r (sl:seq-split-with #'oddp s)))
    (parachute:is equalp #(#(1 3) #(4 5)) r)
    (parachute:is eq t (array-element-type r))
    (dolist (p (coerce r 'list))
      (parachute:is equal (array-element-type s) (array-element-type p))
      (parachute:false (eq s p)))
    (parachute:is equalp #(1 3 4 5) s))
  (parachute:is equal '((1 3) (4 5)) (sl:seq-split-with #'oddp '(1 3 4 5)))
  (parachute:is equalp #("ab" "12") (sl:seq-split-with #'alpha-char-p "ab12"))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (funcall #'sl:seq-split-with #'oddp '(1) key nil) program-error))
  (split04-empty-checks :with))

(parachute:define-test seq-split-with.forcing-and-retry
  (dolist (source (list '(1 3 4 5) #(1 3 4 5)))
    (let ((calls nil))
      (let ((r (sl:seq-split-with (lambda (x) (push x calls) (oddp x)) source)))
        (parachute:is equal '(4 3 1) calls)
        (parachute:is equal '((1 3) (4 5)) (split03-pieces r))
        (parachute:is equal '(4 3 1) calls))))
  (let* ((calls nil) (forces nil)
         (r (sl:seq-split-with (lambda (x) (push x calls) (oddp x))
                              (split03-stream '(1 3 4 5) (lambda (i) (push i forces))))))
    (parachute:is eq nil calls) (parachute:is eq nil forces)
    (parachute:is equal '((1 3) (4 5)) (split03-pieces r))
    (parachute:is equal '(4 3 1) calls)
    (parachute:is equal '(4 3 2 1 0) forces))

  ;; Retry suffix-first after two successful prefix predicates; retain buffer.
  (let* ((successful nil) (attempts 0)
         (r (sl:seq-split-with
             (lambda (x)
               (when (= x 4) (incf attempts) (when (= attempts 1) (error "retry split-with")))
               (push x successful) (oddp x))
             (split03-stream '(1 3 4 5) (constantly nil)))))
    (parachute:is eq nil successful)
    (parachute:fail (split03-list (sl:seq-first (sl:seq-rest r))) simple-error)
    (parachute:is equal '(3 1) successful)
    (parachute:is equal '(4 5) (split03-list (sl:seq-first (sl:seq-rest r))))
    (parachute:is equal '(1 3) (split03-list (sl:seq-first r)))
    (parachute:is equal '(4 3 1) successful)
    (parachute:is = 2 attempts)
    (parachute:is equal '((1 3) (4 5)) (split03-pieces r))
    (parachute:is equal '(4 3 1) successful))

  (split04-observation-checks :with)
  (split04-predicate-retry-checks))

(parachute:define-test seq-split-with.extensions-and-validation
  (parachute:is equal '(nil (2 3)) (sl:seq-split-with #'oddp '(2 3)))
  (parachute:is equal '((1 3) nil) (sl:seq-split-with #'oddp '(1 3)))
  (parachute:is equalp #("" "abc") (sl:seq-split-with (constantly nil) "abc"))
  (parachute:is equalp #("abc" "") (sl:seq-split-with (constantly t) "abc"))
  (let* ((s (make-array 2 :element-type 'bit :initial-contents '(1 0)))
         (r (sl:seq-split-with (constantly nil) s)))
    (parachute:is = 0 (length (aref r 0)))
    (parachute:is equal (array-element-type s) (array-element-type (aref r 0)))
    (parachute:is equal (array-element-type s) (array-element-type (aref r 1)))
    (parachute:false (eq s (aref r 1))))
  (let ((r (sl:seq-split-with #'oddp (make-instance 'split03-source :items '(1 2)))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:true (every #'sl:lazy-seq-p (split03-list r)))
    (parachute:is equal '((1) (2)) (split03-pieces r)))
  (let ((r (sl:seq-split-with (constantly nil) (sl:hash-set 7))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is eq nil (sl:seq-first r))
    (parachute:is equal '(nil (7)) (split03-pieces r)))
  (parachute:fail (sl:seq-split-with 7 '(1)) type-error)

  (let ((table (make-hash-table)))
    (setf (gethash 1 table) 10 (gethash 2 table) 20 (gethash 3 table) 30)
    (dolist (source (list table (sl:dict 1 10 2 20 3 30) (sl:hash-set 1 2 3)))
      (let* ((seen nil)
             (r (sl:seq-split-with (lambda (x) (push x seen) (< (length seen) 2)) source)))
        (parachute:is eq nil seen)
        (parachute:true (sl:lazy-seq-p r))
        (let* ((pieces (split03-pieces r)) (items (append (first pieces) (second pieces))))
          (parachute:is = 1 (length (first pieces)))
          (parachute:is = 2 (length (second pieces)))
          (parachute:is equal (reverse seen) (subseq items 0 2))
          (if (typep (first items) 'sl:map-entry)
              (parachute:is equal '((1 10) (2 20) (3 30))
                            (sort (mapcar (lambda (e) (list (sl:entry-key e) (sl:entry-value e))) items)
                                  #'< :key #'first))
              (parachute:is equal '(1 2 3) (sort items #'<)))))))

  (split04-refusal-checks :with))

;;;; Approved split-pair ruling: ordinary element-only reconstruction, never
;;;; an outer Collector. Source observations are lazy-node effects, not a
;;;; prescribed number or order of the four user seq primitive calls.
(defclass split04-source ()
  ((view :initarg :view :reader split04-view)
   (metadata :initarg :metadata :reader split04-metadata)))
(defmethod sl:seqablep ((s split04-source)) t)
(defmethod sl:seq-emptyp ((s split04-source)) (sl:seq-emptyp (split04-view s)))
(defmethod sl:seq-first ((s split04-source)) (sl:seq-first (split04-view s)))
(defmethod sl:seq-rest ((s split04-source))
  (unless (sl:seq-emptyp (split04-view s))
    (make-instance 'split04-source :view (sl:seq-rest (split04-view s))
                   :metadata (split04-metadata s))))
(defclass split04-collector ()
  ((source :initarg :source :reader split04-origin)
   (items :initform nil :accessor split04-acc)
   (result :accessor split04-result)))
(defvar *split04-events* nil)
(defvar *split04-hook* nil)
(define-condition split04-refusal (error) ())
(defun split04-event (phase value)
  (push (list phase value) *split04-events*)
  (when *split04-hook* (funcall *split04-hook* phase value)))
(defmethod sl:make-collector-for ((s split04-source) &rest options &key &allow-other-keys)
  (split04-event :create (list s options))
  (make-instance 'split04-collector :source s))
(defmethod sl:collector-accumulate ((c split04-collector) value)
  (split04-event :accumulate value)
  ;; A source of integers is intentionally incapable of containing pieces.
  (unless (integerp value) (error 'split04-refusal))
  (push value (split04-acc c)) c)
(defmethod sl:collector-result ((c split04-collector))
  (if (slot-boundp c 'result) (split04-result c)
      (progn
        (split04-event :result (reverse (split04-acc c)))
        (setf (split04-result c)
              (make-instance 'split04-source
                             :view (reverse (split04-acc c))
                             :metadata (split04-metadata (split04-origin c)))))))
(defun split04-count (phase) (count phase *split04-events* :key #'first))
(defun split04-pair (kind source predicate &optional (n 2))
  (ecase kind
    (:at (sl:seq-split-at n source))
    (:with (sl:seq-split-with predicate source))))
(defun split04-observation-checks (kind)
  ;; Each observation starts with a fresh unresolved first node. REST must
  ;; resolve that node, but must not resolve the returned suffix node.
  (dolist (observe '(sl:seq-first sl:seq-emptyp sl:seq-rest))
    (let* ((forces nil) (calls nil) (*split04-events* nil)
           (metadata (list :private-configuration))
           (s (make-instance 'split04-source :metadata metadata
                            :view (split03-stream '(1 3 4 5) (lambda (i) (push i forces)))))
           (r (split04-pair kind s (lambda (x) (push x calls) (oddp x)))))
      (parachute:true (sl:lazy-seq-p r))
      (parachute:is eq nil forces)
      (parachute:is eq nil calls)
      (parachute:is eq nil *split04-events*)
      (funcall observe r)
      (parachute:is = 1 (split04-count :create))
      (parachute:is = 2 (split04-count :accumulate))
      (parachute:is = 1 (split04-count :result))
      (parachute:is equal (if (eq kind :at) '(1 0) '(2 1 0)) forces)
      (parachute:is equal (if (eq kind :at) nil '(4 3 1)) calls)
      (let* ((prefix (sl:seq-first r)) (tail (sl:seq-rest r))
             (snapshot (copy-tree *split04-events*)))
        (parachute:true (typep prefix 'split04-source))
        (parachute:is eq metadata (split04-metadata prefix))
        (parachute:is equal '(1 3) (split03-list prefix))
        (parachute:is eq prefix (sl:seq-first r))
        (parachute:false (sl:seq-emptyp r))
        (parachute:is eq tail (sl:seq-rest r))
        (parachute:is equal snapshot *split04-events*)
        (parachute:false (sl:seq-emptyp tail))
        (let ((suffix (sl:seq-first tail)))
          (parachute:true (typep suffix 'split04-source))
          (parachute:is eq metadata (split04-metadata suffix))
          (parachute:is equal '(4 5) (split03-list suffix))
          (parachute:is = 2 (split04-count :create))
          (parachute:is = 4 (split04-count :accumulate))
          (parachute:is = 2 (split04-count :result))
          (parachute:is equal '(4 3 2 1 0) forces)
          (parachute:is equal (if (eq kind :at) nil '(4 3 1)) calls)
          (let ((events (copy-tree *split04-events*)))
            (dotimes (i 2)
              (parachute:is eq suffix (sl:seq-first (sl:seq-rest r)))
              (parachute:is eq prefix (sl:seq-first r))
              (parachute:is equal '((1 3) (4 5)) (split03-pieces r))
              (parachute:true (sl:seq-emptyp (sl:seq-rest tail))))
            (parachute:is equal events *split04-events*)
            (parachute:is equal '(4 3 2 1 0) forces)))))))
(defun split04-empty-checks (kind)
  (dolist (fixture (if (eq kind :at)
                      '((nil 0 nil nil) (nil 9 nil nil)
                        ((1 3 4) 0 nil (1 3 4)) ((1 3 4) 3 (1 3 4) nil)
                        ((1 3 4) 20 (1 3 4) nil))
                      '((nil 0 nil nil) ((2 3) 0 nil (2 3))
                        ((1 3) 0 (1 3) nil))))
    (destructuring-bind (items n expected-prefix expected-suffix) fixture
      (let* ((forces nil) (calls nil) (*split04-events* nil)
             (metadata (list :empty-metadata))
             (s (make-instance 'split04-source :metadata metadata
                              :view (split03-stream items (lambda (i) (push i forces)))))
             (r (split04-pair kind s (lambda (x) (push x calls) (oddp x)) n)))
        (parachute:is eq nil forces)
        (parachute:is eq nil calls)
        (parachute:is eq nil *split04-events*)
        ;; Suffix-first through the public protocol necessarily resolves prefix.
        (let* ((tail (sl:seq-rest r)) (prefix (sl:seq-first r)))
          (parachute:is = 1 (split04-count :create))
          (parachute:is = 1 (split04-count :result))
          (when (and (eq kind :at) (zerop n)) (parachute:is eq nil forces))
          (let ((suffix (sl:seq-first tail)))
            (dolist (piece (list prefix suffix))
              (parachute:true (typep piece 'split04-source))
              (parachute:is eq metadata (split04-metadata piece)))
            (parachute:is equal expected-prefix (split03-list prefix))
            (parachute:is equal expected-suffix (split03-list suffix))
            (parachute:is eq prefix (sl:seq-first r))
            (parachute:is eq suffix (sl:seq-first tail))
            (parachute:is = 2 (split04-count :create))
            (parachute:is = 2 (split04-count :result))
            (parachute:is = (length items) (split04-count :accumulate))
            (parachute:is = (1+ (length items)) (length forces))
            (parachute:true (sl:seq-emptyp (sl:seq-rest tail)))))))))
(defun split04-refusal-checks (kind)
  (dolist (position '(:prefix :suffix))
    (dolist (phase '(:create :accumulate :result))
      (let* ((forces nil) (calls nil) (*split04-events* nil)
             (condition (make-condition 'split04-refusal)) (attempts 0)
             (s (make-instance 'split04-source :metadata :retry
                              :view (split03-stream '(1 3 4 5) (lambda (i) (push i forces)))))
             (r (split04-pair kind s (lambda (x) (push x calls) (oddp x))))
             ;; Retain the real suffix node, never an imagined random-access node.
             (node (if (eq position :prefix) r (sl:seq-rest r)))
             (prefix (when (eq position :suffix) (sl:seq-first r)))
             (*split04-hook* (lambda (event value)
                              (declare (ignore value))
                              (when (eq event phase)
                                (incf attempts)
                                (when (<= attempts 2) (error condition))))))
        (dotimes (i 2)
          (parachute:is eq condition
                        (handler-case (sl:seq-first node) (split04-refusal (c) c)))
          (parachute:is = (1+ i) attempts)
          (when prefix (parachute:is eq prefix (sl:seq-first r))))
        (let ((piece (sl:seq-first node)))
          (parachute:true (typep piece 'split04-source))
          (parachute:is equal (if (eq position :prefix) '(1 3) '(4 5))
                        (split03-list piece))
          ;; ACCUMULATE can be called again for later elements after recovery.
          (parachute:is = (if (eq phase :accumulate) 4 3) attempts)
          (let ((snapshot (copy-tree *split04-events*)) (reads (copy-list forces))
                (predicates (copy-list calls)))
            (parachute:is eq piece (sl:seq-first node))
            (parachute:false (sl:seq-emptyp node))
            (parachute:is equal snapshot *split04-events*)
            (parachute:is equal reads forces)
            (parachute:is equal predicates calls)))
        (let ((*split04-hook* nil))
          (parachute:is equal '((1 3) (4 5)) (split03-pieces r)))
        (parachute:is equal '(4 3 2 1 0) forces)
        (parachute:is equal (if (eq kind :at) nil '(4 3 1)) calls)))))

(defun split04-predicate-retry-checks ()
  (let* ((forces nil) (successful nil) (attempts 0) (*split04-events* nil)
         (condition (make-condition 'split04-refusal))
         (s (make-instance 'split04-source :metadata :predicate-retry
                          :view (split03-stream '(1 3 4 5) (lambda (i) (push i forces)))))
         (r (sl:seq-split-with
             (lambda (x)
               (when (= x 4)
                 (incf attempts)
                 (when (<= attempts 2) (error condition)))
               (push x successful) (oddp x)) s)))
    (parachute:is eq nil forces)
    (parachute:is eq nil successful)
    (parachute:is eq nil *split04-events*)
    (dotimes (i 2)
      ;; Public suffix-first access first forces the prefix position.
      (parachute:is eq condition
                    (handler-case (sl:seq-first (sl:seq-rest r))
                      (split04-refusal (c) c)))
      (parachute:is = (1+ i) attempts)
      (parachute:is equal '(3 1) successful)
      (parachute:is equal '(2 1 0) forces))
    (let* ((tail (sl:seq-rest r)) (prefix (sl:seq-first r)))
      (parachute:is equal '(1 3) (split03-list prefix))
      (parachute:is = 3 attempts)
      (parachute:is equal '(4 3 1) successful)
      (parachute:is equal '(2 1 0) forces)
      (let ((suffix (sl:seq-first tail)))
        (parachute:is equal '(4 5) (split03-list suffix))
        (parachute:is eq prefix (sl:seq-first r))
        (parachute:is eq suffix (sl:seq-first tail))
        (parachute:is = 3 attempts)
        (parachute:is equal '(4 3 1) successful)
        (parachute:is equal '(4 3 2 1 0) forces)))))
(defun split04-count-validation-checks ()
  (dolist (n '(-1 1/2 :bad))
    (let* ((forces nil) (*split04-events* nil)
           (s (make-instance 'split04-source :metadata :invalid-count
                            :view (split03-stream '(1) (lambda (i) (push i forces))))))
      (parachute:fail (sl:seq-split-at n s) type-error)
      (parachute:is eq nil forces)
      (parachute:is eq nil *split04-events*))))

;;;; Independent preorder and bounded-lookahead expectations, Chapter 6.2.4.
(defun tree03-list (source)
  (loop with view = source for i below 100 until (sl:seq-emptyp view)
        collect (sl:seq-first view) do (setf view (sl:seq-rest view))
        finally (unless (sl:seq-emptyp view)
                  (parachute:true nil "TREE03-LIST exceeded its finite fixture bound"))))
(defun tree03-prefix (source n)
  (loop with view = source for i below n collect (sl:seq-first view)
        do (when (< (1+ i) n) (setf view (sl:seq-rest view)))))
(defun tree03-stream (items observer &optional (i 0))
  (sl:make-lazy-seq
   (lambda () (funcall observer i)
     (if items (sl:lazy-cons (car items) (tree03-stream (cdr items) observer (1+ i))) nil))))
(defclass tree03-source () ((items :initarg :items :reader tree03-items)))
(defclass tree03-collected (tree03-source) ())
(defmethod sl:seqablep ((x tree03-source)) t)
(defmethod sl:seq-emptyp ((x tree03-source)) (null (tree03-items x)))
(defmethod sl:seq-first ((x tree03-source)) (car (tree03-items x)))
(defmethod sl:seq-rest ((x tree03-source)) (cdr (tree03-items x)))
(defclass tree03-collector ()
  ((items :initform nil :accessor tree03-acc) (result :accessor tree03-result)))
(defvar *tree03-collects* 0)
(defmethod sl:make-collector-for ((x tree03-collected) &key)
  (incf *tree03-collects*) (make-instance 'tree03-collector))
(defmethod sl:collector-accumulate ((c tree03-collector) x) (push x (tree03-acc c)) c)
(defmethod sl:collector-result ((c tree03-collector))
  (if (slot-boundp c 'result) (tree03-result c)
      (setf (tree03-result c)
            (make-instance 'tree03-collected :items (reverse (tree03-acc c))))))

(parachute:define-test seq-tree-seq.preorder-and-validation
  (let* ((root (list (list 1) 2)) (branches nil) (children nil)
         (r (sl:seq-tree-seq
             (lambda (x) (push x branches) (consp x))
             (lambda (x) (push x children) x) root)))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is eq nil branches) (parachute:is eq nil children)
    (parachute:is eq root (sl:seq-first r))
    (parachute:is equal '(((1) 2) (1) 1 2) (tree03-list r))
    (parachute:is equal '(((1) 2) (1) 1 2) (reverse branches))
    (parachute:is equal '(((1) 2) (1)) (reverse children))
    (parachute:is = 4 (length branches))
    (parachute:is = 2 (length children)))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (funcall #'sl:seq-tree-seq #'consp #'identity nil key nil) program-error)))

(parachute:define-test seq-tree-seq.forcing-and-lookahead
  (let* ((events nil)
         (r (sl:seq-tree-seq
             (lambda (x) (push (list :branch x) events) (member x '(:root :left)))
             (lambda (x)
               (push (list :children x) events)
               (ecase x
                 (:root (tree03-stream '(:left :right) (lambda (i) (push (list :root-child i) events))))
                 (:left (tree03-stream '(:leaf) (lambda (i) (push (list :left-child i) events))))))
             :root)))
    (parachute:is eq nil events)
    (parachute:is equal '(:root :left :leaf) (tree03-prefix r 3))
    (parachute:false (member '(:root-child 1) events :test #'equal))
    (parachute:false (member '(:children :leaf) events :test #'equal))
    (parachute:is equal '(:root :left :leaf :right) (tree03-list r))
    (parachute:is equal '((:children :root) (:children :left))
                  (remove-if-not (lambda (x) (eq (car x) :children)) (reverse events)))
    (parachute:is equal '((:branch :root) (:branch :left) (:branch :leaf) (:branch :right))
                  (remove-if-not (lambda (x) (eq (car x) :branch)) (reverse events))))
  ;; Finite chain with an explicit sentinel: pre-scanning cannot hang.
  (let ((children 0))
    (let ((r (sl:seq-tree-seq
              (lambda (x) (when (> x 5) (error "tree overforce")) t)
              (lambda (x) (incf children) (list (1+ x))) 0)))
      (parachute:is equal '(0 1 2 3) (tree03-prefix r 4))
      ;; A consumer may test the emitted node itself while forcing it, but
      ;; must not expand any later node. Root-to-3 needs three expansions.
      (parachute:true (<= 3 children 4)))))

(parachute:define-test seq-tree-seq.leaves-and-retry
  (dolist (root (list 7 nil (sl:map-entry :k 1) #() (sl:dict) (sl:hash-set)))
    (let ((r (sl:seq-tree-seq (constantly nil)
                            (lambda (x) (declare (ignore x)) (error "leaf children")) root)))
      (parachute:true (sl:lazy-seq-p r))
      (parachute:is eq root (sl:seq-first r))
      (parachute:is = 1 (length (tree03-list r)))))
  (let ((r (sl:seq-tree-seq (constantly t) (constantly 7) :root)))
    ;; Exact choice of first/rest forcing point is not fixed by the entry.
    (parachute:fail (tree03-list r) type-error))
  (let ((attempts 0))
    (let ((r (sl:seq-tree-seq
              (lambda (x) (eq x :root))
              (lambda (x) (declare (ignore x)) (incf attempts)
                (if (= attempts 1) (error "retry children") '(:leaf))) :root)))
      (parachute:fail (tree03-list r) simple-error)
      (parachute:is equal '(:root :leaf) (tree03-list r))
      (parachute:is = 2 attempts)
      (parachute:is equal '(:root :leaf) (tree03-list r))
      (parachute:is = 2 attempts)))
  (parachute:fail (sl:seq-tree-seq 7 #'identity :root) type-error)
  (parachute:fail (sl:seq-tree-seq #'consp 7 :root) type-error)

  (let* ((branches nil) (attempts 0)
         (r (sl:seq-tree-seq
             (lambda (x) (push x branches) (eq x :root))
             (lambda (x) (declare (ignore x)) (incf attempts)
               (when (= attempts 1) (error "retry children after branch"))
               '(:a :b)) :root)))
    (parachute:fail (tree03-list r) simple-error)
    (parachute:is equal '(:root) branches)
    (parachute:is equal '(:root :a :b) (tree03-list r))
    (parachute:is equal '(:b :a :root) branches)
    (parachute:is = 2 attempts)
    (parachute:is equal '(:root :a :b) (tree03-list r))
    (parachute:is equal '(:b :a :root) branches))
  (dolist (class '(tree03-source tree03-collected))
    (let* ((*tree03-collects* 0)
           (children (make-instance class :items '(:a :b)))
           (r (sl:seq-tree-seq (lambda (x) (eq x :root)) (constantly children) :root)))
      (parachute:true (sl:lazy-seq-p r))
      (parachute:is equal '(:root :a :b) (tree03-list r))
      (parachute:is = 0 *tree03-collects*))))

(parachute:define-test seq-drop-last.representations-and-validation
  (dolist (type '(bit (unsigned-byte 8) t))
    (let ((s (make-array 4 :element-type type :initial-contents '(1 0 1 0))))
      (dolist (n '(0 2 4 20))
        (let ((r (sl:seq-drop-last n s)))
          (parachute:true (vectorp r))
          (parachute:is equalp (subseq s 0 (max 0 (- 4 n))) r)
          (parachute:is equal (array-element-type s) (array-element-type r))
          (parachute:false (eq r s))))))
  (let* ((s (copy-seq "abcd")) (r (sl:seq-drop-last 0 s)))
    (parachute:is equal s r) (parachute:false (eq s r)))
  (parachute:is equal "ab" (sl:seq-drop-last 2 "abcd"))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (funcall #'sl:seq-drop-last 1 '(1 2) key nil) program-error)))

(parachute:define-test seq-drop-last.forcing
  (let* ((reads nil)
         (r (sl:seq-drop-last 2 (tree03-stream '(1 2 3 4 5) (lambda (i) (push i reads))))))
    (parachute:is eq nil reads)
    (parachute:is = 1 (sl:seq-first r))
    (parachute:is equal '(2 1 0) reads)
    (parachute:is = 1 (sl:seq-first r))
    (parachute:is equal '(2 1 0) reads)
    (parachute:is equal '(1 2) (tree03-prefix r 2))
    (parachute:is equal '(3 2 1 0) reads)
    (parachute:is equal '(1 2 3) (tree03-list r))
    (parachute:is equal '(5 4 3 2 1 0) reads))
  (let ((r (sl:seq-drop-last 2
                           (tree03-stream (loop for i below 20 collect i)
                                          (lambda (i) (when (> i 4) (error "overforce")))))))
    (parachute:is equal '(0 1 2) (tree03-prefix r 3)))
  (let ((r (sl:seq-drop-last 0 '(1 2))))
    (parachute:true (sl:lazy-seq-p r)) (parachute:is equal '(1 2) (tree03-list r)))
  (parachute:is eq nil (tree03-list (sl:seq-drop-last 20 '(1 2)))))

(parachute:define-test seq-drop-last.extensions-and-retry
  (dolist (type '(bit (unsigned-byte 8) character))
    (let* ((s (make-array 4 :element-type type :initial-contents
                          (if (eq type 'character) '(#\a #\b #\c #\d) '(1 0 1 0))
                          :fill-pointer 2))
           (r (sl:seq-drop-last 2 s)))
      (parachute:is = 0 (length r))
      (parachute:is equal (array-element-type s) (array-element-type r))
      (parachute:false (eq s r))
      (parachute:is equalp (subseq s 0 1) (sl:seq-drop-last 1 s))))
  (let ((table (make-hash-table)))
    (setf (gethash :k table) 7)
    (dolist (source (list table (sl:dict :k 7) (sl:hash-set 7)
                         (make-instance 'tree03-source :items '(7))
                         (make-instance 'tree03-collected :items '(7))))
      (let* ((*tree03-collects* 0) (r (sl:seq-drop-last 0 source)))
        (parachute:true (sl:lazy-seq-p r))
        (parachute:is = 0 *tree03-collects*)
        (parachute:is = 1 (length (tree03-list r))))))
  (dolist (n '(-1 1/2 :bad))
    (parachute:fail (sl:seq-drop-last n '(1)) type-error))
  (let ((attempts 0))
    (let ((r (sl:seq-drop-last
              1 (tree03-stream '(1 2 3)
                               (lambda (i) (when (= i 1) (incf attempts)
                                             (when (= attempts 1) (error "retry source"))))))))
      (parachute:fail (sl:seq-first r) simple-error)
      (parachute:is equal '(1 2) (tree03-list r))
      (parachute:is = 2 attempts)))
  (parachute:fail (sl:seq-drop-last 1 (sl:map-entry :k 7)) type-error)

  (let ((table (make-hash-table)))
    (setf (gethash 1 table) 10 (gethash 2 table) 20 (gethash 3 table) 30)
    (dolist (source (list table (sl:dict 1 10 2 20 3 30) (sl:hash-set 1 2 3)))
      (let* ((r (sl:seq-drop-last 0 source)) (items (tree03-list r)))
        (parachute:true (sl:lazy-seq-p r))
        (parachute:is = 3 (length items))
        (parachute:is equal items (tree03-list r))
        (if (typep (first items) 'sl:map-entry)
            (parachute:is equal '((1 10) (2 20) (3 30))
                          (sort (mapcar (lambda (e) (list (sl:entry-key e) (sl:entry-value e))) items)
                                #'< :key #'first))
            (parachute:is equal '(1 2 3) (sort (copy-list items) #'<)))))))
