(in-package #:sophie-lisp.tests)

(defun map03-call (name &rest args) (apply (symbol-function name) args))

;;;; Independent Chapter 6 mapping contracts; no other Chapter 6 operation is
;;;; used as a fixture or oracle. Expectations precede the implementation.
(defun map03-list (source &optional (limit 100))
  (loop with view = source for i below limit
        until (sl:seq-emptyp view)
        collect (sl:seq-first view)
        do (setf view (sl:seq-rest view))
        finally (unless (sl:seq-emptyp view)
                  (parachute:true nil "MAP03-LIST exceeded its finite fixture bound"))))

(defun map03-stream (items observer &optional (index 0))
  (sl:make-lazy-seq
   (lambda ()
     (funcall observer index)
     (if items
         (sl:lazy-cons (car items) (map03-stream (cdr items) observer (1+ index)))
         nil))))

(defun map03-prefix (source n)
  ;; Do not inspect the tail after the final requested element.
  (loop with view = source for i below n collect (sl:seq-first view)
        do (when (< (1+ i) n) (setf view (sl:seq-rest view)))))

(defun map03-table ()
  (let ((table (make-hash-table :test 'equal)))
    (setf (gethash "key" table) 7) table))

(defclass map03-source () ((items :initarg :items :reader map03-items)))
(defclass map03-collected (map03-source) ())
(defmethod sl:seqablep ((x map03-source)) t)
(defmethod sl:seq-emptyp ((x map03-source)) (null (map03-items x)))
(defmethod sl:seq-first ((x map03-source)) (car (map03-items x)))
(defmethod sl:seq-rest ((x map03-source)) (cdr (map03-items x)))
(defclass map03-collector ()
  ((items :initform nil :accessor map03-acc) (result :accessor map03-result)))
(defvar *map03-collects* 0)
(defvar *map03-refusal* nil)
(defmethod sl:make-collector-for ((x map03-collected) &key)
  (incf *map03-collects*) (make-instance 'map03-collector))
(defmethod sl:collector-accumulate ((c map03-collector) x)
  (when *map03-refusal* (error *map03-refusal*))
  (push x (map03-acc c)) c)
(defmethod sl:collector-result ((c map03-collector))
  (if (slot-boundp c 'result) (map03-result c)
      (setf (map03-result c)
            (make-instance 'map03-collected :items (reverse (map03-acc c))))))


(defclass map03-opening (map03-source)
  ((failed :initform nil :accessor map03-opening-failed)))

(defmethod sl:seq-emptyp ((x map03-opening))
  (unless (map03-opening-failed x)
    (setf (map03-opening-failed x) t)
    (error "retry opening callback result"))
  (null (map03-items x)))

(parachute:define-test seq-map.representations-and-validation
  (let* ((a (vector 1 2)) (b (vector 10 20 30)) (r (sl:seq-map #'+ a b)))
    (parachute:is equalp #(11 22) r)
    (parachute:is eq t (array-element-type r))
    (parachute:false (eq a r)) (parachute:false (eq b r))
    (parachute:is equalp #(1 2) a))
  (dolist (type '(bit (unsigned-byte 8) t))
    (let* ((s (make-array 4 :element-type type :initial-contents '(1 0 1 0)
                           :fill-pointer 3))
           (r (sl:seq-map #'identity s)))
      (parachute:is equalp #(1 0 1) r)
      (parachute:is eq t (array-element-type r))
      (parachute:false (eq s r))))
  (parachute:is equal '(2 3) (sl:seq-map #'1+ '(1 2)))
  (parachute:is equal "AB" (sl:seq-map #'char-upcase "ab"))
  (parachute:true (sl:lazy-seq-p (sl:seq-map #'+ '(1) #(2))))
  (parachute:is equal '(3) (map03-list (sl:seq-map #'+ '(1) #(2))))
  (parachute:is eq nil (sl:seq-map #'identity nil))
  (parachute:fail (funcall #'sl:seq-map #'identity) program-error)
  ;; Rest arguments are sources, not keyword options.
  (parachute:fail (map03-list (sl:seq-map #'list '(1) :key)) type-error))

(parachute:define-test seq-map.forcing-and-retry
  (let* ((events nil)
         (a (map03-stream '(1) (lambda (i) (push (list :a i) events))))
         (b (map03-stream '(10 20) (lambda (i) (push (list :b i) events))))
         (r (sl:seq-map (lambda (x y) (push :call events) (+ x y)) a b)))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is eq nil events)
    (parachute:is = 11 (sl:seq-first r))
    (parachute:is equal '((:a 0) (:b 0) :call) (reverse events))
    (parachute:is = 11 (sl:seq-first r))
    (parachute:is = 3 (length events))
    (parachute:true (sl:seq-emptyp (sl:seq-rest r)))
    (parachute:is equal '((:a 0) (:b 0) :call (:a 1)) (reverse events)))
  (let ((symbol (make-symbol "MAP03-LATE")) (calls 0))
    (setf (symbol-function symbol) #'identity)
    (unwind-protect
         (let ((r (sl:seq-map symbol (map03-stream '(4 5) (constantly nil)))))
           (setf (symbol-function symbol)
                 (lambda (x) (incf calls) (if (= calls 1) (error "retry") (* x 2))))
           (parachute:fail (sl:seq-first r) simple-error)
           (parachute:is = 8 (sl:seq-first r))
           (parachute:is = 8 (sl:seq-first r))
           (parachute:is = 2 calls))
      (fmakunbound symbol))))

(parachute:define-test seq-map.extensions-and-entry-validation
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (let* ((calls 0)
           (r (sl:seq-map (lambda (entry)
                            (incf calls)
                            (parachute:true (typep entry 'sl:map-entry))
                            (sl:map-entry (sl:entry-key entry) (sl:entry-value entry))) source)))
      (parachute:true (sl:ordered-dict-p r))
      (parachute:is = 1 calls)
      (parachute:true (every (lambda (entry) (typep entry 'sl:map-entry))
                             (map03-list r)))
      (parachute:is equal '(("key" 7))
                    (mapcar (lambda (entry) (list (sl:entry-key entry) (sl:entry-value entry)))
                            (map03-list r)))))
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (parachute:fail (sl:seq-map (constantly :not-an-entry) source) type-error))
  (parachute:is equalp (map 'vector #'char-code "ab") (sl:seq-map #'char-code "ab"))
  (let ((r (sl:seq-map (constantly :same) (sl:hash-set 1 2))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is equal '(:same :same) (map03-list r)))
  (let* ((*map03-collects* 0)
         (r (sl:seq-map #'1+ (make-instance 'map03-collected :items '(1 2)))))
    (parachute:true (typep r 'map03-collected))
    (parachute:is equal '(2 3) (map03-items r))
    (parachute:is = 1 *map03-collects*))
  (parachute:true (sl:lazy-seq-p
                   (sl:seq-map #'identity (make-instance 'map03-source :items '(1)))))
  (let ((*map03-refusal* (make-condition 'simple-error)))
    (parachute:fail (sl:seq-map #'identity
                              (make-instance 'map03-collected :items '(1))) simple-error))
  (parachute:fail (sl:seq-map #'identity (sl:map-entry :a 1)) type-error)

  (let ((table (make-hash-table)))
    (setf (gethash 1 table) 10 (gethash 2 table) 20 (gethash 3 table) 30)
    (dolist (source (list table (sl:dict 1 10 2 20 3 30)))
      (let* ((seen nil)
             (r (sl:seq-map (lambda (e)
                              (let ((pair (list (sl:entry-key e) (sl:entry-value e))))
                                (push pair seen)
                                (sl:map-entry (sl:entry-key e) (sl:entry-value e)))) source)))
        (parachute:true (sl:ordered-dict-p r))
        (let ((items (mapcar (lambda (e) (list (sl:entry-key e) (sl:entry-value e)))
                             (map03-list r))))
          (parachute:is equal (reverse seen) items)
          (parachute:is equal '((1 10) (2 20) (3 30))
                        (sort (copy-list items) #'< :key #'first))))))
)

(parachute:define-test seq-map-indexed.representations-and-validation
  (let* ((s (vector 'a 'b)) (r (sl:seq-map-indexed #'list s)))
    (parachute:is equalp #((0 a) (1 b)) r)
    (parachute:is eq t (array-element-type r))
    (parachute:false (eq s r)))
  (parachute:is equal '((0 a) (1 b)) (sl:seq-map-indexed #'list '(a b)))
  (parachute:is equal "AB" (sl:seq-map-indexed (lambda (i x) (declare (ignore i)) (char-upcase x)) "ab"))
  (parachute:is equalp #(0 1) (sl:seq-map-indexed (lambda (i x) (declare (ignore x)) i) #*10))
  (parachute:is eq nil (sl:seq-map-indexed #'list nil))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (map03-call 'sl:seq-map-indexed #'list '(a) key #'identity) program-error)))

(parachute:define-test seq-map-indexed.forcing
  (let* ((forces nil) (calls nil)
         (r (sl:seq-map-indexed
             (lambda (i x) (push (list i x) calls) (list i x))
             (map03-stream '(a b c) (lambda (i) (push i forces))))))
    (parachute:is eq nil forces) (parachute:is eq nil calls)
    (parachute:is equal '((0 a) (1 b)) (map03-prefix r 2))
    (parachute:is equal '(1 0) forces)
    (parachute:is equal '((1 b) (0 a)) calls)
    (parachute:is eq (sl:seq-first r) (sl:seq-first r))
    (parachute:is = 2 (length calls))))

(parachute:define-test seq-map-indexed.extensions-and-validation
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (let ((r (sl:seq-map-indexed
              (lambda (i e) (sl:map-entry i (sl:entry-value e))) source)))
      (parachute:true (sl:ordered-dict-p r))
      (parachute:is equal '((0 7))
                    (mapcar (lambda (entry) (list (sl:entry-key entry) (sl:entry-value entry)))
                            (map03-list r)))))
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (parachute:fail (sl:seq-map-indexed (lambda (i e) (declare (ignore i e)) :bad) source)
                    type-error))
  (let ((calls 0)
        (s (make-instance 'map03-source :items '(a b))))
    (let ((r (sl:seq-map-indexed (lambda (i x) (incf calls) (list i x)) s)))
      (parachute:true (sl:lazy-seq-p r)) (parachute:is = 0 calls)
      (parachute:is equal '((0 a) (1 b)) (map03-list r))
      (parachute:is = 2 calls)))
  (let* ((*map03-collects* 0) (calls 0)
         (r (sl:seq-map-indexed (lambda (i x) (incf calls) (list i x))
                                (make-instance 'map03-collected :items '(a b)))))
    (parachute:is = 2 calls)
    (parachute:true (typep r 'map03-collected))
    (parachute:is equal '((0 a) (1 b)) (map03-items r))
    (parachute:is = 1 *map03-collects*))
  (let ((r (sl:seq-map-indexed (lambda (i x) (declare (ignore x)) i) (sl:hash-set :a :b))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is equal '(0 1) (map03-list r)))
  (parachute:fail (sl:seq-map-indexed 7 '(1)) type-error))

(parachute:define-test seq-keep.representations-and-validation
  (let* ((s (vector 1 2 3))
         (r (sl:seq-keep (lambda (x) (and (oddp x) (* x 10))) s)))
    (parachute:is equalp #(10 30) r) (parachute:is eq t (array-element-type r))
    (parachute:false (eq s r)) (parachute:is equalp #(1 2 3) s))
  (parachute:is equal '(0 :yes) (sl:seq-keep #'identity '(nil 0 nil :yes)))
  (parachute:is equal "AB" (sl:seq-keep #'char-upcase "ab"))
  (parachute:is equalp #() (sl:seq-keep (constantly nil) #*10))
  (dolist (key '(:test :test-not :key))
    (parachute:fail (map03-call 'sl:seq-keep #'identity '(1) key #'identity) program-error)))

(parachute:define-test seq-keep.forcing
  (let* ((forces nil) (calls nil)
         (r (sl:seq-keep (lambda (x) (push x calls) (and (oddp x) (* 10 x)))
                        (map03-stream '(2 1 4 3 6) (lambda (i) (push i forces))))))
    (parachute:is eq nil calls) (parachute:is eq nil forces)
    (parachute:is = 10 (sl:seq-first r))
    (parachute:is equal '(1 2) calls)
    (parachute:is equal '(1 0) forces)
    (parachute:is equal '(10 30) (map03-prefix r 2))
    (parachute:is equal '(3 4 1 2) calls)
    (parachute:is equal '(3 2 1 0) forces)))

(parachute:define-test seq-keep.extensions-and-retry
  (parachute:is equalp (map 'vector #'char-code "ab") (sl:seq-keep #'char-code "ab"))
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (let* ((calls 0)
           (r (sl:seq-keep (lambda (entry)
                             (incf calls)
                             (sl:map-entry (sl:entry-key entry) (sl:entry-value entry))) source)))
      (parachute:true (sl:ordered-dict-p r))
      (parachute:is = 1 calls)
      (parachute:is equal '(("key" 7))
                    (mapcar (lambda (entry) (list (sl:entry-key entry) (sl:entry-value entry)))
                            (map03-list r)))))
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (let* ((result (sl:seq-keep (lambda (entry)
                                  (sl:map-entry (sl:entry-key entry) nil))
                                source))
           (entries (map03-list result)))
      (parachute:true (sl:ordered-dict-p result))
      (parachute:is = 1 (length entries))
      (parachute:true (typep (first entries) 'sl:map-entry))
      (parachute:is equal "key" (sl:entry-key (first entries)))
      (parachute:is eq nil (sl:entry-value (first entries)))))
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (parachute:fail (sl:seq-keep (constantly :not-an-entry) source) type-error))
  (let* ((*map03-collects* 0) (calls 0)
         (r (sl:seq-keep (lambda (x) (incf calls) (and (oddp x) (* x 10)))
                         (make-instance 'map03-collected :items '(1 2 3)))))
    (parachute:is = 3 calls)
    (parachute:true (typep r 'map03-collected))
    (parachute:is equal '(10 30) (map03-items r))
    (parachute:is = 1 *map03-collects*))
  (let* ((calls 0)
         (r (sl:seq-keep (lambda (x) (declare (ignore x)) (incf calls)
                          (if (= calls 1) (error "retry keep") :ok))
                         (map03-stream '(7) (constantly nil)))))
    (parachute:is = 0 calls)
    (parachute:fail (sl:seq-first r) simple-error)
    (parachute:is eq :ok (sl:seq-first r)))
  (parachute:is equal '(:same :same)
                (map03-list (sl:seq-keep (constantly :same) (sl:hash-set 1 2)))))

(parachute:define-test seq-mapcat.representations-and-validation
  (let* ((s (vector 1 2)) (r (sl:seq-mapcat (lambda (x) (list x (- x))) s)))
    (parachute:is equalp #(1 -1 2 -2) r) (parachute:is eq t (array-element-type r))
    (parachute:false (eq s r)) (parachute:is equalp #(1 2) s))
  (let* ((piece (list :a :b)) (r (sl:seq-mapcat (constantly piece) '(1 2))))
    (parachute:is equal '(:a :b :a :b) r)
    (parachute:false (eq piece r)) (parachute:is equal '(:a :b) piece))
  (parachute:is equal "aabb" (sl:seq-mapcat (lambda (x) (list x x)) "ab"))
  (parachute:is equalp #() (sl:seq-mapcat (constantly nil) #*10))
  (parachute:fail (funcall #'sl:seq-mapcat #'list '(1) :key #'identity) program-error))

(parachute:define-test seq-mapcat.forcing
  (let* ((calls nil) (forces nil)
         (r (sl:seq-mapcat
             (lambda (x)
               (push x calls)
               (map03-stream (list x (- x)) (lambda (i) (push (list x i) forces))))
             (map03-stream '(1 2) (constantly nil)))))
    (parachute:is eq nil calls) (parachute:is eq nil forces)
    (parachute:is = 1 (sl:seq-first r))
    (parachute:is equal '(1) calls)
    (parachute:is equal '((1 0)) forces)
    (parachute:is equal '(1 -1) (map03-prefix r 2))
    (parachute:is equal '(1) calls)
    (parachute:is equal '((1 1) (1 0)) forces))
  ;; Finite sentinel models an arbitrarily long first callback result: an
  ;; accidental pre-scan fails promptly rather than hanging a test process.
  (let ((calls 0))
    (let ((r (sl:seq-mapcat
              (lambda (x) (incf calls)
                (map03-stream (make-list 20 :initial-element x)
                              (lambda (i) (when (> i 3) (error "overforce")))))
              (map03-stream '(9 10) (constantly nil)))))
      (parachute:is equal '(9 9 9) (map03-prefix r 3))
      (parachute:is = 1 calls))))

;; Fault injection is confined to this returned object, not protocol methods
;; on built-in sources. Inherited FIRST/REST supply the remaining primitives.
(define-condition map03-validation-retry (error) ())

(defclass map03-validating (map03-source)
  ((validations :initform nil :accessor map03-validations)
   (empties :initform 0 :accessor map03-validation-empties)))

(defmethod sl:seqablep ((x map03-validating))
  (push x (map03-validations x))
  (when (null (cdr (map03-validations x)))
    (error (quote map03-validation-retry)))
  t)

(defmethod sl:seq-emptyp ((x map03-validating))
  (incf (map03-validation-empties x))
  (call-next-method))

(parachute:define-test seq-mapcat.extensions-and-retry
  (parachute:fail (sl:seq-mapcat (constantly 7) '(1)) type-error)
  (let ((r (sl:seq-mapcat (constantly 7) (map03-stream '(1) (constantly nil)))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:fail (sl:seq-first r) type-error))
  (let ((r (sl:seq-mapcat (constantly '(:same :same)) (sl:hash-set 1 2))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is equal '(:same :same :same :same) (map03-list r)))
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (let ((r (sl:seq-mapcat
              (lambda (e) (list (sl:map-entry (sl:entry-key e) (sl:entry-value e)))) source)))
      (parachute:true (sl:ordered-dict-p r))
      (parachute:is equal '(("key" 7))
                    (mapcar (lambda (entry) (list (sl:entry-key entry) (sl:entry-value entry)))
                            (map03-list r)))))
  (dolist (source (list (map03-table) (sl:dict "key" 7)))
    (parachute:fail (sl:seq-mapcat (constantly (list :not-an-entry)) source) type-error))
  (parachute:fail (sl:seq-mapcat (constantly (sl:map-entry :a 1)) '(1)) type-error)

  ;; A successful callback must survive failure opening its custom result.
  (let* ((calls 0) (piece (make-instance 'map03-opening :items '(8 9)))
         (r (sl:seq-mapcat (lambda (x) (declare (ignore x)) (incf calls) piece)
                           (map03-stream '(1) (constantly nil)))))
    (parachute:is = 0 calls)
    (parachute:fail (sl:seq-first r) simple-error)
    (parachute:is = 1 calls)
    (parachute:is equal '(8 9) (map03-list r))
    (parachute:is = 1 calls)
    (parachute:is equal '(8 9) (map03-list r))
    (parachute:is = 1 calls)
    (parachute:is equal '(8 9) (map03-items piece)))
  (dolist (class '(map03-source map03-collected))
    (let* ((*map03-collects* 0) (calls 0)
           (r (sl:seq-mapcat (lambda (x) (incf calls) (list x (- x)))
                             (make-instance class :items '(1 2)))))
      (parachute:is = (if (eq class 'map03-collected) 2 0) calls)
      (parachute:true (if (eq class 'map03-collected)
                          (typep r 'map03-collected) (sl:lazy-seq-p r)))
      (parachute:is equal '(1 -1 2 -2) (map03-list r))
      (parachute:is = 2 calls)))
  ;; Section 6.1.1 counts successful callbacks, independently of a later
  ;; protocol failure. This fails in SEQABLEP before any emptiness observation,
  ;; unlike the separate MAP03-OPENING regression above.
  (let* ((calls 0)
         (piece (make-instance (quote map03-validating) :items (quote (8 9))))
         (r (sl:seq-mapcat (lambda (x) (declare (ignore x)) (incf calls) piece)
                           (map03-stream (quote (1)) (constantly nil)))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is = 0 calls)
    (parachute:is eq nil (map03-validations piece))
    (parachute:is = 0 (map03-validation-empties piece))
    (parachute:fail (sl:seq-first r) map03-validation-retry)
    (parachute:is = 1 calls)
    (parachute:is equal (list piece) (map03-validations piece))
    (parachute:is = 0 (map03-validation-empties piece))
    ;; Retry the very same unresolved node; both validation attempts must
    ;; have received the exact object returned by the one successful callback.
    (parachute:is = 8 (sl:seq-first r))
    (parachute:is = 1 calls)
    ;; Validation frequency is unspecified; identity and retry are not.
    (parachute:true
     (and (>= (length (map03-validations piece)) 2)
          (every (lambda (x) (eq x piece)) (map03-validations piece))))
    (parachute:true (plusp (map03-validation-empties piece)))
    (parachute:is = 8 (sl:seq-first r))
    (parachute:is = 1 calls)
    (parachute:is equal (quote (8 9)) (map03-list r))
    (parachute:is = 1 calls)
    (parachute:is equal (quote (8 9)) (map03-list r))
    (parachute:is = 1 calls)
    (parachute:is equal (quote (8 9)) (map03-items piece)))
)

;;;; Chapter 6.1.4-5 and CONCATENATE/INTERLEAVE, independent serial/round oracles.
(defun multi03-list (source)
  (loop with view = source for i below 100 until (sl:seq-emptyp view)
        collect (sl:seq-first view) do (setf view (sl:seq-rest view))
        finally (unless (sl:seq-emptyp view)
                  (parachute:true nil "MULTI03-LIST exceeded its finite fixture bound"))))
(defun multi03-stream (items observer &optional (i 0))
  (sl:make-lazy-seq
   (lambda () (funcall observer i)
     (if items (sl:lazy-cons (car items) (multi03-stream (cdr items) observer (1+ i))) nil))))
(defun multi03-prefix (source n)
  (loop with view = source for i below n collect (sl:seq-first view)
        do (when (< (1+ i) n) (setf view (sl:seq-rest view)))))
(defclass multi03-source () ((items :initarg :items :reader multi03-items)))
(defclass multi03-collected (multi03-source) ())
(defclass multi03-other (multi03-source) ())
(defmethod sl:seqablep ((x multi03-source)) t)
(defmethod sl:seq-emptyp ((x multi03-source)) (null (multi03-items x)))
(defmethod sl:seq-first ((x multi03-source)) (car (multi03-items x)))
(defmethod sl:seq-rest ((x multi03-source)) (cdr (multi03-items x)))
(defclass multi03-collector ()
  ((items :initform nil :accessor multi03-acc) (result :accessor multi03-result)))
(defvar *multi03-collects* 0)
(defmethod sl:make-collector-for ((x multi03-collected) &key)
  (incf *multi03-collects*) (make-instance 'multi03-collector))
(defmethod sl:collector-accumulate ((c multi03-collector) x) (push x (multi03-acc c)) c)
(defmethod sl:collector-result ((c multi03-collector))
  (if (slot-boundp c 'result) (multi03-result c)
      (setf (multi03-result c)
            (make-instance 'multi03-collected :items (reverse (multi03-acc c))))))

(parachute:define-test seq-concatenate.representations-and-validation
  (let* ((a (vector 1 2)) (b (vector 3)) (r (sl:seq-concatenate a b #(4 5))))
    (parachute:is equalp #(1 2 3 4 5) r)
    (parachute:is eq t (array-element-type r))
    (parachute:false (eq r a)) (parachute:false (eq r b))
    (parachute:is equalp #(1 2) a))
  (dolist (source (list (list 1 2) (vector 1 2) (copy-seq "ab")))
    (let ((r (sl:seq-concatenate source)))
      (parachute:is equalp source r) (parachute:false (eq source r))))
  (parachute:is equal '(1 2 3) (sl:seq-concatenate '(1) nil '(2 3)))
  (parachute:is equal "abc" (sl:seq-concatenate "a" "" "bc"))
  (let* ((s (make-array 4 :element-type 'bit :initial-contents '(1 0 1 0) :fill-pointer 2))
         (r (sl:seq-concatenate s #*1)))
    (parachute:is equalp #(1 0 1) r) (parachute:is eq t (array-element-type r)))
  (let* ((s (make-array 0 :element-type 'bit)) (r (sl:seq-concatenate s)))
    (parachute:is = 0 (length r)) (parachute:is eq t (array-element-type r))
    (parachute:false (eq s r)))
  (parachute:fail (funcall #'sl:seq-concatenate) program-error))

(parachute:define-test seq-concatenate.forcing-and-invalid-sources
  (let* ((events nil)
         (r (sl:seq-concatenate
             (multi03-stream '(1 2) (lambda (i) (push (list :a i) events)))
             (multi03-stream '(3) (lambda (i) (push (list :b i) events))))))
    (parachute:is eq nil events)
    (parachute:is equal '(1 2) (multi03-prefix r 2))
    (parachute:is equal '((:a 0) (:a 1)) (reverse events))
    (parachute:is equal '(1 2 3) (multi03-prefix r 3))
    (parachute:is equal '((:a 0) (:a 1) (:a 2) (:b 0)) (reverse events))
    (parachute:is equal '(1 2 3) (multi03-list r))
    (parachute:is equal '((:a 0) (:a 1) (:a 2) (:b 0) (:b 1)) (reverse events)))
  (let ((r (sl:seq-concatenate
            (multi03-stream (make-list 20 :initial-element :a)
                            (lambda (i) (when (> i 2) (error "overforce"))))
            :test)))
    (parachute:is equal '(:a :a :a) (multi03-prefix r 3)))
  (dolist (keyword '(:test :test-not :key))
    (let ((r (sl:seq-concatenate (multi03-stream '(1) (constantly nil)) keyword)))
      (parachute:is = 1 (sl:seq-first r))
      (parachute:fail (sl:seq-emptyp (sl:seq-rest r)) type-error))))

(parachute:define-test seq-concatenate.extensions-and-coalescing
  (let ((r (sl:seq-concatenate '(1) #(2))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is equal '(1 2) (multi03-list r)))
  (let* ((*multi03-collects* 0)
         (a (make-instance 'multi03-collected :items '(1)))
         (b (make-instance 'multi03-collected :items '(2)))
         (r (sl:seq-concatenate a b)))
    (parachute:true (typep r 'multi03-collected))
    (parachute:is equal '(1 2) (multi03-items r))
    (parachute:is = 1 *multi03-collects*))
  (dolist (class '(multi03-source multi03-other))
    (let ((r (sl:seq-concatenate (make-instance 'multi03-collected :items '(1))
                                (make-instance class :items '(2)))))
      (parachute:true (sl:lazy-seq-p r))
      (parachute:is equal '(1 2) (multi03-list r))))
  (let ((r (sl:seq-concatenate (sl:hash-set 1) (sl:hash-set 1))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is equal '(1 1) (multi03-list r)))
  (let* ((r (sl:seq-concatenate (sl:dict :k 1) (sl:dict :k 2)))
         (items (multi03-list r)))
    (parachute:true (sl:ordered-dict-p r))
    (parachute:true (every (lambda (entry) (typep entry 'sl:map-entry)) items))
    (parachute:is equal '(:k) (mapcar #'sl:entry-key items))
    (parachute:is equal '(2) (mapcar #'sl:entry-value items)))
  (parachute:is equal '((a . 1) :b 2)
                (sl:seq-concatenate '((a . 1)) '(:b 2)))

  (let ((table (make-hash-table)))
    (setf (gethash 1 table) 10 (gethash 2 table) 20)
    (let* ((items (multi03-list (sl:seq-concatenate table (sl:dict 3 30 4 40))))
           (pairs (mapcar (lambda (e) (list (sl:entry-key e) (sl:entry-value e))) items)))
      (parachute:is = 4 (length pairs))
      (parachute:is equal '((1 10) (2 20)) (sort (subseq pairs 0 2) #'< :key #'first))
      (parachute:is equal '((3 30) (4 40)) (sort (subseq pairs 2) #'< :key #'first))))
  (let ((items (multi03-list (sl:seq-concatenate (sl:hash-set 1 2) (sl:hash-set 2 3)))))
    (parachute:is equal '(1 2) (sort (subseq items 0 2) #'<))
    (parachute:is equal '(2 3) (sort (subseq items 2) #'<)))
)

(parachute:define-test seq-interleave.representations-and-truncation
  (let ((r (sl:seq-interleave '(1 2) #(10 20))))
    (parachute:true (sl:lazy-seq-p r))
    (parachute:is equal '(1 10 2 20) (multi03-list r)))
  (let* ((a (list 1 2)) (b (list 10 20)) (r (sl:seq-interleave a b)))
    (parachute:true (listp r)) (parachute:is equal '(1 10 2 20) r)
    (parachute:false (eq a r)) (parachute:false (eq b r)))
  (parachute:is equal "aXbY" (sl:seq-interleave "ab" "XYZ"))
  (let* ((s (make-array 4 :element-type 'bit :initial-contents '(1 0 1 0) :fill-pointer 2))
         (r (sl:seq-interleave s #*01)))
    (parachute:is equalp #(1 0 0 1) r) (parachute:is eq t (array-element-type r))
    (parachute:false (eq s r)))
  (parachute:is equal '(1 10) (sl:seq-interleave '(1 2) '(10)))
  (let ((r (sl:seq-interleave #() #(1))))
    (parachute:is = 0 (length r)) (parachute:is eq t (array-element-type r))))

(parachute:define-test seq-interleave.forcing-and-empty-input
  (parachute:is eq nil (sl:seq-interleave))
  (let* ((events nil)
         (r (sl:seq-interleave
             (multi03-stream '(1 2) (lambda (i) (push (list :a i) events)))
             (multi03-stream '(10) (lambda (i) (push (list :b i) events)))
             (multi03-stream '(100 200) (lambda (i) (push (list :c i) events))))))
    (parachute:is eq nil events)
    (parachute:is = 1 (sl:seq-first r))
    (parachute:is equal '((:a 0) (:b 0) (:c 0)) (reverse events))
    (parachute:is equal '(1 10 100) (multi03-prefix r 3))
    (parachute:is = 3 (length events))
    (parachute:is equal '(1 10 100) (multi03-list r))
    (parachute:is equal '((:a 0) (:b 0) (:c 0) (:a 1) (:b 1)) (reverse events)))
  (let ((later 0))
    (let ((r (sl:seq-interleave (multi03-stream nil (constantly nil))
                              (multi03-stream '(1) (lambda (i) (declare (ignore i)) (incf later))))))
      (parachute:true (sl:seq-emptyp r))
      (parachute:is = 0 later))))

(parachute:define-test seq-interleave.extensions-and-invalid-sources
  (let ((table (make-hash-table)))
    (setf (gethash :key table) 7)
    (dolist (source (list table (sl:dict :key 7)))
      (let ((r (sl:seq-interleave source '(9))))
        (parachute:true (sl:lazy-seq-p r))
        (let ((items (multi03-list r)))
          (parachute:true (typep (first items) 'sl:map-entry))
          (parachute:is = 7 (sl:entry-value (first items)))
          (parachute:is = 9 (second items))))))
  (let ((r (sl:seq-interleave (sl:hash-set 1) (sl:hash-set 1))))
    (parachute:true (sl:lazy-seq-p r)) (parachute:is equal '(1 1) (multi03-list r)))
  (let* ((events nil)
         (r (sl:seq-interleave (multi03-stream '(1) (lambda (i) (push i events))) :key)))
    (parachute:is eq nil events)
    (parachute:fail (sl:seq-first r) type-error)
    (parachute:is equal '(0) events))
  (let* ((*multi03-collects* 0)
         (r (sl:seq-interleave (make-instance 'multi03-collected :items '(1 2))
                              (make-instance 'multi03-collected :items '(3 4)))))
    (parachute:true (typep r 'multi03-collected))
    (parachute:is equal '(1 3 2 4) (multi03-items r))
    (parachute:is = 1 *multi03-collects*))

  (dolist (class '(multi03-source multi03-collected))
    (let* ((*multi03-collects* 0)
           (r (sl:seq-interleave (make-instance class :items '(1 2))
                                (make-instance class :items '(10 20)))))
      (parachute:true (if (eq class 'multi03-collected)
                          (typep r 'multi03-collected) (sl:lazy-seq-p r)))
      (parachute:is equal '(1 10 2 20) (multi03-list r))))
  (let ((table (make-hash-table)))
    (setf (gethash 1 table) 10 (gethash 2 table) 20 (gethash 3 table) 30)
    (dolist (source (list table (sl:dict 1 10 2 20 3 30) (sl:hash-set 1 2 3)))
      (let* ((items (multi03-list (sl:seq-interleave source '(:a :b :c))))
             (left (loop for (x marker) on items by #'cddr collect x))
             (right (loop for (x marker) on items by #'cddr collect marker)))
        (parachute:is equal '(:a :b :c) right)
        (parachute:is = 6 (length items))
        (if (typep (first left) 'sl:map-entry)
            (parachute:is equal '((1 10) (2 20) (3 30))
                          (sort (mapcar (lambda (e) (list (sl:entry-key e) (sl:entry-value e))) left)
                                #'< :key #'first))
            (parachute:is equal '(1 2 3) (sort left #'<))))))
)

;;;; Independent Chapter 6 substitution oracles. No pending operation is used
;;;; as a helper: observation and extension fixtures belong to S-POLICY.
(defun select0-stream (items counter)
  (sl:make-lazy-seq
   (lambda ()
     (incf (car counter))
     (if items
         (sl:lazy-cons (car items) (select0-stream (cdr items) counter))
         nil))))

(defun select0-model-check (operation oracle)
  ;; 2 directions * 4 counts * 3 starts * 3 ends = 72 finite models.
  (dolist (back '(nil t))
    (dolist (count '(nil 0 1 2))
      (dolist (start '(0 1 3))
        (dolist (end '(3 5 9))
          (let* ((source (list 1 2 1 3 1))
                 (options (list :start start :end end :count count :from-end back))
                 (expected (apply oracle source :start start :end (min end 5)
                                  :count count :from-end back nil))
                 (result (apply operation source options)))
            (parachute:is equal expected result)
            (parachute:false (eq source result))
            (parachute:is equal '(1 2 1 3 1) source)))))))

(defun select0-representation (operation dictionary-operation)
  ;; Each operation replaces selected A characters with a non-character.
  (let* ((source (copy-seq "aba")) (result (funcall operation source)))
    (parachute:is equalp #(9 #\b 9) result)
    (parachute:is eq t (array-element-type result))
    (parachute:false (eq source result))
    (parachute:is string= "aba" source))
  (let ((result (funcall operation "bbb")))
    (parachute:true (stringp result))
    (parachute:is string= "bbb" result))
  (let ((calls 0))
    (dolist (source (list (sl:dict :a 1 :b 2)
                          (let ((h (make-hash-table)))
                            (setf (gethash :a h) 1 (gethash :b h) 2) h)))
      (let ((result (funcall dictionary-operation source
                             (lambda (x) (declare (ignore x)) (incf calls) 1))))
        (parachute:true (sl:ordered-dict-p result))
        (parachute:is = 2 calls)
        (parachute:true (every (lambda (entry) (typep entry 'sl:map-entry))
                               (policy-list result)))
        (parachute:is = 1 (length (policy-list result)))
        (parachute:is eq :replacement (sl:entry-key (first (policy-list result))))
        (parachute:is = 9 (sl:entry-value (first (policy-list result))))
        (parachute:is equal '((:replacement 9))
                      (mapcar (lambda (entry) (list (sl:entry-key entry) (sl:entry-value entry)))
                              (policy-list result)))
        (parachute:is = 2 calls)
        (setf calls 0))))
  (let ((calls 0))
    (let ((result (funcall dictionary-operation (sl:hash-set 1 2)
                           (lambda (x) (declare (ignore x)) (incf calls) 1))))
      (parachute:true (sl:lazy-seq-p result))
      (parachute:is = 0 calls)
      (parachute:is equal '((:replacement 9) (:replacement 9))
                    (mapcar (lambda (entry) (list (sl:entry-key entry) (sl:entry-value entry)))
                            (policy-list result)))
      (parachute:is = 2 calls)
      (parachute:is equal '((:replacement 9) (:replacement 9))
                    (mapcar (lambda (entry) (list (sl:entry-key entry) (sl:entry-value entry)))
                            (policy-list result)))
      (parachute:is = 2 calls))))

(parachute:define-test seq-substitute.model-and-representations
  (select0-model-check (lambda (s &rest o) (apply #'sl:seq-substitute 9 1 s o))
                      (lambda (s &rest o) (apply #'substitute 9 1 s o)))
  (let* ((s (make-array 4 :element-type '(unsigned-byte 8)
                        :initial-contents '(1 2 3 99) :fill-pointer 3))
         (r (sl:seq-substitute 9 2 s :test #'eql :key nil :count 1)))
    (parachute:is equalp #(1 9 3) r)
    (parachute:is eq t (array-element-type r))
    (parachute:false (eq s r)))
  (parachute:is equal '(9 9 2) (sl:seq-substitute 9 1 '(1 1.0 2)))
  (parachute:is equal '(9 1.0 2) (sl:seq-substitute 9 1 '(1 1.0 2) :test #'eql))
  (parachute:fail (sl:seq-substitute 9 1 nil :test-not #'eql) 'program-error))

(parachute:define-test seq-substitute-if.model-and-representations
  (select0-model-check (lambda (s &rest o) (apply #'sl:seq-substitute-if 9 #'oddp s o))
                      (lambda (s &rest o) (apply #'substitute-if 9 #'oddp s o)))
  (let ((r (sl:seq-substitute-if 9 #'oddp #*101 :count 1 :key nil)))
    (parachute:is equalp #(9 0 1) r)
    (parachute:is eq t (array-element-type r)))
  (parachute:fail (sl:seq-substitute-if 9 #'oddp nil :test #'eql) 'program-error)
  (parachute:fail (sl:seq-substitute-if 9 #'oddp nil :test-not #'eql) 'program-error)
  (parachute:is equal '(9 2) (sl:seq-substitute-if 9 #'oddp '(1 2) :key nil)))

(defun select0-timing (operation)
  (let* ((forces (list 0)) (keys nil)
         (s (select0-stream '(1 2 1 3) forces))
         (r (funcall operation s (lambda (x) (push x keys) x))))
    (parachute:is = 0 (car forces))
    (parachute:is equal nil keys)
    (parachute:is = 1 (sl:seq-first r))
    ;; All four selected elements, but not the END sentinel, are required.
    (parachute:is = 4 (car forces))
    (parachute:is equal '(1 1 2 3) (sort (copy-list keys) #'<))
    (parachute:is equal '(1 2 9 3) (policy-list r))
    (parachute:is = 4 (length keys))
    (parachute:is equal '(1 2 9 3) (policy-list r))
    (parachute:is = 4 (length keys)))
  (let* ((tag (gensym))
         (s (sl:make-lazy-seq (lambda () (throw tag :reached)))))
    (parachute:is eq :reached
                  (catch tag (sl:seq-first (funcall operation s #'identity)) :miss))))

(parachute:define-test seq-substitute.forcing-and-retry
  (select0-timing (lambda (s k) (sl:seq-substitute 9 1 s :count 1 :from-end t
                                                 :end 4 :key k)))
  (select0-match-retry (lambda (s k p back) (sl:seq-substitute 9 1 s :test (lambda (a b) (funcall p b) (= a b)) :key k :from-end back :count 2 :end 3))))

(parachute:define-test seq-substitute-if.forcing-and-retry
  (select0-timing (lambda (s k) (sl:seq-substitute-if 9 (lambda (x) (= x 1)) s
                                                    :count 1 :from-end t :end 4 :key k)))
  (select0-match-retry (lambda (s k p back) (sl:seq-substitute-if 9 p s :key k :from-end back :count 2 :end 3))))

(defun select0-errors-and-retry (operation)
  (let* ((n (list 0)) (s (select0-stream '(1) n)))
    (dolist (options '((:start -1) (:start 1/2) (:end -1) (:start 2 :end 1)
                       (:count -1) (:count 1/2) (:key 42)))
      (parachute:fail (apply operation s options) 'type-error))
    (parachute:is = 0 (car n)))
  (let* ((attempts 0) (condition (make-condition 'simple-error))
         (s (sl:lazy-cons 1 nil))
         (r (funcall operation s :key (lambda (x)
                                       (when (= 1 (incf attempts)) (error condition)) x))))
    (parachute:is = 0 attempts)
    (parachute:is eq condition (handler-case (sl:seq-first r) (error (e) e)))
    (parachute:is = 9 (sl:seq-first r))
    (parachute:is = 2 attempts)
    (parachute:is = 9 (sl:seq-first r))
    (parachute:is = 2 attempts))
  (let ((symbol (gensym "LATE-KEY")))
    (unwind-protect
         (progn
           (setf (symbol-function symbol) #'identity)
           (let ((r (funcall operation (sl:lazy-cons 2 nil) :key symbol)))
             (setf (symbol-function symbol) (constantly 1))
             (parachute:is = 9 (sl:seq-first r))))
      (fmakunbound symbol)))
  (let* ((s (copy-seq "aba"))
         (r (funcall operation s :count 0 :key (lambda (x) (declare (ignore x))
                                                        (error "Unexpected key")))))
    (parachute:true (stringp r))
    (parachute:is string= s r)
    (parachute:false (eq s r)))
  (let* ((s (make-instance 'policy-child :items '(1 2 3)))
         (r (funcall operation s)))
    (parachute:true (typep r 'policy-child))
    (parachute:is equal '(9 2 3) (policy-source-items r)))
  (dolist (phase '(:create :accumulate :result))
    (let ((*policy-refusal-phase* phase)
          (*policy-refusal* (make-condition 'policy-refusal)))
      (parachute:is eq *policy-refusal*
                    (handler-case
                        (funcall operation (make-instance 'policy-refusing :items '(1 2 3)))
                      (policy-refusal (e) e)))))
  (let* ((n (list 0))
         (tail (sl:make-lazy-seq (lambda () (error "Untouched substitution tail"))))
         (s (sl:make-lazy-seq (lambda () (incf (car n)) (sl:lazy-cons 1 tail))))
         (r (funcall operation s)))
    (parachute:is = 0 (car n))
    (parachute:is = 9 (sl:seq-first r))
    (parachute:is = 1 (car n)))
  (parachute:fail (funcall operation '(1) :start 2 :end 2) 'type-error)
  (let ((r (funcall operation (sl:lazy-cons 1 nil) :start 2 :end 2)))
    (parachute:is = 1 (sl:seq-first r))
    (parachute:fail (policy-list r) 'type-error)))

(parachute:define-test seq-substitute.extensions-and-validation
  (select0-representation (lambda (s) (sl:seq-substitute 9 #\a s))
                          (lambda (s k) (sl:seq-substitute (sl:map-entry :replacement 9) 1 s :key k)))
  (parachute:fail (sl:seq-substitute 9 1 (sl:dict :a 1) :key #'sl:entry-value) type-error)
  (select0-errors-and-retry (lambda (s &rest o) (apply #'sl:seq-substitute 9 1 s o))))

(parachute:define-test seq-substitute-if.extensions-and-validation
  (select0-representation (lambda (s) (sl:seq-substitute-if 9 (lambda (x) (eql x #\a)) s))
                          (lambda (s k) (sl:seq-substitute-if (sl:map-entry :replacement 9) #'oddp s :key k)))
  (parachute:fail (sl:seq-substitute-if 9 (constantly t) (sl:dict :a 1)) type-error)
  (select0-errors-and-retry (lambda (s &rest o)
                            (apply #'sl:seq-substitute-if 9 (lambda (x) (eql x 1)) s o))))

(defun select0-match-retry (operation)
  (dolist (back '(nil t))
    (let* ((keys nil) (matches nil) (escaped nil) (tag (gensym)) (n (list 0))
           (r (funcall operation (select0-stream '(0 1 2) n)
                       (lambda (x) (push x keys) x)
                       (lambda (x)
                         (push x matches)
                         (when (and (= x 1) (not escaped))
                           (setf escaped t) (throw tag :matcher))
                         (= x 1))
                       back)))
      (parachute:is = 0 (car n))
      (unless back (parachute:is = 0 (sl:seq-first r)))
      (parachute:is eq :matcher (catch tag (policy-list r) :miss))
      (parachute:is equal '(0 9 2) (policy-list r))
      (parachute:is equal '(0 1 2) (sort (copy-list keys) #'<))
      (parachute:is = 2 (count 1 matches))
      (let ((saved (copy-list matches)))
        (parachute:is equal '(0 9 2) (policy-list r))
        (parachute:is equal saved matches)))))
